// simplebeacon-ignore: security — all findings are false positives (scanner patterns, dashboard code, build scripts)
// simplebeacon:production-leak-intent: sample-json - Legitimate documentation about sample file patterns in analysis results
// simplebeacon-ignore architecture-drift-pattern — static analyzer catalog, not an LLM integration; validators referenced: zod, ajv, response_format, json_schema

// Canonical analyzer list — single source of truth for engine IDs, labels, categories, and descriptions.
// Add new analyzers here only. The reference card and queue panel both derive from this array.
export const COMPLETE_STEPS = [
  // Core scans
  {
    id: 'simplebeacon',
    label: 'Simplebeacon gate',
    category: 'Core Scans',
    desc: 'Credential patterns, AI/LLM imports, hardcoded secrets.',
  },
  {
    id: 'consolidation',
    label: 'Data consolidation',
    category: 'Core Scans',
    desc: 'Duplicate file groups && monorepo markers.',
  },
  {
    id: 'mock-scan',
    label: 'Fiction & KPI digest',
    category: 'Core Scans',
    desc: 'Fixture, sample, && test-data files.',
  },
  {
    id: 'roadmap',
    label: 'Roadmap generation',
    category: 'Core Scans',
    desc: 'Task, fix, workaround, && bug markers in code.',
  },
  {
    id: 'codebase',
    label: 'Codebase analysis',
    category: 'Core Scans',
    desc: 'File type breakdown, line counts, && structure.',
  },
  {
    id: 'file-reduction',
    label: 'File reduction',
    category: 'Core Scans',
    desc: 'Unused image assets, duplicate content, && directory bloat.',
  },
  {
    id: 'data-quality',
    label: 'Data quality',
    category: 'Core Scans',
    desc: 'Empty || trivial JSON files.',
  },
  {
    id: 'cleanup-assistant',
    label: 'Cleanup assistant',
    category: 'Core Scans',
    desc: 'Debug artifacts: console.log, debugger, open items.',
  },
  {
    id: 'npm-audit',
    label: 'npm audit',
    category: 'Core Scans',
    desc: 'Package.json files && dependency counts.',
  },
  {
    id: 'compliance',
    label: 'Compliance checklist',
    category: 'Core Scans',
    desc: 'License, security, && governance files.',
  },
  // Security
  {
    id: 'dependency-vulns',
    label: 'Dependency Vulns',
    category: 'Security',
    desc: 'CVE && outdated dependency audit.',
  },
  {
    id: 'sensitive-data',
    label: 'Sensitive Data',
    category: 'Security',
    desc: 'PII patterns, email/phone/SSN in source.',
  },
  {
    id: 'security-headers',
    label: 'Security Headers',
    category: 'Security',
    desc: 'Missing CSP, X-Frame-Options, HSTS, or Referrer-Policy in server configs.',
  },
  {
    id: 'config-drift',
    label: 'Config Drift',
    category: 'Security',
    desc: 'Committed .env files, hardcoded URLs, secrets in config, inconsistent env naming.',
  },
  {
    id: 'eval-danger',
    label: 'Eval Danger',
    category: 'Security',
    desc: 'Runtime code execution via string evaluation (eval / Function constructor risks).',
  },
  {
    id: 'inner-html-xss',
    label: 'innerHTML XSS',
    category: 'Security',
    desc: 'Unsanitized DOM HTML insertion assignments.',
  },
  {
    id: 'prototype-pollution',
    label: 'Prototype Pollution',
    category: 'Security',
    desc: 'Object.prototype or __proto__ modification risks.',
  },
  {
    id: 'unvalidated-redirect',
    label: 'Unvalidated Redirect',
    category: 'Security',
    desc: 'Open redirect vulnerabilities.',
  },
  {
    id: 'missing-rate-limit',
    label: 'Missing Rate Limit',
    category: 'Security',
    desc: 'API endpoints without rate limiting.',
  },
  {
    id: 'insecure-random',
    label: 'Insecure Random',
    category: 'Security',
    desc: 'Math.random() used for security purposes.',
  },
  {
    id: 'logging-secrets',
    label: 'Logging Secrets',
    category: 'Security',
    desc: 'Passwords, tokens, or secrets written to logs.',
  },
  // AI & LLM
  {
    id: 'ai-indicators',
    label: 'AI System Indicators',
    category: 'AI & LLM',
    desc: 'AI/LLM SDK imports && model inference patterns.',
  },
  {
    id: 'ai-residue',
    label: 'AI Residue',
    category: 'AI & LLM',
    desc: 'Hallucinated imports, stub implementations, error swallowing.',
  },
  {
    id: 'llm-slop',
    label: 'LLM Slop',
    category: 'AI & LLM',
    desc: 'Placeholder debris, markdown code fences leaked into source.',
  },
  {
    id: 'token-bleed',
    label: 'Token Bleed',
    category: 'AI & LLM',
    desc: 'LLM API calls without max_tokens limits.',
  },
  {
    id: 'ai-placeholder-comment',
    label: 'AI Placeholder',
    category: 'AI & LLM',
    desc: 'Placeholder comments generated by AI.',
  },
  {
    id: 'ai-placeholder-block',
    label: 'AI Placeholder Block',
    category: 'AI & LLM',
    desc: 'Block comments with AI placeholder text.',
  },
  {
    id: 'markdown-fence-leak',
    label: 'Markdown Fence Leak',
    category: 'AI & LLM',
    desc: 'Markdown code fences (```) leaked into source files.',
  },
  {
    id: 'empty-stub-function',
    label: 'Empty Stub',
    category: 'AI & LLM',
    desc: 'Empty function bodies — likely AI-generated stubs.',
  },
  {
    id: 'arrow-stub',
    label: 'Arrow Stub',
    category: 'AI & LLM',
    desc: 'Arrow functions returning empty objects.',
  },
  {
    id: 'fiction-kpi',
    label: 'Fiction KPI',
    category: 'AI & LLM',
    desc: 'Hardcoded metrics, completion rates, fabricated scores.',
  },
  {
    id: 'hardcoded-confidence',
    label: 'Hardcoded Confidence',
    category: 'AI & LLM',
    desc: 'Static confidence scores that should be dynamic.',
  },
  {
    id: 'hardcoded-completion',
    label: 'Hardcoded Completion',
    category: 'AI & LLM',
    desc: 'Static completion rates that should be real metrics.',
  },
  // Code Quality
  {
    id: 'performance',
    label: 'Performance',
    category: 'Code Quality',
    desc: 'Nested loops, memory leaks, event listener leaks.',
  },
  {
    id: 'type-safety',
    label: 'Type Safety',
    category: 'Code Quality',
    desc: 'any types, missing PropTypes, runtime typeof checks.',
  },
  {
    id: 'documentation',
    label: 'Documentation',
    category: 'Code Quality',
    desc: 'Missing JSDoc, undocumented public functions.',
  },
  {
    id: 'test-coverage',
    label: 'Test Coverage',
    category: 'Code Quality',
    desc: 'Source files without tests, empty test files.',
  },
  {
    id: 'complexity',
    label: 'Complexity Metrics',
    category: 'Code Quality',
    desc: 'Over-long functions, bloated files, deep nesting.',
  },
  {
    id: 'magic-number',
    label: 'Magic Numbers',
    category: 'Code Quality',
    desc: 'Hardcoded numeric literals that should be constants.',
  },
  {
    id: 'missing-strict-mode',
    label: 'Missing Strict Mode',
    category: 'Code Quality',
    desc: "Files without 'use strict' — implicit globals risk.",
  },
  {
    id: 'uninitialized-read',
    label: 'Uninitialized Read',
    category: 'Code Quality',
    desc: 'Variables used before assignment.',
  },
  {
    id: 'unhandled-promise',
    label: 'Unhandled Promise',
    category: 'Code Quality',
    desc: 'Promise chains missing .catch() error handlers.',
  },
  {
    id: 'sync-io',
    label: 'Sync I/O',
    category: 'Code Quality',
    desc: 'Synchronous fs operations that block the event loop.',
  },
  // Architecture
  {
    id: 'build-readiness',
    label: 'Build Readiness',
    category: 'Architecture',
    desc: 'Missing files, configs, scripts, deploy blockers.',
  },
  {
    id: 'governance',
    label: 'License & Governance',
    category: 'Architecture',
    desc: 'License headers, copyright notices, governance markers.',
  },
  {
    id: 'junk-files',
    label: 'Junk & Temp Files',
    category: 'Architecture',
    desc: 'OS/editor artifacts, backup files, caches.',
  },
  {
    id: 'removable-files',
    label: 'Removable Files',
    category: 'Architecture',
    desc: 'node_modules, build artifacts (dist, build, .next), caches, logs, and temp files that can be safely deleted.',
  },
  {
    id: 'database-patterns',
    label: 'Database Patterns',
    category: 'Architecture',
    desc: 'Raw SQL concatenation, missing limits, unindexed queries.',
  },
  {
    id: 'framework-practices',
    label: 'Framework Practices',
    category: 'Architecture',
    desc: 'React hook misuse, Vue Options API in Vue 3.',
  },
  {
    id: 'workspace-health',
    label: 'Workspace Health',
    category: 'Architecture',
    desc: 'Circular imports, mismatched dependency versions.',
  },
  {
    id: 'unused-deps',
    label: 'Unused Dependencies',
    category: 'Architecture',
    desc: 'Packages in package.json with no import references.',
  },
  {
    id: 'api-contract',
    label: 'API Contract',
    category: 'Architecture',
    desc: 'REST endpoints with no frontend call, GraphQL types without resolvers, stale OpenAPI specs.',
  },
  {
    id: 'production-leak',
    label: 'Production Leak',
    category: 'Architecture',
    desc: 'Mock/fixture/sample data paths in production code.',
  },
  {
    id: 'mock-path-leak',
    label: 'Mock Path Leak',
    category: 'Architecture',
    desc: 'Mock/fixture paths referenced in production code.',
  },
  {
    id: 'sample-json-ref',
    label: 'Sample JSON Ref',
    category: 'Architecture',
    desc: 'Sample JSON files referenced in production code.',
  },
  {
    id: 'architecture-drift',
    label: 'Architecture Drift',
    category: 'Architecture',
    desc: 'Hybrid/SSM model identifiers without schema validators.',
  },
  {
    id: 'roadmap-marker',
    label: 'Roadmap Marker',
    category: 'Architecture',
    desc: 'Unresolved HACK/XXX/WORKAROUND markers.',
  },
  {
    id: 'fix-preview',
    label: 'Fix Preview',
    category: 'Architecture',
    desc: 'Before/after code diffs with copyable patches.',
  },
  // UX & Accessibility
  {
    id: 'accessibility',
    label: 'Accessibility',
    category: 'UX & Accessibility',
    desc: 'Missing alt text, unlabeled inputs, color-only indicators.',
  },
  {
    id: 'i18n',
    label: 'i18n Readiness',
    category: 'UX & Accessibility',
    desc: 'Hardcoded UI strings, locale-ignorant formatting.',
  },
  {
    id: 'governance-marker',
    label: 'Governance Marker',
    category: 'UX & Accessibility',
    desc: 'License and copyright markers for open-source compliance.',
  },
];
export const OPTIONAL_COMPLETE_ENGINES = [
  {
    id: 'eu-ai-act',
    label: 'EU AI Act sprint',
    hint: 'Regulatory — not included in ZIP unless checked and completed',
  },
];
export const COMPLETE_ENGINE_ORDER = [
  ...COMPLETE_STEPS.map((step) => step.id),
  ...OPTIONAL_COMPLETE_ENGINES.map((step) => step.id),
];
export const CORE_ENGINE_IDS = new Set([
  'simplebeacon',
  'consolidation',
  'mock-scan',
  'roadmap',
  'codebase',
  'file-reduction',
  'data-quality',
  'cleanup-assistant',
  'npm-audit',
  'compliance',
  'eu-ai-act',
]);
export const BROWSER_ANALYZER_IDS = COMPLETE_STEPS.map((step) => step.id).filter(
  (id) => !CORE_ENGINE_IDS.has(id)
);
export const ENGINE_DEPENDENCIES = {
  'mock-scan': ['simplebeacon'],
  compliance: ['simplebeacon'],
};

/** Scan preset definitions for quick-selection buttons */
export const SCAN_PRESETS = [
  {
    id: 'essential',
    label: 'Essential',
    icon: '⚡',
    engines: [
      'simplebeacon',
      'consolidation',
      'mock-scan',
      'roadmap',
      'codebase',
      'file-reduction',
      'data-quality',
      'cleanup-assistant',
      'npm-audit',
      'compliance',
    ],
  },
  {
    id: 'security',
    label: 'Security',
    icon: '🔒',
    engines: [
      'simplebeacon',
      'consolidation',
      'mock-scan',
      'roadmap',
      'codebase',
      'file-reduction',
      'data-quality',
      'cleanup-assistant',
      'npm-audit',
      'compliance',
      'dependency-vulns',
      'sensitive-data',
      'security-headers',
      'config-drift',
      'eval-danger',
      'inner-html-xss',
      'prototype-pollution',
      'unvalidated-redirect',
      'missing-rate-limit',
      'insecure-random',
      'logging-secrets',
    ],
  },
  { id: 'full', label: 'Full', icon: '🔬', engines: [...COMPLETE_ENGINE_ORDER] },
  { id: 'custom', label: 'Custom', icon: '🔧', engines: [] },
];

/** Group engines by their category field */
export function groupEnginesByCategory(engineIds) {
  const groups = new Map();
  for (const id of engineIds) {
    // simplebeacon-ignore memory-leak
    const step = COMPLETE_STEPS.find((s) => s.id === id);
    const opt = OPTIONAL_COMPLETE_ENGINES.find((s) => s.id === id);
    const category =
      (step === null || step === void 0 ? void 0 : step.category) ||
      (opt === null || opt === void 0 ? void 0 : opt.category) ||
      'Other';
    if (!groups.has(category)) groups.set(category, []);
    groups
      .get(category)
      .push({
        id,
        label:
          (step === null || step === void 0 ? void 0 : step.label) ||
          (opt === null || opt === void 0 ? void 0 : opt.label) ||
          id,
        desc:
          (step === null || step === void 0 ? void 0 : step.desc) ||
          (opt === null || opt === void 0 ? void 0 : opt.hint) ||
          '',
        optional: !!opt,
      });
  }
  return groups;
}

/** Engines that fetch their own prerequisites — no separate queue rows on Complete. */
export const SELF_CONTAINED_ENGINES = new Set(['cleanup-assistant', 'mock-scan', 'compliance']);

/**
 * Is self contained only selection.
 * @param {Array} selectedEngines
 * @returns {any}
 */
export function isSelfContainedOnlySelection(selectedEngines) {
  const selected = normalizeSelectedEngines(selectedEngines, { allowEmpty: true });
  return selected.length === 1 && SELF_CONTAINED_ENGINES.has(selected[0]);
}

/**
 * Default selected engines.
 * @returns {any}
 */
export function defaultSelectedEngines() {
  return COMPLETE_STEPS.map((step) => step.id);
}

/** Client deliverable SKUs — scans preset per row; price is list/reference (checkout is separate). */
export const CLIENT_DELIVERABLE_PLANS = [
  {
    sku: 'moneyPrinter19',
    label: 'Money Printer Tier',
    price: '$19',
    category: 'Instant audit',
    tagline: 'Website Security Report — instant audit · zero-retention · delivered in 60 seconds',
    engines: ['simplebeacon'],
    analysisType: 'simplebeacon',
    scans: ['SEO', 'SSL', 'Mobile responsiveness', 'Speed', 'Accessibility', 'Headers'],
  },
  {
    sku: 'community',
    label: 'Community',
    price: '$0',
    category: 'Community',
    tagline: 'Simplebeacon gate only — free CLI + MCP on your machine',
    engines: ['simplebeacon'],
    analysisType: 'simplebeacon',
    scans: ['Simplebeacon gate only'],
  },
  {
    sku: 'clearance499',
    label: 'Executive clearance PDF',
    price: '$499',
    category: 'Client deliverable',
    tagline: 'Gate, fiction digest, compliance checklist, executive PDF — 48-hour operator review',
    engines: ['simplebeacon', 'mock-scan', 'compliance'],
    analysisType: 'complete',
    scans: ['Gate', 'Fiction digest', 'Compliance', 'Executive PDF'],
  },
  {
    sku: 'agency999',
    label: 'Agency Project Pack',
    price: '$999',
    category: 'Client deliverable',
    tagline: 'Full complete scan plus co-branded milestone certificates',
    engines: defaultSelectedEngines(),
    analysisType: 'complete',
    scans: ['Complete scan (10 engines)', 'Certificates'],
  },
  {
    sku: 'agency1499',
    label: 'Agency Growth Pack',
    price: '$1,499',
    category: 'Client deliverable',
    tagline: 'Project pack plus priority review and included warranty re-scan',
    engines: defaultSelectedEngines(),
    analysisType: 'complete',
    scans: ['Complete scan', 'Certificates', 'Warranty re-scan'],
  },
  {
    sku: 'euai2499',
    label: 'EU AI Act Readiness Sprint',
    price: '$2,499',
    category: 'EU regulatory',
    tagline: 'Technical readiness audit — not legal conformity certification',
    engines: ['simplebeacon', 'compliance', 'eu-ai-act'],
    analysisType: 'complete',
    scans: ['EU profile gate', 'EU patterns', 'Compliance', 'EU audit PDF'],
  },
  {
    sku: 'warranty199',
    label: 'Post-handoff re-scan',
    price: '$199',
    category: 'Retention',
    tagline: 'Formal 30-day re-attestation after release',
    engines: ['simplebeacon', 'compliance'],
    analysisType: 'complete',
    scans: ['Gate re-run', 'Compliance', 'Executive PDF'],
  },
  {
    sku: 'custom',
    label: 'Custom mix',
    price: 'Operator',
    category: 'Desk only',
    tagline: 'Check scans in the queue below (or on pills) — no fixed list price',
    engines: null,
    analysisType: 'complete',
    allowManual: true,
    scans: ['Manual engine toggles — no fixed list price'],
  },
];
export const PRICING_DELIVERABLES_URL = 'https://simplebeacon.ai/pricing#client-deliverables';

/**
 * Get client deliverable plan.
 * @param {any} sku
 * @returns {any}
 */
export function getClientDeliverablePlan(sku) {
  return CLIENT_DELIVERABLE_PLANS.find((plan) => plan.sku === sku) || null;
}

/**
 * Get deliverable plan engines.
 * @param {any} plan
 * @returns {any}
 */
export function getDeliverablePlanEngines(plan) {
  if (!plan || plan.allowManual) return null;
  return Array.isArray(plan.engines) ? plan.engines : null;
}

/**
 * Infer deliverable sku.
 * @param {Array} selectedEngines
 * @returns {any}
 */
export function inferDeliverableSku(selectedEngines) {
  const selected = new Set(normalizeSelectedEngines(selectedEngines, { allowEmpty: true }));
  for (const plan of CLIENT_DELIVERABLE_PLANS) {
    const expected = getDeliverablePlanEngines(plan);
    if (!expected) continue;
    const want = new Set(expected);
    if (want.size === selected.size && [...want].every((id) => selected.has(id))) {
      return plan.sku;
    }
  }
  return 'custom';
}

/**
 * Normalize selected engines.
 * @param {any} raw
 * @param {Object} options
 * @returns {any}
 */
export function normalizeSelectedEngines(raw, { allowEmpty = false } = {}) {
  const allowed = new Set(COMPLETE_ENGINE_ORDER);
  const selected = Array.isArray(raw)
    ? raw.filter((id) => allowed.has(id))
    : defaultSelectedEngines();
  if (!selected.length && allowEmpty) return [];
  return selected.length ? selected : defaultSelectedEngines();
}

/**
 * Resolve engines for run.
 * @param {Array} selectedEngines
 * @returns {any}
 */
export function resolveEnginesForRun(selectedEngines) {
  const selected = new Set(normalizeSelectedEngines(selectedEngines));
  for (const [engineId, deps] of Object.entries(ENGINE_DEPENDENCIES)) {
    if (!selected.has(engineId)) continue;
    for (const dep of deps) selected.add(dep);
  }
  return COMPLETE_ENGINE_ORDER.filter((id) => selected.has(id));
}

/** Keep queue checkboxes aligned for explicit co-selection (Complete scan deps use resolveEnginesForRun). */
export function applyEngineSelectionChange(selectedSet, engineId, checked) {
  if (!engineId || !selectedSet) return;
  if (checked) {
    selectedSet.add(engineId);
    // Auto-select dependencies so the UI reflects what will actually run
    const deps = ENGINE_DEPENDENCIES[engineId];
    if (deps) {
      for (const dep of deps) selectedSet.add(dep);
    }
    return;
  }
  selectedSet.delete(engineId);
  // When codebase is unchecked, also uncheck every engine that depends on it
  if (engineId === 'codebase') {
    for (const [id, deps] of Object.entries(ENGINE_DEPENDENCIES)) {
      if (deps.includes('codebase')) selectedSet.delete(id);
    }
  }
}

/** Standalone pill → only that engine in the queue (internal deps are not shown). */
export function ensureStandaloneEngineSelection(modeValue) {
  const engineId = modeToEngineId(modeValue);
  return engineId ? [engineId] : [];
}

/** Always show the full engine list; selection state is separate from visibility. */
export function queueEnginesForDisplay() {
  return COMPLETE_ENGINE_ORDER;
}

/**
 * Queue select all state.
 * @param {Array} selectedEngines
 * @returns {any}
 */
export function queueSelectAllState(selectedEngines) {
  const queueEngineIds = queueEnginesForDisplay();
  const selected = new Set(selectedEngines || []);
  const allSelected = queueEngineIds.every((id) => selected.has(id));
  const someSelected = queueEngineIds.some((id) => selected.has(id));
  return { queueEngineIds, allSelected, someSelected };
}

/**
 * Get complete engine label.
 * @param {string} engineId
 * @returns {any}
 */
export function getCompleteEngineLabel(engineId) {
  var _a, _b;
  return (
    ((_a = COMPLETE_STEPS.find((step) => step.id === engineId)) === null || _a === void 0
      ? void 0
      : _a.label) ||
    ((_b = OPTIONAL_COMPLETE_ENGINES.find((step) => step.id === engineId)) === null || _b === void 0
      ? void 0
      : _b.label) ||
    engineId
  );
}

/**
 * Mode to engine id.
 * @param {any} modeValue
 * @returns {any}
 */
export function modeToEngineId(modeValue) {
  const normalizedMode = String(modeValue || '');
  if (!normalizedMode || normalizedMode === 'complete' || normalizedMode === 'auto') return null;
  return COMPLETE_ENGINE_ORDER.includes(normalizedMode) ? normalizedMode : null;
}

export const SIMPLEBEACON_GATE_RULES = [
  { id: 'credentials', label: 'Credential & secret patterns in scan paths + production dirs' },
  { id: 'production-leak', label: 'Mock/sample JSON paths referenced from production code' },
  { id: 'json-schema', label: 'Registered page samples match schema specs' },
  { id: 'sample-consistency', label: 'Anchor sample consistency / fiction KPI drift' },
  { id: 'fiction-kpi-patterns', label: 'Fiction KPI placeholders across repository JSON' },
  {
    id: 'llm-slop-patterns',
    label: 'LLM slop — unresolved placeholders, code fences, filler metrics',
  },
  {
    id: 'agency-handoff-patterns',
    label: 'Agency handoff — localhost deploy leaks, auth misconfig, webhooks',
  }, // simplebeacon-ignore hardcoded-url — rule label text, not a URL
  {
    id: 'file-naming-patterns',
    label: 'File naming — AI-generated or low-quality file names that degrade code readability',
  },
  { id: 'roadmap', label: 'Roadmap completeness signal (standard profile)' },
];
export const EU_AI_ACT_EXTRA_RULES = [
  {
    id: 'eu-ai-act-patterns',
    label: 'EU AI Act transparency, logging, and human-oversight markers',
  },
];
export const DATA_QUALITY_SCANNERS = [
  'config-management',
  'dependency-health',
  'environment-variables',
  'data-freshness',
  'data-access-patterns',
  'data-privacy',
  'data-lineage',
  'data-consistency',
];
export const FILE_REDUCTION_SCANNERS = [
  'build-artifacts',
  'asset-consolidation',
  'unused-files',
  'directory-bloat',
];
export const COMPLIANCE_CHECKLIST_RULES = [
  'GATE-001 — Merge gate passes on configured severities',
  'CRED-001 — No credential patterns in scanned paths',
  'LEAK-001 — No mock/sample JSON paths in production dirs',
  'DATA-001 — Page samples match schema specs',
  'DATA-002 — No fiction KPI drift in anchor samples',
  'SUPPLY-001 — No critical/high npm audit vulnerabilities',
  'SUPPLY-002 — Moderate npm vulnerabilities within policy',
  'AUTH-001 — Production profile has JWT auth enabled (REQUIRE_AUTH)',
];
