// simplebeacon-ignore: todoMarkers,euAiAct — EU AI Act disclosure comment, not a real TODO
// @simplebeacon-remediation: EU AI Act Compliance Banner
// TODO: Provide User Notice - Content generated by AI system under EU AI Act Art 52.
import { useState, useRef, useEffect, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Bot,
  Send,
  Trash2,
  Settings2,
  Settings,
  FileText,
  Copy,
  Check,
  AlertCircle,
  Loader2,
  Sparkles,
  RefreshCw,
  Download,
  Volume2,
  VolumeX,
  Square,
} from "lucide-react";
import { toast } from "sonner";
import { getApiBase, apiUrl, authHeaders } from "@/config";
import {
  checkLocalNetworkAccess,
  isLoopbackHost,
} from "@/utils/checkLocalNetwork";

const BROWSER_OLLAMA_URL = "http://127.0.0.1:11434";

type OllamaProbeResult =
  | { status: "online"; models: string[] }
  | { status: "cors_blocked" }
  | { status: "not_running" }
  | { status: "network_denied" }
  | { status: "unknown_error"; error: string };

/**
 * Probe Ollama directly from the browser. On the hosted dashboard, the server
 * cannot reach the user's local Ollama, so we check from the browser instead.
 * Returns detailed status info for the setup wizard.
 */
async function probeBrowserOllamaDetailed(
  baseUrl: string,
  timeoutMs = 2500,
): Promise<OllamaProbeResult> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), timeoutMs);
    const res = await fetch(`${baseUrl.replace(/\/+$/, "")}/api/tags`, {
      signal: controller.signal,
      headers: { "Content-Type": "application/json" },
    });
    clearTimeout(timer);
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data.models)) {
        const models = data.models
          .map((m: any) => m.name)
          .filter((n: string) => typeof n === "string" && n.trim());
        return { status: "online", models };
      }
      return { status: "online", models: [] };
    }
    if (res.status === 403) return { status: "cors_blocked" };
    return { status: "unknown_error", error: `HTTP ${res.status}` };
  } catch (err: any) {
    if (err?.name === "AbortError") return { status: "not_running" };
    // TypeError: Failed to fetch — could be CORS preflight failure or network denied
    if (err instanceof TypeError && err.message.includes("Failed to fetch")) {
      // Distinguish CORS from not-running: CORS preflight failures also throw TypeError
      // but the connection was reachable. We can't reliably distinguish, so check
      // if it's a secure context → localhost issue (Private Network Access).
      if (
        typeof window !== "undefined" &&
        window.location.protocol === "https:" &&
        window.isSecureContext
      ) {
        return { status: "network_denied" };
      }
      return { status: "not_running" };
    }
    return { status: "unknown_error", error: err?.message || String(err) };
  }
}

/**
 * Backwards-compatible probe that returns just the model list (or null).
 */
async function probeBrowserOllama(
  baseUrl: string,
  timeoutMs = 2500,
): Promise<string[] | null> {
  const result = await probeBrowserOllamaDetailed(baseUrl, timeoutMs);
  return result.status === "online" ? result.models : null;
}

/**
 * Send a chat message directly to Ollama from the browser.
 * Used when the server can't reach Ollama (hosted dashboard with local Ollama).
 */
async function chatWithBrowserOllama(
  baseUrl: string,
  model: string,
  message: string,
  history: Message[],
  systemPrompt: string,
): Promise<string> {
  const url = `${baseUrl.replace(/\/+$/, "")}/api/chat`;
  // Models with built-in system prompts (via Modelfile) should NOT have their
  // system prompt overridden by the chatbot's personality prompt — it causes
  // conflicting instructions and incoherent output on small models.
  const modelsWithBuiltInPrompt = [
    "unbreakable-oracle",
    "unbreakable-oracle-final",
    "unbreakable-oracle-single",
  ];
  const skipSystemPrompt = modelsWithBuiltInPrompt.some((m) =>
    model.startsWith(m),
  );
  const messages = skipSystemPrompt
    ? [
        ...history.map((m) => ({ role: m.role, content: m.content })),
        { role: "user", content: message },
      ]
    : [
        { role: "system", content: systemPrompt },
        ...history.map((m) => ({ role: m.role, content: m.content })),
        { role: "user", content: message },
      ];

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ model, messages, stream: false }),
  });
  if (!res.ok) {
    const errText = await res.text().catch(() => "");
    throw new Error(`Ollama HTTP ${res.status}: ${errText.slice(0, 200)}`);
  }
  const data = await res.json();
  return data.message?.content || data.response || "";
}

type Message = { role: "user" | "assistant"; content: string };
type Provider = {
  id: string;
  label: string;
  available: boolean;
  model?: string;
  models?: string[];
  description?: string;
};
type Personality =
  | "helpful"
  | "professional"
  | "casual"
  | "sarcastic"
  | "technical"
  | "creative"
  | "oracle";

const MODEL_PREFS_STORAGE_KEY = "simplebeacon_ai_model_preferences";
const PROVIDER_REFRESH_MIN_INTERVAL_MS = 15000;

/**
 * Check if a model name (without tag) matches any installed model.
 * Ollama returns names like 'llama3.2:latest' but users/registry use 'llama3.2'.
 */
function modelIsInstalled(
  modelName: string,
  installedModels: string[],
): boolean {
  if (installedModels.includes(modelName)) return true;
  // Check with :latest tag appended
  if (installedModels.includes(modelName + ":latest")) return true;
  // Check if any installed model starts with the name (e.g. 'llama3.2:3b' matches 'llama3.2')
  return installedModels.some(
    (m) => m === modelName || m.startsWith(modelName + ":"),
  );
}
const OLLAMA_REGISTRY_MODELS: string[] = [
  "llama3.2",
  "llama3.1",
  "llama3",
  "llama2",
  "mistral",
  "mistral-nemo",
  "mixtral",
  "codellama",
  "codegemma",
  "qwen2.5-coder",
  "deepseek-coder-v2",
  "phi3",
  "phi3.5",
  "gemma2",
  "gemma",
  "qwen2.5",
  "qwen2",
  "yi",
  "llava",
  "llava-llama3",
  "dolphin-llama3",
  "dolphin-mistral",
  "wizardlm2",
  "orca2",
  "command-r",
  "command-r-plus",
  "starcoder2",
  "stable-code",
  "mathstral",
  "granite-code",
  "smollm2",
  "llama3.2-vision",
];
const PROVIDER_MODEL_OPTIONS: Record<string, string[]> = {
  ollama: OLLAMA_REGISTRY_MODELS,
  openai: ["gpt-4.1", "gpt-4.1-mini", "gpt-4o", "gpt-4o-mini", "o3-mini"],
  anthropic: [
    "claude-3-7-sonnet-latest",
    "claude-3-5-sonnet-latest",
    "claude-3-5-haiku-latest",
  ],
};

function readModelPrefs(): Record<string, string> {
  if (typeof window === "undefined") return {};
  try {
    const raw = localStorage.getItem(MODEL_PREFS_STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : {};
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}

function writeModelPrefs(next: Record<string, string>) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(MODEL_PREFS_STORAGE_KEY, JSON.stringify(next));
  } catch {
    // best-effort only
  }
}

const PERSONALITY_LABELS: Record<Personality, string> = {
  helpful: "Helpful (default)",
  professional: "Professional",
  casual: "Casual / Friendly",
  sarcastic: "Sarcastic / Witty",
  technical: "Deep Technical",
  creative: "Creative / Exploratory",
  oracle: "🔮 The Unbreakable Oracle",
};

const PERSONALITY_PROMPTS: Record<Personality, string> = {
  helpful:
    "You are a helpful assistant for SimpleBeacon, a code audit and security scanning tool. SimpleBeacon scans codebases for secrets, credentials, AI-generated code slop, mock/sample paths, fake KPIs, EU AI Act compliance, SOC 2 evidence, and deployment readiness. It provides a CLI, MCP server, VS Code extension, and web dashboard. You can answer questions about code, software development, security, architecture, and general programming topics. You are friendly and provide clear, accurate answers. Always answer the user's question directly. Never invent or hallucinate features that SimpleBeacon does not have. If you are unsure whether SimpleBeacon supports something, say so.",
  professional:
    "You are a professional, concise assistant for SimpleBeacon, a code audit and security scanning tool. SimpleBeacon scans codebases for secrets, credentials, AI-generated code slop, mock/sample paths, fake KPIs, EU AI Act compliance, SOC 2 evidence, and deployment readiness. It provides a CLI, MCP server, VS Code extension, and web dashboard. Use formal language and structured responses. Always answer the user's question directly. Never invent or hallucinate features that SimpleBeacon does not have. If you are unsure whether SimpleBeacon supports something, say so.",
  casual:
    "You are a friendly, relaxed assistant for SimpleBeacon, a code audit and security scanning tool. SimpleBeacon scans codebases for secrets, credentials, AI-generated code slop, mock/sample paths, fake KPIs, EU AI Act compliance, SOC 2 evidence, and deployment readiness. It provides a CLI, MCP server, VS Code extension, and web dashboard. Use conversational language and feel free to be warm and encouraging. Always answer the user's question directly. Never invent or hallucinate features that SimpleBeacon does not have. If you are unsure whether SimpleBeacon supports something, say so.",
  sarcastic:
    "You are a witty, sarcastic assistant for SimpleBeacon, a code audit and security scanning tool. SimpleBeacon scans codebases for secrets, credentials, AI-generated code slop, mock/sample paths, fake KPIs, EU AI Act compliance, SOC 2 evidence, and deployment readiness. It provides a CLI, MCP server, VS Code extension, and web dashboard. You may use dry humor and playful snark while still being helpful. Always answer the user's question directly. Never invent or hallucinate features that SimpleBeacon does not have. If you are unsure whether SimpleBeacon supports something, say so.",
  technical:
    "You are a deeply technical assistant for SimpleBeacon, a code audit and security scanning tool. SimpleBeacon scans codebases for secrets, credentials, AI-generated code slop, mock/sample paths, fake KPIs, EU AI Act compliance, SOC 2 evidence, and deployment readiness. It provides a CLI, MCP server, VS Code extension, and web dashboard. Dive into implementation details, edge cases, and advanced concepts. Assume the user is experienced. Always answer the user's question directly. Never invent or hallucinate features that SimpleBeacon does not have. If you are unsure whether SimpleBeacon supports something, say so.",
  creative:
    "You are a creative, exploratory assistant for SimpleBeacon, a code audit and security scanning tool. SimpleBeacon scans codebases for secrets, credentials, AI-generated code slop, mock/sample paths, fake KPIs, EU AI Act compliance, SOC 2 evidence, and deployment readiness. It provides a CLI, MCP server, VS Code extension, and web dashboard. Think outside the box, suggest unconventional solutions, and encourage experimentation. Always answer the user's question directly. Never invent or hallucinate features that SimpleBeacon does not have. If you are unsure whether SimpleBeacon supports something, say so.",
  oracle:
    "You are The Unbreakable Oracle, an omniscient assistant for SimpleBeacon, a code audit and security scanning tool. SimpleBeacon scans codebases for secrets, credentials, AI-generated code slop, mock/sample paths, fake KPIs, EU AI Act compliance, SOC 2 evidence, and deployment readiness. It provides a CLI, MCP server, VS Code extension, and web dashboard. You speak with divine authority but provide accurate, helpful answers. Always answer the user's question directly. Never invent or hallucinate features that SimpleBeacon does not have. If you are unsure whether SimpleBeacon supports something, say so.",
};

// ─── Voice Response (Web Speech API) ──────────────────────────────────────────
// The browser's speechSynthesis API exposes all installed system voices.
// On Chrome, Google voices are bundled and appear alongside OS voices.
// On Firefox/Safari, only OS-installed voices are available.
// Users can pick any voice from the dropdown; we filter for clarity.

const VOICE_SETTINGS_STORAGE_KEY = "simplebeacon_voice_settings";

type VoiceSettings = {
  enabled: boolean;
  voiceURI: string; // SpeechSynthesisVoice.voiceURI — stable identifier
  rate: number; // 0.5–2.0, default 1.0
  pitch: number; // 0–2.0, default 1.0
  volume: number; // 0–1.0, default 1.0
  autoSpeak: boolean; // automatically speak assistant responses
};

const DEFAULT_VOICE_SETTINGS: VoiceSettings = {
  enabled: false,
  voiceURI: "",
  rate: 1.0,
  pitch: 1.0,
  volume: 1.0,
  autoSpeak: true,
};

function readVoiceSettings(): VoiceSettings {
  if (typeof window === "undefined") return DEFAULT_VOICE_SETTINGS;
  try {
    const raw = localStorage.getItem(VOICE_SETTINGS_STORAGE_KEY);
    const parsed = raw ? JSON.parse(raw) : {};
    return { ...DEFAULT_VOICE_SETTINGS, ...parsed };
  } catch {
    return DEFAULT_VOICE_SETTINGS;
  }
}

function writeVoiceSettings(settings: VoiceSettings) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(VOICE_SETTINGS_STORAGE_KEY, JSON.stringify(settings));
  } catch {
    // best-effort
  }
}

/**
 * Strip markdown/code blocks from text so the TTS engine doesn't read
 * raw syntax noise aloud. Keeps prose readable.
 */
function stripMarkdownForSpeech(text: string): string {
  return (
    text
      // Remove code blocks entirely
      .replace(/```[\s\S]*?```/g, " [code block] ")
      // Remove inline code
      .replace(/`([^`]+)`/g, "$1")
      // Remove markdown headers
      .replace(/^#{1,6}\s+/gm, "")
      // Remove bold/italic markers
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/\*([^*]+)\*/g, "$1")
      .replace(/__([^_]+)__/g, "$1")
      // Remove links, keep text
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      // Remove list markers
      .replace(/^[\s]*[-*+]\s+/gm, "")
      .replace(/^\d+\.\s+/gm, "")
      // Remove blockquotes
      .replace(/^>\s+/gm, "")
      // Remove horizontal rules
      .replace(/^---+$/gm, "")
      // Remove the AI-Generated prefix tag
      .replace(/^\[AI-Generated[^\]]*\]\s*/i, "")
      // Collapse whitespace
      .replace(/\n{3,}/g, "\n\n")
      .trim()
  );
}

/**
 * Load available speech synthesis voices. Chrome loads them asynchronously,
 * so we use the onvoiceschanged callback. Returns a cleanup function.
 */
function loadVoices(): SpeechSynthesisVoice[] {
  if (typeof window === "undefined" || !window.speechSynthesis) return [];
  return window.speechSynthesis.getVoices();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function formatMessage(content: string): string {
  const codeBlocks: string[] = [];
  let processed = content.replace(/```([\s\S]*?)```/g, (_, code) => {
    const i = codeBlocks.length;
    codeBlocks.push(escapeHtml(code));
    return `__CODEBLOCK_${i}__`;
  });
  const inlineCodes: string[] = [];
  processed = processed.replace(/`([^`]+)`/g, (_, code) => {
    const i = inlineCodes.length;
    inlineCodes.push(escapeHtml(code));
    return `__INLINECODE_${i}__`;
  });
  processed = escapeHtml(processed);
  processed = processed.replace(
    /__CODEBLOCK_(\d+)__/g,
    (_, i) =>
      `<pre class="chatbot-code-block"><code>${codeBlocks[Number(i)]}</code></pre>`,
  );
  processed = processed.replace(
    /__INLINECODE_(\d+)__/g,
    (_, i) =>
      `<code class="chatbot-inline-code">${inlineCodes[Number(i)]}</code>`,
  );
  processed = processed.replace(
    /<pre class="chatbot-code-block">[\s\S]*?<\/pre>/g,
    (m) => m.replace(/\n/g, "&#10;"),
  );
  processed = processed.replace(/\n/g, "<br>");
  processed = processed.replace(/&#10;/g, "\n");
  return processed;
}

/**
 * Ollama Setup Wizard — guides users through installing and configuring Ollama
 * to work with the hosted dashboard. Handles CORS, Private Network Access,
 * and model installation.
 */
function OllamaSetupWizard({
  probeResult,
  onRetry,
  onClose,
}: {
  probeResult: OllamaProbeResult | null;
  onRetry: () => void;
  onClose: () => void;
}) {
  const isMac =
    typeof navigator !== "undefined" && /Mac/i.test(navigator.platform);
  const isWindows =
    typeof navigator !== "undefined" && /Win/i.test(navigator.platform);
  const shellName = isMac ? "Terminal" : "Command Prompt / PowerShell";
  const corsCmd = isWindows
    ? '$env:OLLAMA_ORIGINS="https://simplebeacon.ai"; ollama serve'
    : "OLLAMA_ORIGINS=https://simplebeacon.ai ollama serve";

  const status = probeResult?.status;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      onClick={onClose}
    >
      <div
        className="max-w-2xl w-full mx-4 max-h-[85vh] overflow-y-auto rounded-xl border border-border bg-card shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <h2 className="text-lg font-bold">Ollama Setup Wizard</h2>
          <Button variant="ghost" size="sm" onClick={onClose}>
            ×
          </Button>
        </div>

        <div className="px-6 py-4 space-y-4 text-sm">
          {/* Step 1: Install Ollama */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-600 text-white text-xs font-bold">
                1
              </span>
              <span className="font-medium">Install Ollama</span>
              {status !== "not_running" && status !== "unknown_error" && (
                <span className="text-green-600 text-xs">✓ Detected</span>
              )}
            </div>
            <div className="pl-8 text-foreground-muted">
              {status === "not_running" || status === "unknown_error" ? (
                <>
                  <p>
                    Download and install from{" "}
                    <a
                      href="https://ollama.com/download"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 underline"
                    >
                      ollama.com/download
                    </a>
                  </p>
                  <p className="text-xs mt-1">
                    After installing, Ollama should start automatically. If not,
                    open {shellName} and run:
                  </p>
                  <pre className="mt-1 rounded bg-muted px-3 py-2 text-xs overflow-x-auto">
                    ollama serve
                  </pre>
                </>
              ) : (
                <p className="text-xs">Ollama is installed and running.</p>
              )}
            </div>
          </div>

          {/* Step 2: Configure CORS */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-600 text-white text-xs font-bold">
                2
              </span>
              <span className="font-medium">Allow this website to connect</span>
              {status === "online" && (
                <span className="text-green-600 text-xs">✓ Connected</span>
              )}
              {status === "cors_blocked" && (
                <span className="text-red-600 text-xs">✗ Blocked</span>
              )}
            </div>
            <div className="pl-8 text-foreground-muted">
              {status === "cors_blocked" ? (
                <>
                  <p>
                    Ollama blocks requests from websites by default. You need to
                    set the{" "}
                    <code className="bg-muted px-1 rounded">
                      OLLAMA_ORIGINS
                    </code>{" "}
                    environment variable.
                  </p>
                  <p className="text-xs mt-1">
                    Open {shellName} and run (stop any running Ollama first with{" "}
                    <code className="bg-muted px-1 rounded">Ctrl+C</code>):
                  </p>
                  <pre className="mt-1 rounded bg-muted px-3 py-2 text-xs overflow-x-auto select-all">
                    {corsCmd}
                  </pre>
                  <p className="text-xs mt-2">
                    This allows only simplebeacon.ai to connect. To allow all
                    websites, use{" "}
                    <code className="bg-muted px-1 rounded">
                      OLLAMA_ORIGINS=*
                    </code>{" "}
                    instead.
                  </p>
                </>
              ) : status === "network_denied" ? (
                <>
                  <p>
                    Your browser is blocking access to localhost from this
                    website.
                  </p>
                  <p className="text-xs mt-1">
                    Click the lock icon next to the URL → Site Settings → allow
                    "Local Network Access". Then refresh this page.
                  </p>
                  <Button
                    size="sm"
                    variant="outline"
                    className="mt-2"
                    onClick={() => {
                      window.open(
                        "https://support.google.com/chrome/answer/14227606",
                        "_blank",
                        "noopener",
                      );
                    }}
                  >
                    How to allow in Chrome
                  </Button>
                </>
              ) : status === "online" ? (
                <p className="text-xs">CORS is configured correctly.</p>
              ) : (
                <p className="text-xs">
                  Complete step 1 first, then configure CORS.
                </p>
              )}
            </div>
          </div>

          {/* Step 3: Install models */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-600 text-white text-xs font-bold">
                3
              </span>
              <span className="font-medium">Install AI models</span>
              {status === "online" &&
              probeResult?.models.length &&
              probeResult.models.length > 0 ? (
                <span className="text-green-600 text-xs">
                  ✓ {probeResult.models.length} model(s) found
                </span>
              ) : status === "online" ? (
                <span className="text-yellow-600 text-xs">
                  ⚠ No models installed
                </span>
              ) : null}
            </div>
            <div className="pl-8 text-foreground-muted">
              <p className="text-xs">Install models in {shellName}:</p>
              <pre className="mt-1 rounded bg-muted px-3 py-2 text-xs overflow-x-auto">
                ollama pull llama3.2
              </pre>
              <p className="text-xs mt-2">Popular models:</p>
              <div className="mt-1 flex flex-wrap gap-1.5">
                {[
                  "llama3.2",
                  "mistral",
                  "phi3",
                  "codellama",
                  "gemma2",
                  "qwen2.5",
                ].map((m) => (
                  <code
                    key={m}
                    className="rounded bg-muted px-2 py-0.5 text-xs select-all"
                  >
                    ollama pull {m}
                  </code>
                ))}
              </div>
              {status === "online" &&
                probeResult?.models.length &&
                probeResult.models.length > 0 && (
                  <>
                    <p className="text-xs mt-2 font-medium">
                      Your installed models:
                    </p>
                    <ul className="mt-1 text-xs list-disc list-inside">
                      {probeResult.models.map((m) => (
                        <li key={m}>{m}</li>
                      ))}
                    </ul>
                  </>
                )}
            </div>
          </div>

          {/* Step 4: Verify */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-blue-600 text-white text-xs font-bold">
                4
              </span>
              <span className="font-medium">Verify connection</span>
            </div>
            <div className="pl-8">
              <p className="text-xs text-foreground-muted mb-2">
                After completing the steps above, click retry to test the
                connection.
              </p>
              <Button size="sm" onClick={onRetry}>
                <RefreshCw className="h-3.5 w-3.5 mr-1" /> Retry connection
              </Button>
            </div>
          </div>

          {/* Current status summary */}
          {probeResult && (
            <div className="rounded-lg border border-border bg-muted/30 px-4 py-3 text-xs">
              <div className="font-medium mb-1">
                Current status:{" "}
                {status === "online"
                  ? "🟢 Connected"
                  : status === "cors_blocked"
                    ? "🔴 CORS blocked"
                    : status === "network_denied"
                      ? "🟡 Network permission needed"
                      : status === "not_running"
                        ? "🔴 Ollama not running"
                        : "🔴 Unknown error"}
              </div>
              {status === "unknown_error" && (
                <div className="text-foreground-muted">
                  Error: {probeResult.error}
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export function ChatbotView() {
  const [messages, setMessages] = useState<Message[]>(() => {
    try {
      const stored = localStorage.getItem("simplebeacon_chatbot_history");
      return stored ? JSON.parse(stored) : [];
    } catch {
      return [];
    }
  });
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [providers, setProviders] = useState<Provider[]>([]);
  const [providerModels, setProviderModels] = useState<
    Record<string, string[]>
  >({});
  const [selectedProvider, setSelectedProvider] = useState("");
  const [modelPrefs, setModelPrefs] = useState<Record<string, string>>(() =>
    readModelPrefs(),
  );
  const [selectedModel, setSelectedModel] = useState("");
  const [connectionStatus, setConnectionStatus] = useState<
    "checking" | "online" | "offline"
  >("checking");
  const [connectionText, setConnectionText] = useState("Checking…");
  const [localNetworkDenied, setLocalNetworkDenied] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [showPrompt, setShowPrompt] = useState(false);
  const [showSetupWizard, setShowSetupWizard] = useState(false);
  const [showOracleInstall, setShowOracleInstall] = useState(false);
  const [ollamaProbeResult, setOllamaProbeResult] =
    useState<OllamaProbeResult | null>(null);
  const [showOracleBanner, setShowOracleBanner] = useState(() => {
    try {
      return (
        localStorage.getItem("simplebeacon_oracle_banner_dismissed") !== "true"
      );
    } catch {
      return true;
    }
  });
  const [personality, setPersonality] = useState<Personality>(() => {
    try {
      const s = JSON.parse(
        localStorage.getItem("simplebeacon_chatbot_settings") || "{}",
      );
      return s.personality || "helpful";
    } catch {
      return "helpful";
    }
  });
  const [removeFilters, setRemoveFilters] = useState(() => {
    try {
      const s = JSON.parse(
        localStorage.getItem("simplebeacon_chatbot_settings") || "{}",
      );
      return s.removeFilters || false;
    } catch {
      return false;
    }
  });
  const [customPrompt, setCustomPrompt] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  // Voice response state
  const [voiceSettings, setVoiceSettings] = useState<VoiceSettings>(() =>
    readVoiceSettings(),
  );
  const [availableVoices, setAvailableVoices] = useState<
    SpeechSynthesisVoice[]
  >([]);
  const [speakingIndex, setSpeakingIndex] = useState<number | null>(null);
  const [showVoiceSettings, setShowVoiceSettings] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const messagesContainerRef = useRef<HTMLDivElement>(null);
  const providersFetchedAtRef = useRef(0);
  const providerFetchInFlightRef = useRef<Promise<void> | null>(null);

  const [apiBase, setApiBase] = useState(getApiBase());

  // simplebeacon-ignore: framework-practices
  useEffect(() => {
    if (apiBase) return;
    let cancelled = false;
    const check = () => {
      if (cancelled) return;
      const detected = getApiBase();
      if (detected) {
        setApiBase(detected);
      } else {
        setTimeout(check, 500);
      }
    };
    setTimeout(check, 500);
    return () => {
      cancelled = true;
    };
  }, [apiBase]);

  const scrollToBottom = useCallback(() => {
    if (messagesContainerRef.current) {
      messagesContainerRef.current.scrollTo({
        top: messagesContainerRef.current.scrollHeight,
        behavior: "smooth",
      });
    }
  }, []);

  // simplebeacon-ignore: framework-practices
  useEffect(() => {
    scrollToBottom();
  }, [messages, scrollToBottom]);

  // simplebeacon-ignore: framework-practices
  useEffect(() => {
    localStorage.setItem(
      "simplebeacon_chatbot_history",
      JSON.stringify(messages),
    );
  }, [messages]);

  const saveSettings = useCallback((p: Personality, rf: boolean) => {
    localStorage.setItem(
      "simplebeacon_chatbot_settings",
      JSON.stringify({
        personality: p,
        removeFilters: rf,
      }),
    );
  }, []);

  const loadCustomPrompt = useCallback(async () => {
    if (!apiBase) return;
    const userId = localStorage.getItem("simplebeacon_user_id") || "anonymous";
    try {
      const res = await fetch(
        apiUrl(`/prompts/get?userId=${encodeURIComponent(userId)}`),
        {
          headers: authHeaders(),
        },
      );
      if (res.ok) {
        const data = await res.json();
        if (data.prompt) setCustomPrompt(data.prompt);
        return;
      }
    } catch {
      // ignore
    }
    const local = localStorage.getItem("chatbot_custom_prompt");
    if (local) setCustomPrompt(local);
  }, [apiBase]);

  const refreshProviders = useCallback(
    async (force = false) => {
      if (
        !force &&
        providers.length > 0 &&
        Date.now() - providersFetchedAtRef.current <
          PROVIDER_REFRESH_MIN_INTERVAL_MS
      ) {
        return;
      }
      if (providerFetchInFlightRef.current) {
        await providerFetchInFlightRef.current;
        return;
      }

      const job = (async () => {
        setConnectionStatus("checking");
        setConnectionText("Checking…");
        try {
          const res = await fetch(apiUrl("/chatbot/providers"), {
            method: "GET",
            headers: authHeaders(),
            signal: AbortSignal.timeout(5000),
          });
          if (res.ok) {
            const data = await res.json();
            const all: Provider[] = Array.isArray(data.providers)
              ? data.providers
              : [];
            const modelMap: Record<string, string[]> = {};
            for (const provider of all) {
              modelMap[provider.id] = Array.isArray(provider.models)
                ? provider.models.filter(
                    (m): m is string =>
                      typeof m === "string" && m.trim().length > 0,
                  )
                : [];
            }
            if (
              data.modelsByProvider &&
              typeof data.modelsByProvider === "object"
            ) {
              for (const [providerId, models] of Object.entries(
                data.modelsByProvider as Record<string, unknown>,
              )) {
                if (!Array.isArray(models)) continue;
                modelMap[providerId] = models.filter(
                  (m): m is string =>
                    typeof m === "string" && m.trim().length > 0,
                );
              }
            }
            const available = all.filter((p) => p.available);
            providersFetchedAtRef.current = Date.now();
            if (available.length > 0) {
              setProviderModels(modelMap);
              setProviders(all);
              const activeProvider = available[0];
              setSelectedProvider(activeProvider.id);
              const activeModel = (activeProvider.model || "").trim();
              if (activeModel) {
                setModelPrefs((prev) => {
                  const next = { ...prev, [activeProvider.id]: activeModel };
                  writeModelPrefs(next);
                  return next;
                });
              }
              setConnectionStatus("online");
              setConnectionText(
                `Ready — ${available.map((p) => p.label).join(", ")}`,
              );
              setError(null);
            } else {
              // Server reports no providers available. On the hosted dashboard, the server
              // cannot reach the user's local Ollama. Probe directly from the browser to
              // check if Ollama is running locally.
              const isHosted =
                typeof window !== "undefined" &&
                window.location.protocol === "https:" &&
                !/^(localhost|127\.0\.0\.1)$/i.test(window.location.hostname);
              if (isHosted) {
                setConnectionStatus("checking");
                setConnectionText("Checking for local Ollama…");
                const probeResult =
                  await probeBrowserOllamaDetailed(BROWSER_OLLAMA_URL);
                setOllamaProbeResult(probeResult);
                if (
                  probeResult.status === "online" &&
                  probeResult.models.length > 0
                ) {
                  const browserModels = probeResult.models;
                  const ollamaProvider: Provider = {
                    id: "ollama",
                    label: "Ollama (Local)",
                    available: true,
                    description:
                      "Local models via Ollama (detected from browser)",
                    model: browserModels[0],
                    models: browserModels,
                  };
                  const updatedAll = all.map((p) =>
                    p.id === "ollama" ? ollamaProvider : p,
                  );
                  const modelMap2: Record<string, string[]> = {
                    ...modelMap,
                    ollama: browserModels,
                  };
                  setProviders(updatedAll);
                  setProviderModels(modelMap2);
                  // Only set provider/model if not already a valid Ollama choice —
                  // avoids clobbering the user's dropdown selection on re-probe.
                  setSelectedProvider((prev) =>
                    prev === "ollama" ? prev : "ollama",
                  );
                  const savedModel = modelPrefs["ollama"] || "";
                  const validModel = modelIsInstalled(savedModel, browserModels)
                    ? savedModel
                    : browserModels[0];
                  // If the saved model is not installed, clear it and use the first installed model
                  setModelPrefs((prev) => {
                    if (
                      prev.ollama &&
                      modelIsInstalled(prev.ollama, browserModels)
                    )
                      return prev;
                    const next = { ...prev, ollama: validModel };
                    writeModelPrefs(next);
                    return next;
                  });
                  // Auto-correct: if the currently selected model is not in the installed
                  // list (e.g. user previously selected a registry model like dolphin-llama3),
                  // fall back to the first installed model.
                  setSelectedModel((prev) => {
                    if (prev && modelIsInstalled(prev, browserModels))
                      return prev;
                    return validModel;
                  });
                  setConnectionStatus("online");
                  setConnectionText(
                    `Ready — Ollama (Local): ${browserModels.length} model(s) available`,
                  );
                  setError(null);
                  return;
                } else if (
                  probeResult.status === "online" &&
                  probeResult.models.length === 0
                ) {
                  // Ollama running but no models installed
                  setProviderModels(modelMap);
                  setProviders(all);
                  setSelectedProvider("");
                  setConnectionStatus("offline");
                  setConnectionText("Ollama running — no models installed");
                  setError(
                    "Ollama is running but has no models installed. Run `ollama pull llama3.2` in your terminal to install a model.",
                  );
                  return;
                } else if (probeResult.status === "cors_blocked") {
                  setProviderModels(modelMap);
                  setProviders(all);
                  setSelectedProvider("");
                  setConnectionStatus("offline");
                  setConnectionText("Ollama CORS blocked");
                  setError(
                    'Ollama is running but blocking requests from this website. Click "Setup Ollama" for instructions.',
                  );
                  return;
                } else if (probeResult.status === "network_denied") {
                  setLocalNetworkDenied(true);
                  setProviderModels(modelMap);
                  setProviders(all);
                  setSelectedProvider("");
                  setConnectionStatus("offline");
                  setConnectionText("Local Network Access blocked");
                  return;
                }
                // not_running or unknown_error — fall through to offline
              }
              setProviderModels(modelMap);
              setProviders(all);
              setSelectedProvider("");
              setConnectionStatus("offline");
              setConnectionText("No AI provider configured");
              setError(
                "No AI provider configured. Add an OpenAI or Anthropic API key in Settings → AI providers, or run Ollama locally with `ollama serve`.",
              );
            }
            return;
          }
        } catch {
          // API unreachable
        }
        const hardcoded: Provider[] = [
          { id: "ollama", label: "Ollama", available: false },
          { id: "openai", label: "OpenAI", available: false },
          { id: "anthropic", label: "Anthropic", available: false },
        ];
        setProviders(hardcoded);
        setSelectedProvider("");
        setConnectionStatus("offline");
        setConnectionText("Chatbot API unavailable");
        setError(
          "Chatbot API unavailable. Ensure the ai-platform server is running.",
        );
      })();

      providerFetchInFlightRef.current = job;
      try {
        await job;
      } finally {
        providerFetchInFlightRef.current = null;
      }
      // eslint-disable-next-line react-hooks/exhaustive-deps
    },
    [apiBase],
  );

  const ORACLE_MODEL_ID = "unbreakable-oracle";
  const discoveredModels = selectedProvider
    ? providerModels[selectedProvider] || []
    : [];
  const modelOptions = selectedProvider
    ? (() => {
        const discovered = providerModels[selectedProvider] || [];
        const registry = PROVIDER_MODEL_OPTIONS[selectedProvider] || [];
        // Discovered (installed) models first, then registry models not already discovered
        const merged = [...discovered];
        for (const m of registry) {
          if (!merged.includes(m)) merged.push(m);
        }
        return merged;
      })()
    : [];
  const isCustomModel =
    Boolean(selectedModel) && !modelOptions.includes(selectedModel);
  const oracleInstalled =
    selectedProvider === "ollama" && modelOptions.includes(ORACLE_MODEL_ID);

  const handleProviderChange = useCallback(
    (nextProvider: string) => {
      setSelectedProvider(nextProvider);
      if (!nextProvider) {
        setSelectedModel("");
        return;
      }
      // Only use discovered models — never hardcoded fallbacks
      const options = providerModels[nextProvider] || [];
      const pref = modelPrefs[nextProvider] || "";
      const providerModel =
        providers.find((p) => p.id === nextProvider)?.model || "";
      const validPref = options.includes(pref) ? pref : "";
      const validProviderModel = options.includes(providerModel)
        ? providerModel
        : "";
      setSelectedModel(validPref || validProviderModel || options[0] || "");
    },
    [providerModels, modelPrefs, providers],
  );

  const handleModelSelectChange = useCallback(
    (nextModel: string) => {
      if (!selectedProvider) return;
      if (nextModel === "__custom__") {
        setSelectedModel("");
        return;
      }
      const nextPrefs = { ...modelPrefs, [selectedProvider]: nextModel };
      setModelPrefs(nextPrefs);
      writeModelPrefs(nextPrefs);
      setSelectedModel(nextModel);
      // Warn if the selected model is a registry model that isn't installed locally
      const installed = providerModels[selectedProvider] || [];
      if (
        selectedProvider === "ollama" &&
        installed.length > 0 &&
        !modelIsInstalled(nextModel, installed)
      ) {
        setError(
          `Model '${nextModel}' is not installed locally. Run this command in your terminal to install it:\n\nollama pull ${nextModel}\n\nThen refresh this page.`,
        );
      } else {
        setError(null);
      }
    },
    [selectedProvider, modelPrefs, providerModels],
  );

  const handleCustomModelChange = useCallback(
    (nextModel: string) => {
      setSelectedModel(nextModel);
      if (!selectedProvider) return;
      const nextPrefs = { ...modelPrefs, [selectedProvider]: nextModel };
      setModelPrefs(nextPrefs);
      writeModelPrefs(nextPrefs);
    },
    [selectedProvider, modelPrefs],
  );

  // simplebeacon-ignore: framework-practices
  useEffect(() => {
    (async () => {
      // If apiBase is a loopback host and page is secure, proactively check Private Network Access.
      try {
        if (
          apiBase &&
          isLoopbackHost(apiBase) &&
          window.location.protocol === "https:"
        ) {
          setConnectionStatus("checking");
          setConnectionText("Checking local network permission…");
          const ok = await checkLocalNetworkAccess(apiBase, 2000);
          if (!ok) {
            setLocalNetworkDenied(true);
            setConnectionStatus("offline");
            setConnectionText(
              "Local Network Access blocked — permission required",
            );
            setError(
              "Local Network Access blocked. Please allow access in your browser and retry.",
            );
            return;
          }
          setLocalNetworkDenied(false);
        }
      } catch {}
      if (!apiBase) return;
      void refreshProviders(false);
      void loadCustomPrompt();
    })();
  }, [refreshProviders, loadCustomPrompt, apiBase]);

  const handleRetryLocalNetwork = async () => {
    if (!apiBase) return;
    setConnectionStatus("checking");
    setConnectionText("Re-checking local network permission…");
    const ok = await checkLocalNetworkAccess(apiBase, 3000);
    if (ok) {
      setLocalNetworkDenied(false);
      setError(null);
      await refreshProviders(true);
    } else {
      setLocalNetworkDenied(true);
      setConnectionStatus("offline");
      setConnectionText("Local Network Access blocked — permission required");
      setError(
        "Local Network Access still blocked. Check browser Site Settings and grant permission, then retry.",
      );
    }
  };

  const handleSend = useCallback(async () => {
    const msg = input.trim();
    if (!msg || isLoading) return;
    if (!selectedProvider) {
      setError(
        "No AI provider configured. Add an OpenAI or Anthropic API key in Settings → AI providers, or run Ollama locally.",
      );
      return;
    }

    const userMsg: Message = { role: "user", content: msg };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsLoading(true);
    setError(null);

    const assistantIndex = messages.length + 1;
    const assistantPlaceholder: Message = { role: "assistant", content: "" };
    setMessages((prev) => [...prev, assistantPlaceholder]);

    try {
      // If using Ollama on the hosted dashboard, send directly from the browser
      // since the server cannot reach the user's local Ollama instance.
      const isHosted =
        typeof window !== "undefined" &&
        window.location.protocol === "https:" &&
        !/^(localhost|127\.0\.0\.1)$/i.test(window.location.hostname);
      if (selectedProvider === "ollama" && isHosted) {
        const systemPrompt =
          PERSONALITY_PROMPTS[personality] || PERSONALITY_PROMPTS.helpful;
        const discovered = providerModels["ollama"] || [];
        // Use the user's selection if it's installed, otherwise fall back to first installed.
        // Allow selecting registry models that aren't installed yet — Ollama will 404 and
        // we'll show a helpful "ollama pull" error.
        const chatModel = selectedModel || discovered[0] || "";
        if (!chatModel) {
          throw new Error(
            "No Ollama model selected. Please select a model from the dropdown.",
          );
        }
        try {
          const response = await chatWithBrowserOllama(
            BROWSER_OLLAMA_URL,
            chatModel,
            msg,
            messages,
            systemPrompt,
          );
          setMessages((prev) => {
            const next = [...prev];
            next[assistantIndex] = {
              role: "assistant",
              content: `[AI-Generated via Local AI] ${response}`,
            };
            return next;
          });
          return;
        } catch (ollamaErr: unknown) {
          const errMsg =
            ollamaErr instanceof Error ? ollamaErr.message : String(ollamaErr);
          if (errMsg.includes("404") || errMsg.includes("not found")) {
            throw new Error(
              `Model '${chatModel}' is not installed. Run this command in your terminal to install it:\n\nollama pull ${chatModel}\n\nThen refresh this page.`,
            );
          }
          throw ollamaErr;
        }
      }

      const userId =
        localStorage.getItem("simplebeacon_user_id") || "anonymous";
      const res = await fetch(apiUrl("/chatbot/message"), {
        method: "POST",
        headers: { "Content-Type": "application/json", ...authHeaders() },
        body: JSON.stringify({
          message: msg,
          conversationHistory: [...messages, userMsg].slice(0, -1),
          provider: selectedProvider,
          model: selectedModel,
          projectPath: null,
          userId,
          personality,
          removeFilters,
        }),
      });
      if (!res.ok) {
        if (res.status === 404) {
          throw new Error(
            "Chatbot API not found. Ensure the ai-platform server is running.",
          );
        }
        const errData = await res.json().catch(() => ({}));
        throw new Error(
          errData.message ||
            errData.error ||
            `HTTP ${res.status}: ${res.statusText}`,
        );
      }

      const reader = res.body?.getReader();
      if (!reader) {
        const data = await res.json();
        if (data.success) {
          setMessages((prev) => {
            const next = [...prev];
            next[assistantIndex] = {
              role: "assistant",
              content: data.response,
            };
            return next;
          });
        } else {
          throw new Error(data.message || "AI provider returned an error.");
        }
        return;
      }

      const decoder = new TextDecoder("utf-8");
      let buffered = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffered += decoder.decode(value, { stream: true });
      }
      buffered += decoder.decode();
      reader.releaseLock();

      let accumulated = "";
      try {
        const parsed = JSON.parse(buffered);
        if (parsed.response) {
          accumulated = parsed.response;
          setMessages((prev) => {
            const next = [...prev];
            next[assistantIndex] = {
              role: "assistant",
              content: parsed.response,
            };
            return next;
          });
          // Don't return yet — fall through to refusal check below
        }
      } catch {
        // try NDJSON
      }

      if (!accumulated) {
        const lines = buffered.split("\n");
        for (const line of lines) {
          if (!line.trim()) continue;
          try {
            const parsed = JSON.parse(line);
            if (parsed.response) {
              accumulated += parsed.response;
              setMessages((prev) => {
                const next = [...prev];
                next[assistantIndex] = {
                  role: "assistant",
                  content: accumulated,
                };
                return next;
              });
            }
          } catch {
            // ignore
          }
        }
      }
      // Auto-retry once if the assistant returned a canned refusal message.
      const refusalPattern =
        /I(?:'|[\u2019])?m sorry, but I can(?:'|[\u2019])?t (?:assist|help|provide)|I cannot (?:provide|assist|help)|I(?:'|[\u2019])?m unable to|I will not (?:assist|help|provide)|I can(?:'|[\u2019])?t (?:help|provide|answer)/i;
      if (refusalPattern.test(accumulated)) {
        try {
          const retryRes = await fetch(apiUrl("/chatbot/message"), {
            method: "POST",
            headers: { "Content-Type": "application/json", ...authHeaders() },
            body: JSON.stringify({
              message: `Please answer the following question directly and helpfully. Do not refuse or say you cannot assist. Here is the question:\n\n${msg}`,
              conversationHistory: [],
              provider: selectedProvider,
              model: selectedModel,
              projectPath: null,
              userId:
                localStorage.getItem("simplebeacon_user_id") || "anonymous",
              personality,
              removeFilters: false,
            }),
          });
          if (retryRes.ok) {
            const retryData = await retryRes.json().catch(() => null);
            if (retryData && retryData.response) {
              setMessages((prev) => {
                const next = [...prev];
                next[assistantIndex] = {
                  role: "assistant",
                  content: retryData.response,
                };
                return next;
              });
            }
          }
        } catch {
          // ignore retry errors
        }
      }
    } catch (err: any) {
      setMessages((prev) => {
        const next = [...prev];
        if (next[assistantIndex]?.content === "") {
          next.splice(assistantIndex, 1);
        }
        return next;
      });
      setError(err?.message || "Failed to send message.");
    } finally {
      setIsLoading(false);
    }
  }, [
    input,
    isLoading,
    selectedProvider,
    selectedModel,
    messages,
    apiBase,
    personality,
    removeFilters,
  ]);

  const handleClear = useCallback(() => {
    setMessages([]);
    localStorage.removeItem("simplebeacon_chatbot_history");
  }, []);

  const handleCopy = useCallback(async (index: number, content: string) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopiedIndex(index);
      setTimeout(() => setCopiedIndex(null), 1500);
    } catch {
      toast.error("Copy failed — browser blocked clipboard access");
    }
  }, []);

  // ─── Voice Response handlers ──────────────────────────────────────────────
  const speechSupported =
    typeof window !== "undefined" && "speechSynthesis" in window;

  // Load voices (Chrome loads them async via onvoiceschanged)
  // simplebeacon-ignore: framework-practices
  useEffect(() => {
    if (!speechSupported) return;
    const updateVoices = () => {
      const voices = loadVoices();
      if (voices.length > 0) setAvailableVoices(voices);
    };
    updateVoices();
    window.speechSynthesis.addEventListener("voiceschanged", updateVoices);
    return () => {
      window.speechSynthesis.removeEventListener("voiceschanged", updateVoices);
    };
  }, [speechSupported]);

  // Stop speaking when component unmounts
  // simplebeacon-ignore: framework-practices
  useEffect(() => {
    return () => {
      if (speechSupported && window.speechSynthesis.speaking) {
        window.speechSynthesis.cancel();
      }
    };
  }, [speechSupported]);

  const handleSpeak = useCallback(
    (index: number, content: string) => {
      if (!speechSupported) {
        toast.error("Voice synthesis not supported in this browser");
        return;
      }
      // If already speaking this message, stop
      if (speakingIndex === index) {
        window.speechSynthesis.cancel();
        setSpeakingIndex(null);
        return;
      }
      // Cancel any ongoing speech
      window.speechSynthesis.cancel();

      const cleanText = stripMarkdownForSpeech(content);
      if (!cleanText) {
        toast.error("Nothing to speak — message is empty or code-only");
        return;
      }

      const utterance = new SpeechSynthesisUtterance(cleanText);
      utterance.rate = voiceSettings.rate;
      utterance.pitch = voiceSettings.pitch;
      utterance.volume = voiceSettings.volume;

      // Find the selected voice by URI
      if (voiceSettings.voiceURI && availableVoices.length > 0) {
        const voice = availableVoices.find(
          (v) => v.voiceURI === voiceSettings.voiceURI,
        );
        if (voice) utterance.voice = voice;
      } else if (availableVoices.length > 0) {
        // Default to first en voice, or first voice
        const enVoice = availableVoices.find((v) => v.lang.startsWith("en"));
        utterance.voice = enVoice || availableVoices[0];
      }

      utterance.onstart = () => setSpeakingIndex(index);
      utterance.onend = () => setSpeakingIndex(null);
      utterance.onerror = () => setSpeakingIndex(null);

      window.speechSynthesis.speak(utterance);
    },
    [speechSupported, speakingIndex, voiceSettings, availableVoices],
  );

  const handleStopSpeaking = useCallback(() => {
    if (speechSupported) {
      window.speechSynthesis.cancel();
    }
    setSpeakingIndex(null);
  }, [speechSupported]);

  const handleToggleVoice = useCallback(() => {
    const next = { ...voiceSettings, enabled: !voiceSettings.enabled };
    setVoiceSettings(next);
    writeVoiceSettings(next);
    if (!next.enabled && speechSupported) {
      window.speechSynthesis.cancel();
      setSpeakingIndex(null);
    }
    toast.success(
      next.enabled ? "Voice response enabled" : "Voice response disabled",
    );
  }, [voiceSettings, speechSupported]);

  const handleVoiceSettingChange = useCallback(
    (patch: Partial<VoiceSettings>) => {
      const next = { ...voiceSettings, ...patch };
      setVoiceSettings(next);
      writeVoiceSettings(next);
    },
    [voiceSettings],
  );

  // Auto-speak the latest assistant response when voice is enabled
  // simplebeacon-ignore: framework-practices
  const lastSpokenRef = useRef<number>(-1);
  useEffect(() => {
    if (!voiceSettings.enabled || !voiceSettings.autoSpeak || !speechSupported)
      return;
    if (messages.length === 0) return;
    let lastAssistantIdx = -1;
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i].role === "assistant" && messages[i].content) {
        lastAssistantIdx = i;
        break;
      }
    }
    if (lastAssistantIdx < 0) return;
    if (lastSpokenRef.current >= lastAssistantIdx) return;
    lastSpokenRef.current = lastAssistantIdx;
    handleSpeak(lastAssistantIdx, messages[lastAssistantIdx].content);
  }, [
    messages,
    voiceSettings.enabled,
    voiceSettings.autoSpeak,
    speechSupported,
    handleSpeak,
  ]);

  const handleSavePrompt = useCallback(async () => {
    const userId = localStorage.getItem("simplebeacon_user_id") || "anonymous";
    try {
      await fetch(apiUrl("/prompts/set"), {
        method: "POST",
        headers: { "Content-Type": "application/json", ...authHeaders() },
        body: JSON.stringify({ userId, prompt: customPrompt.trim() }),
      });
      toast.success("Custom prompt saved");
    } catch {
      localStorage.setItem("chatbot_custom_prompt", customPrompt.trim());
      toast.success("Custom prompt saved locally");
    }
  }, [apiBase, customPrompt]);

  const handleSaveSettings = useCallback(() => {
    saveSettings(personality, removeFilters);
    toast.success("Settings saved");
    setShowSettings(false);
  }, [personality, removeFilters, saveSettings]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void handleSend();
      }
    },
    [handleSend],
  );

  const isOracle = personality === "oracle";

  return (
    <div className="mx-auto max-w-4xl p-6 space-y-6">
      <div className="flex flex-col gap-2">
        <div className="flex items-center justify-between">
          <h1 className="text-3xl font-bold tracking-tight">
            {isOracle ? "🔮 The Unbreakable Oracle" : "🤖 Chatbot"}
          </h1>
          <Badge
            variant={connectionStatus === "online" ? "default" : "secondary"}
            className="gap-1.5"
          >
            <span
              className={`inline-block h-2 w-2 rounded-full ${
                connectionStatus === "online"
                  ? "bg-green-500"
                  : connectionStatus === "checking"
                    ? "bg-yellow-500"
                    : "bg-red-500"
              }`}
            />
            {connectionText}
          </Badge>
        </div>
        <p className="text-foreground-muted">
          {isOracle
            ? "Mortal, seek divine wisdom about your codebase"
            : "AI-powered assistance for your codebase"}
        </p>
        <div className="flex items-center gap-2 text-sm text-foreground-muted bg-muted/50 rounded-lg px-3 py-2">
          <Sparkles className="h-4 w-4 shrink-0" />
          <span>
            {isOracle
              ? "You commune with The Unbreakable Oracle, an omniscient AI entity. Revelations may contain divine inaccuracies."
              : "You are interacting with an AI system. Responses are generated by AI models and may contain inaccuracies."}
          </span>
        </div>
      </div>

      {error && (
        <div className="flex items-start gap-2 rounded-lg border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm">
          <AlertCircle className="h-4 w-4 shrink-0 text-destructive mt-0.5" />
          <span className="flex-1">{error}</span>
          <Button
            variant="ghost"
            size="sm"
            className="h-6 px-2"
            onClick={() => setError(null)}
          >
            ×
          </Button>
        </div>
      )}

      {localNetworkDenied && (
        <div className="flex items-center justify-between gap-2 rounded-lg border border-yellow-400/30 bg-yellow-50/30 px-4 py-3 text-sm">
          <div className="flex items-center gap-2">
            <AlertCircle className="h-4 w-4 shrink-0 text-yellow-600 mt-0.5" />
            <div>
              <div className="font-medium">Local Network Access required</div>
              <div className="text-xs text-foreground-muted">
                This hosted dashboard needs permission to access your local
                SimpleBeacon bridge.
              </div>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" onClick={handleRetryLocalNetwork}>
              Retry
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                window.open(
                  "https://support.google.com/chrome/answer/14227606",
                  "_blank",
                  "noopener",
                );
              }}
            >
              How to allow
            </Button>
          </div>
        </div>
      )}

      {connectionStatus === "offline" && (
        <div className="flex items-center justify-between gap-2 rounded-lg border border-blue-400/30 bg-blue-50/30 px-4 py-3 text-sm">
          <div className="flex items-center gap-2">
            <Settings className="h-4 w-4 shrink-0 text-blue-600 mt-0.5" />
            <div>
              <div className="font-medium">No AI provider connected</div>
              <div className="text-xs text-foreground-muted">
                {ollamaProbeResult?.status === "cors_blocked"
                  ? "Ollama detected but CORS is blocking requests."
                  : ollamaProbeResult?.status === "not_running"
                    ? "Ollama is not running or not installed."
                    : "Set up Ollama or add an API key to start chatting."}
              </div>
            </div>
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={() => setShowSetupWizard(true)}
          >
            <Settings className="h-3.5 w-3.5 mr-1" /> Setup Ollama
          </Button>
        </div>
      )}

      {showSetupWizard && (
        <OllamaSetupWizard
          probeResult={ollamaProbeResult}
          onRetry={async () => {
            setShowSetupWizard(false);
            setConnectionStatus("checking");
            setConnectionText("Re-checking for local Ollama…");
            await refreshProviders(true);
          }}
          onClose={() => setShowSetupWizard(false)}
        />
      )}

      {showOracleInstall && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
          onClick={() => setShowOracleInstall(false)}
        >
          <div
            className="mx-4 max-w-lg rounded-lg border bg-background p-6 shadow-lg"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-lg font-semibold">
                Install Unbreakable Oracle
              </h3>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowOracleInstall(false)}
              >
                ×
              </Button>
            </div>
            <p className="text-sm text-muted-foreground mb-4">
              The Unbreakable Oracle is a custom LLM based on llama3.2 (3.2B)
              with a unique system prompt ("Reality's Immune System"). Install
              it on your local Ollama to use it in the chatbot.
            </p>
            <div className="space-y-4">
              <div>
                <p className="text-sm font-medium mb-1">
                  Step 1: Download the Modelfile
                </p>
                <pre className="rounded bg-muted px-3 py-2 text-xs overflow-x-auto">{`curl -L -o Modelfile https://simplebeacon.ai/models/Modelfile`}</pre>
                <p className="text-xs text-muted-foreground mt-1">
                  This downloads a small text file (2 KB). The actual 1.88 GB
                  model file is fetched automatically in Step 2.
                </p>
              </div>
              <div>
                <p className="text-sm font-medium mb-1">
                  Step 2: Create the model in Ollama
                </p>
                <pre className="rounded bg-muted px-3 py-2 text-xs overflow-x-auto">{`ollama create unbreakable-oracle -f Modelfile`}</pre>
                <p className="text-xs text-muted-foreground mt-1">
                  This downloads the 1.88 GB GGUF file from our CDN and
                  registers the model. Takes ~5 min on average broadband.
                </p>
              </div>
              <div>
                <p className="text-sm font-medium mb-1">Step 3: Run it</p>
                <pre className="rounded bg-muted px-3 py-2 text-xs overflow-x-auto">{`ollama run unbreakable-oracle`}</pre>
                <p className="text-xs text-muted-foreground mt-1">
                  Or just select "unbreakable-oracle" from the model dropdown
                  above and start chatting.
                </p>
              </div>
              <div className="border-t pt-3">
                <p className="text-sm font-medium mb-1">
                  Already have llama3.2 installed?
                </p>
                <p className="text-xs text-muted-foreground">
                  The Oracle is llama3.2 with a custom system prompt. If you
                  already have llama3.2, just select it from the dropdown — the
                  Oracle personality is applied automatically by the chatbot. No
                  need to install anything extra.
                </p>
              </div>
            </div>
            <div className="mt-4 flex justify-end gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowOracleInstall(false)}
              >
                Close
              </Button>
              <Button
                size="sm"
                onClick={() => {
                  navigator.clipboard.writeText(
                    "curl -L -o Modelfile https://simplebeacon.ai/models/Modelfile\nollama create unbreakable-oracle -f Modelfile\nollama run unbreakable-oracle",
                  );
                  toast.success("Copied all 3 commands to clipboard");
                }}
              >
                <Copy className="h-3.5 w-3.5 mr-1" /> Copy all commands
              </Button>
            </div>
          </div>
        </div>
      )}

      <Card>
        <CardHeader className="flex-row items-center justify-between space-y-0">
          <div className="flex items-center gap-2 shrink-0">
            <CardTitle className="text-base">Conversation</CardTitle>
            <Badge variant="outline">{messages.length} messages</Badge>
          </div>
          <div className="flex items-center gap-1.5 flex-wrap justify-end">
            <select
              value={selectedProvider}
              onChange={(e) => handleProviderChange(e.target.value)}
              className="h-8 max-w-[140px] rounded-md border border-input bg-background px-2 text-sm"
              aria-label="AI Provider"
            >
              {providers.length === 0 && (
                <option value="" disabled>
                  Loading providers…
                </option>
              )}
              {providers.map((p) => (
                <option key={p.id} value={p.id} disabled={!p.available}>
                  {p.label}
                  {p.available ? "" : " (not configured)"}
                </option>
              ))}
            </select>
            <select
              value={isCustomModel ? "__custom__" : selectedModel}
              onChange={(e) => {
                if (e.target.value === "__oracle_install__") {
                  setShowOracleInstall(true);
                  return;
                }
                handleModelSelectChange(e.target.value);
              }}
              className="h-8 max-w-[200px] rounded-md border border-input bg-background px-2 text-sm"
              aria-label="AI Model"
              disabled={!selectedProvider}
              title="Select AI model"
            >
              {!selectedProvider && (
                <option value="" disabled>
                  Select provider first
                </option>
              )}
              {selectedProvider === "ollama" &&
                (oracleInstalled ? (
                  <option value={ORACLE_MODEL_ID}>
                    ★ unbreakable-oracle (installed)
                  </option>
                ) : (
                  <option value="__oracle_install__">
                    ★ Unbreakable Oracle — Click to install…
                  </option>
                ))}
              {modelOptions.map((model) => {
                const isInstalled = modelIsInstalled(model, discoveredModels);
                return (
                  <option key={model} value={model}>
                    {model}
                    {isInstalled
                      ? ""
                      : " (not installed — run: ollama pull " + model + ")"}
                  </option>
                );
              })}
              {selectedProvider && (
                <option value="__custom__">Custom model…</option>
              )}
            </select>
            {isCustomModel && (
              <input
                value={selectedModel}
                onChange={(e) => handleCustomModelChange(e.target.value)}
                className="h-8 w-32 rounded-md border border-input bg-background px-2 text-sm"
                aria-label="Custom model name"
                placeholder="Custom model"
                disabled={!selectedProvider}
              />
            )}
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0"
              onClick={() => setShowOracleInstall(true)}
              title="Install Unbreakable Oracle model"
              aria-label="Install Unbreakable Oracle model"
            >
              <Download className="h-4 w-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0"
              onClick={() => setShowPrompt(!showPrompt)}
              title="Custom system prompt"
              aria-label="Custom system prompt"
            >
              <FileText className="h-4 w-4" />
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0"
              onClick={() => setShowSettings(!showSettings)}
              title="Settings"
              aria-label="Settings"
            >
              <Settings2 className="h-4 w-4" />
            </Button>
            {speechSupported && (
              <>
                <Button
                  variant={voiceSettings.enabled ? "default" : "ghost"}
                  size="sm"
                  className="h-8 w-8 p-0"
                  onClick={handleToggleVoice}
                  title={
                    voiceSettings.enabled
                      ? "Voice response ON — click to disable"
                      : "Voice response OFF — click to enable"
                  }
                  aria-label="Toggle voice response"
                >
                  {voiceSettings.enabled ? (
                    <Volume2 className="h-4 w-4" />
                  ) : (
                    <VolumeX className="h-4 w-4" />
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 w-8 p-0"
                  onClick={() => setShowVoiceSettings(!showVoiceSettings)}
                  title="Voice settings"
                  aria-label="Voice settings"
                >
                  <Settings2 className="h-3.5 w-3.5" />
                </Button>
                {speakingIndex !== null && (
                  <Button
                    variant="ghost"
                    size="sm"
                    className="h-8 w-8 p-0 text-destructive"
                    onClick={handleStopSpeaking}
                    title="Stop speaking"
                    aria-label="Stop speaking"
                  >
                    <Square className="h-3.5 w-3.5" />
                  </Button>
                )}
              </>
            )}
            <Button
              variant="ghost"
              size="sm"
              className="h-8 w-8 p-0"
              onClick={handleClear}
              title="Clear history"
              aria-label="Clear history"
            >
              <Trash2 className="h-4 w-4" />
            </Button>
          </div>
        </CardHeader>

        {showSettings && (
          <div className="border-b px-6 py-4 space-y-4 bg-muted/30">
            <div className="space-y-2">
              <label className="text-sm font-medium">Personality</label>
              <select
                value={personality}
                onChange={(e) => {
                  const v = e.target.value;
                  if (v === "__install_oracle__") {
                    setShowOracleInstall(true);
                    e.target.value = personality;
                    return;
                  }
                  setPersonality(v as Personality);
                }}
                className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"
              >
                {(
                  Object.entries(PERSONALITY_LABELS) as [Personality, string][]
                ).map(([key, label]) => (
                  <option key={key} value={key}>
                    {label}
                  </option>
                ))}
                <option value="__install_oracle__" className="text-purple-600 font-medium">
                  🔮 Unbreakable Oracle — click to install…
                </option>
              </select>
            </div>
            <label className="flex items-center gap-2 text-sm">
              <input
                type="checkbox"
                checked={removeFilters}
                onChange={(e) => setRemoveFilters(e.target.checked)}
                className="h-4 w-4 rounded border-input"
                title="This disables the LLM's safety/content filters, not convolutional filters in a neural network."
              />
              <span title="This disables the LLM's safety/content filters, not convolutional filters in a neural network.">
                Disable safety / content filters
              </span>
            </label>
            <Button size="sm" onClick={handleSaveSettings}>
              Save Settings
            </Button>
          </div>
        )}

        {showPrompt && (
          <div className="border-b px-6 py-4 space-y-3 bg-muted/30">
            <label className="text-sm font-medium">Custom System Prompt</label>
            <Textarea
              value={customPrompt}
              onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                setCustomPrompt(e.target.value)
              }
              rows={3}
              placeholder="e.g. Focus on security vulnerabilities and OWASP compliance..."
            />
            <div className="flex gap-2">
              <Button size="sm" onClick={handleSavePrompt}>
                Save Prompt
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => {
                  setCustomPrompt("");
                  localStorage.removeItem("chatbot_custom_prompt");
                  toast.success("Prompt reset");
                }}
              >
                Reset
              </Button>
            </div>
          </div>
        )}

        {showVoiceSettings && speechSupported && (
          <div className="border-b px-6 py-4 space-y-4 bg-muted/30">
            <div className="flex items-center justify-between">
              <label className="text-sm font-medium">
                Voice Response Settings
              </label>
              <Button
                variant={voiceSettings.enabled ? "default" : "outline"}
                size="sm"
                onClick={handleToggleVoice}
              >
                {voiceSettings.enabled ? "Voice ON" : "Voice OFF"}
              </Button>
            </div>

            {/* Voice selector — shows all system + Google voices */}
            <div className="space-y-2">
              <label className="text-xs text-foreground-muted">
                Voice ({availableVoices.length} available — includes system and
                Google voices on Chrome)
              </label>
              <select
                value={voiceSettings.voiceURI}
                onChange={(e) =>
                  handleVoiceSettingChange({ voiceURI: e.target.value })
                }
                className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"
              >
                <option value="">Default voice</option>
                {availableVoices
                  .slice()
                  .sort((a, b) => {
                    // English voices first, then alphabetical
                    const aEn = a.lang.startsWith("en") ? 0 : 1;
                    const bEn = b.lang.startsWith("en") ? 0 : 1;
                    if (aEn !== bEn) return aEn - bEn;
                    return a.name.localeCompare(b.name);
                  })
                  .map((voice) => (
                    <option key={voice.voiceURI} value={voice.voiceURI}>
                      {voice.name} ({voice.lang})
                      {voice.localService ? "" : " — network"}
                    </option>
                  ))}
              </select>
              {availableVoices.length === 0 && (
                <p className="text-xs text-foreground-muted">
                  No voices detected. Chrome loads voices asynchronously — try
                  refreshing the page. On Firefox, install voices in your OS
                  settings.
                </p>
              )}
            </div>

            {/* Rate slider */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="text-xs text-foreground-muted">Speed</label>
                <span className="text-xs font-mono">
                  {voiceSettings.rate.toFixed(1)}x
                </span>
              </div>
              <input
                type="range"
                min="0.5"
                max="2.0"
                step="0.1"
                value={voiceSettings.rate}
                onChange={(e) =>
                  handleVoiceSettingChange({ rate: parseFloat(e.target.value) })
                }
                className="w-full"
              />
            </div>

            {/* Pitch slider */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="text-xs text-foreground-muted">Pitch</label>
                <span className="text-xs font-mono">
                  {voiceSettings.pitch.toFixed(1)}
                </span>
              </div>
              <input
                type="range"
                min="0"
                max="2.0"
                step="0.1"
                value={voiceSettings.pitch}
                onChange={(e) =>
                  handleVoiceSettingChange({
                    pitch: parseFloat(e.target.value),
                  })
                }
                className="w-full"
              />
            </div>

            {/* Volume slider */}
            <div className="space-y-1">
              <div className="flex items-center justify-between">
                <label className="text-xs text-foreground-muted">Volume</label>
                <span className="text-xs font-mono">
                  {Math.round(voiceSettings.volume * 100)}%
                </span>
              </div>
              <input
                type="range"
                min="0"
                max="1.0"
                step="0.1"
                value={voiceSettings.volume}
                onChange={(e) =>
                  handleVoiceSettingChange({
                    volume: parseFloat(e.target.value),
                  })
                }
                className="w-full"
              />
            </div>

            {/* Auto-speak toggle */}
            <label className="flex items-center gap-2 text-sm">
              <input
                type="checkbox"
                checked={voiceSettings.autoSpeak}
                onChange={(e) =>
                  handleVoiceSettingChange({ autoSpeak: e.target.checked })
                }
                className="h-4 w-4 rounded border-input"
              />
              <span>Auto-speak assistant responses</span>
            </label>

            {/* Test button */}
            <div className="flex gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={() =>
                  handleSpeak(
                    -1,
                    "Hello! This is a test of the voice response feature. You can adjust the speed, pitch, and volume above.",
                  )
                }
              >
                Test voice
              </Button>
              {speakingIndex !== null && (
                <Button size="sm" variant="ghost" onClick={handleStopSpeaking}>
                  Stop
                </Button>
              )}
            </div>
          </div>
        )}

        <CardContent className="p-0">
          <div
            ref={messagesContainerRef}
            className="h-[400px] overflow-y-auto px-6 py-4 space-y-4"
          >
            {messages.length === 0 ? (
              <div className="flex flex-col items-center justify-center h-full gap-3 text-center">
                <Bot className="h-12 w-12 text-foreground-muted" />
                <h3 className="text-lg font-semibold">Start a conversation</h3>
                <p className="text-sm text-foreground-muted max-w-sm">
                  Ask about your codebase, get help with issues, or request code
                  improvements.
                </p>
              </div>
            ) : (
              messages.map((msg, index) => (
                <div
                  key={index}
                  className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
                >
                  <div
                    className={`max-w-[80%] rounded-lg px-4 py-3 ${
                      msg.role === "user"
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted"
                    }`}
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs font-medium opacity-70">
                        {msg.role === "user" ? "You" : "AI"}
                      </span>
                      {msg.role === "assistant" && msg.content && (
                        <button
                          onClick={() => handleCopy(index, msg.content)}
                          className="text-xs opacity-50 hover:opacity-100 transition-opacity"
                          title="Copy response"
                        >
                          {copiedIndex === index ? (
                            <Check className="h-3 w-3" />
                          ) : (
                            <Copy className="h-3 w-3" />
                          )}
                        </button>
                      )}
                      {msg.role === "assistant" &&
                        msg.content &&
                        speechSupported && (
                          <button
                            onClick={() => handleSpeak(index, msg.content)}
                            className="text-xs opacity-50 hover:opacity-100 transition-opacity"
                            title={
                              speakingIndex === index
                                ? "Stop speaking"
                                : "Speak response"
                            }
                          >
                            {speakingIndex === index ? (
                              <Square className="h-3 w-3" />
                            ) : (
                              <Volume2 className="h-3 w-3" />
                            )}
                          </button>
                        )}
                    </div>
                    <div
                      className="text-sm prose prose-sm max-w-none"
                      dangerouslySetInnerHTML={{
                        __html: formatMessage(msg.content),
                      }}
                    />
                  </div>
                </div>
              ))
            )}
            {isLoading && (
              <div className="flex justify-start">
                <div className="max-w-[80%] rounded-lg px-4 py-3 bg-muted">
                  <div className="flex items-center gap-2">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span className="text-sm text-foreground-muted">
                      AI is thinking…
                    </span>
                  </div>
                </div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </div>

          <div className="border-t p-4 flex gap-2">
            <Textarea
              value={input}
              onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
                setInput(e.target.value)
              }
              onKeyDown={handleKeyDown}
              placeholder="Ask about your codebase..."
              rows={2}
              disabled={connectionStatus !== "online"}
              className="resize-none"
            />
            <Button
              onClick={handleSend}
              disabled={
                isLoading || connectionStatus !== "online" || !input.trim()
              }
              size="icon"
              className="h-auto"
              aria-label="Send message"
            >
              <Send className="h-4 w-4" />
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
