'use strict';

/**
 * Stage 3: HSM adapter metrics registry.
 *
 * In-memory counters and histograms for HSM operations, exposed in
 * Prometheus exposition format. Follows the pattern established by
 * siem-exporter.cjs (in-memory counters) and the /api/agentic/metrics
 * endpoint (text/plain; version=0.0.4).
 *
 * @module hsm-adapter/hsm-metrics
 */

// ── Counters ────────────────────────────────────────────────────
const counters = {
  hsm_wrap_total: 0,
  hsm_wrap_failures_total: 0,
  hsm_unwrap_total: 0,
  hsm_unwrap_failures_total: 0,
  hsm_create_kek_total: 0,
  hsm_create_kek_failures_total: 0,
  hsm_rotate_kek_total: 0,
  hsm_zeroize_total: 0,
  hsm_circuit_opened_total: 0,
  hsm_circuit_closed_total: 0,
  hsm_circuit_half_open_total: 0,
  // Track 33: Recovery sync counters
  hsm_recovery_started_total: 0,
  hsm_recovery_synced_total: 0,
  hsm_recovery_failures_total: 0,
  hsm_recovery_catchup_batches_total: 0,
  // Track 34: Consensus counters
  hsm_consensus_leader_elections_total: 0,
  hsm_consensus_leader_elections_won_total: 0,
  hsm_consensus_quorum_lost_total: 0,
  hsm_consensus_log_replicated_total: 0,
  hsm_consensus_log_committed_total: 0,
  hsm_consensus_heartbeats_sent_total: 0,
  // Track 34 Stage 3: Byzantine hardening counters
  hsm_consensus_rpc_signed_total: 0,
  hsm_consensus_rpc_verified_total: 0,
  hsm_consensus_signature_invalid_total: 0,
  hsm_consensus_peer_key_unknown_total: 0,
  // Track 34 Phase 4: Replay protection counters
  hsm_consensus_replay_detected_total: 0,
  hsm_consensus_nonce_stale_total: 0,
  hsm_consensus_timestamp_expired_total: 0,
  // Track 34 Phase 5: Peer key rotation counters
  hsm_consensus_peer_key_added_total: 0,
  hsm_consensus_peer_key_revoked_total: 0,
  hsm_consensus_peer_key_rotation_blocked_total: 0,
  // Track 34 Phase 6: Snapshot/compaction counters
  hsm_consensus_snapshot_created_total: 0,
  hsm_consensus_snapshot_installed_total: 0,
  hsm_consensus_snapshot_rejected_total: 0,
  // Track 34 Phase 7: Implicit outbound signing counters
  hsm_consensus_outbound_signed_total: 0,
  hsm_consensus_outbound_sign_failed_total: 0,
  // Track 40: Distributed Consensus Coordinator counters
  hsm_consensus_coord_groups_created_total: 0,
  hsm_consensus_coord_groups_destroyed_total: 0,
  hsm_consensus_coord_proposals_routed_total: 0,
  hsm_consensus_coord_proposals_rejected_total: 0,
  hsm_consensus_coord_faults_detected_total: 0,
  hsm_consensus_coord_view_change_started_total: 0,
  hsm_consensus_coord_view_change_completed_total: 0,
  hsm_consensus_coord_view_change_aborted_total: 0,
  hsm_consensus_coord_quorum_verified_total: 0,
  hsm_consensus_coord_quorum_denied_total: 0,
  // Track 41: Hardware Enclave Isolation counters
  hsm_enclave_bootstrap_total: 0,
  hsm_enclave_bootstrap_failed_total: 0,
  hsm_enclave_seal_total: 0,
  hsm_enclave_unseal_total: 0,
  hsm_enclave_unseal_failed_total: 0,
  hsm_enclave_key_provisioned_total: 0,
  hsm_enclave_key_provision_blocked_total: 0,
  hsm_enclave_attestation_verified_total: 0,
  hsm_enclave_attestation_rejected_total: 0,
  hsm_enclave_active: 0,
  // Track 42: Enclave Secret-Sealing and Attestation Policy counters
  hsm_sealing_policy_validated_total: 0,
  hsm_sealing_policy_blocked_total: 0,
  hsm_unseal_policy_validated_total: 0,
  hsm_unseal_policy_blocked_total: 0,
  hsm_attestation_challenge_issued_total: 0,
  hsm_attestation_policy_validated_total: 0,
  hsm_attestation_replay_detected_total: 0,
  hsm_attestation_expired_total: 0,
  hsm_key_provisioning_validated_total: 0,
  hsm_key_provisioning_blocked_total: 0,
  hsm_sealed_keys_tracked: 0,
  // Track 43: Multiparty Auditing and Remote Attestation Logs counters
  hsm_audit_entry_appended_total: 0,
  hsm_audit_entry_committed_total: 0,
  hsm_audit_entry_pending: 0,
  hsm_audit_signature_added_total: 0,
  hsm_audit_verification_timeout_total: 0,
  hsm_audit_duplicate_signature_total: 0,
  hsm_audit_chain_verified_total: 0,
  hsm_audit_chain_broken_total: 0,
  hsm_audit_verifier_registered_total: 0,
  hsm_audit_event_type_blocked_total: 0,
  hsm_audit_committed_entries: 0,
  // Track 44: Distributed Sharding and Cross-Enclave State Sync counters
  hsm_cross_enclave_registered_total: 0,
  hsm_cross_enclave_unregistered_total: 0,
  hsm_cross_enclave_stale_detected_total: 0,
  hsm_cross_enclave_active: 0,
  hsm_cross_enclave_shard_created_total: 0,
  hsm_cross_enclave_shard_reassigned_total: 0,
  hsm_cross_enclave_state_written_total: 0,
  hsm_cross_enclave_state_conflict_total: 0,
  hsm_cross_enclave_state_too_large_total: 0,
  hsm_cross_enclave_sync_total: 0,
  hsm_cross_enclave_sync_merged_total: 0,
  hsm_cross_enclave_sync_skipped_total: 0,
  hsm_cross_enclave_shards: 0,
  // Track 45: Enclave Key Rotation and Cryptographic Heartbeats counters
  hsm_key_rotation_total: 0,
  hsm_key_rotation_blocked_total: 0,
  hsm_key_rotation_skipped_total: 0,
  hsm_key_revoked_total: 0,
  hsm_key_quarantined_total: 0,
  hsm_key_recovered_total: 0,
  hsm_heartbeat_issued_total: 0,
  hsm_heartbeat_verified_total: 0,
  hsm_heartbeat_expired_total: 0,
  hsm_heartbeat_response_invalid_total: 0,
  hsm_heartbeat_active_keys: 0,
  hsm_heartbeat_quarantined_keys: 0,
  hsm_heartbeat_pending_challenges: 0,
  // Track 46: Zero-Knowledge Inter-Enclave MPC Handshakes counters
  hsm_mpc_handshake_initiated_total: 0,
  hsm_mpc_handshake_committed_total: 0,
  hsm_mpc_handshake_proven_total: 0,
  hsm_mpc_handshake_verified_total: 0,
  hsm_mpc_handshake_finalized_total: 0,
  hsm_mpc_handshake_aborted_total: 0,
  hsm_mpc_handshake_expired_total: 0,
  hsm_mpc_proof_valid_total: 0,
  hsm_mpc_proof_invalid_total: 0,
  hsm_mpc_handshake_active: 0,
  // Track 47: Post-Quantum Cryptographic Enclave Migrations counters
  hsm_pqc_migration_registered_total: 0,
  hsm_pqc_migration_planned_total: 0,
  hsm_pqc_hybrid_activated_total: 0,
  hsm_pqc_fully_activated_total: 0,
  hsm_pqc_migration_completed_total: 0,
  hsm_pqc_migration_rollback_total: 0,
  hsm_pqc_migration_failed_total: 0,
  hsm_pqc_signature_constraint_satisfied_total: 0,
  hsm_pqc_signature_constraint_violated_total: 0,
  hsm_pqc_classical_enclaves: 0,
  hsm_pqc_hybrid_enclaves: 0,
  hsm_pqc_pqc_enclaves: 0,
  // Track 48: Enclave Fault Injection and Byzantine Chaos Testing counters
  hsm_fault_injected_total: 0,
  hsm_fault_resolved_total: 0,
  hsm_fault_expired_total: 0,
  hsm_fault_cancelled_total: 0,
  hsm_fault_byzantine_total: 0,
  hsm_fault_network_partition_total: 0,
  hsm_fault_crash_total: 0,
  hsm_fault_key_corruption_total: 0,
  hsm_fault_timing_attack_total: 0,
  hsm_fault_active: 0,
  hsm_fault_scenario_completed_total: 0,
  hsm_fault_scenario_failed_total: 0,
  // Track 49: Dynamic Enclave Rescaling and Predictive Load Balancing counters
  hsm_rescaling_scale_up_total: 0,
  hsm_rescaling_scale_down_total: 0,
  hsm_rescaling_rebalance_total: 0,
  hsm_rescaling_failed_total: 0,
  hsm_rescaling_chaos_triggered_total: 0,
  hsm_rescaling_active_enclaves: 0,
  hsm_rescaling_average_load: 0,
  hsm_rescaling_predicted_load: 0,
  hsm_rescaling_imbalance: 0,
  // Track 50: Confidential Federated Learning and ZK Model Aggregation counters
  hsm_fl_rounds_initiated_total: 0,
  hsm_fl_rounds_completed_total: 0,
  hsm_fl_rounds_failed_total: 0,
  hsm_fl_rounds_expired_total: 0,
  hsm_fl_gradients_submitted_total: 0,
  hsm_fl_gradients_verified_total: 0,
  hsm_fl_gradients_rejected_total: 0,
  hsm_fl_active_rounds: 0,
  hsm_fl_global_model_version: 0,
  hsm_fl_participants_total: 0,
  // Track 51: Homomorphic Encryption Over Mesh Topologies counters
  hsm_he_mesh_nodes_total: 0,
  hsm_he_mesh_edges_total: 0,
  hsm_he_mesh_active_nodes: 0,
  hsm_he_mesh_queries_created_total: 0,
  hsm_he_mesh_queries_completed_total: 0,
  hsm_he_mesh_queries_failed_total: 0,
  hsm_he_mesh_queries_expired_total: 0,
  hsm_he_mesh_hops_executed_total: 0,
  hsm_he_mesh_active_queries: 0,
  // Track 52: Secure Multi-Party Inner Product and Encrypted Search Indexes counters
  hsm_sip_indexes_built_total: 0,
  hsm_sip_indexes_active: 0,
  hsm_sip_queries_total: 0,
  hsm_sip_queries_completed_total: 0,
  hsm_sip_queries_failed_total: 0,
  hsm_sip_parties_total: 0,
  hsm_sip_parties_active: 0,
  hsm_sip_documents_indexed_total: 0,
  hsm_sip_search_results_total: 0,
  // Track 53: Zero-Knowledge Range Proofs and Auditable Asset Solvency counters
  hsm_zk_range_proofs_generated_total: 0,
  hsm_zk_range_proofs_verified_total: 0,
  hsm_zk_range_proofs_invalid_total: 0,
  hsm_zk_range_proofs_revoked_total: 0,
  hsm_zk_range_proofs_active: 0,
  hsm_zk_batch_proofs_total: 0,
  hsm_zk_solvency_audits_total: 0,
  hsm_zk_solvency_audits_solvent_total: 0,
  hsm_zk_solvency_audits_insolvent_total: 0,
  // Track 54: Multi-Party Threshold Cryptography and Distributed Decryption Circuits counters
  hsm_tdc_keysets_created_total: 0,
  hsm_tdc_keysets_active: 0,
  hsm_tdc_circuits_initiated_total: 0,
  hsm_tdc_circuits_completed_total: 0,
  hsm_tdc_circuits_failed_total: 0,
  hsm_tdc_circuits_expired_total: 0,
  hsm_tdc_partial_shares_submitted_total: 0,
  hsm_tdc_partial_shares_verified_total: 0,
  hsm_tdc_partial_shares_invalid_total: 0,
  // Track 55: ZK Verifiable Secret Sharing and Proactive Secret Sharing counters
  hsm_vss_sessions_total: 0,
  hsm_vss_sessions_completed_total: 0,
  hsm_vss_shares_verified_total: 0,
  hsm_vss_shares_invalid_total: 0,
  hsm_vss_complaints_total: 0,
  hsm_vss_disqualifications_total: 0,
  hsm_pss_epochs_total: 0,
  hsm_pss_epochs_active: 0,
  hsm_pss_refreshes_total: 0,
  hsm_pss_recoveries_total: 0,
  // Track 56: Oblivious RAM and Secure Side-Channel Memory Attenuation counters
  hsm_oram_blocks_total: 0,
  hsm_oram_reads_total: 0,
  hsm_oram_writes_total: 0,
  hsm_oram_deletes_total: 0,
  hsm_oram_dummy_accesses_total: 0,
  hsm_oram_stash_size: 0,
  hsm_oram_reshuffles_total: 0,
  hsm_oram_stash_evictions_total: 0,
  // Track 57: zk-SNARK Enclave Verifiers counters
  hsm_snark_circuits_compiled_total: 0,
  hsm_snark_circuits_active: 0,
  hsm_snark_setups_generated_total: 0,
  hsm_snark_setups_active: 0,
  hsm_snark_proofs_generated_total: 0,
  hsm_snark_proofs_verified_total: 0,
  hsm_snark_proofs_invalid_total: 0,
  hsm_snark_proofs_aggregated_total: 0,
  hsm_snark_setups_destroyed_total: 0,
  // Track 58: Multi-Key FHE Relinearization Engine counters
  hsm_mfhe_key_pairs_total: 0,
  hsm_mfhe_key_pairs_active: 0,
  hsm_mfhe_relin_keys_total: 0,
  hsm_mfhe_encryptions_total: 0,
  hsm_mfhe_decryptions_total: 0,
  hsm_mfhe_homomorphic_ops_total: 0,
  hsm_mfhe_relinearizations_total: 0,
  hsm_mfhe_key_switches_total: 0,
  hsm_mfhe_bootstraps_total: 0,
  // Track 59: VDF and Time-Locked Enclave Puzzles counters
  hsm_vdf_created_total: 0,
  hsm_vdf_evaluated_total: 0,
  hsm_vdf_verified_total: 0,
  hsm_vdf_active: 0,
  hsm_puzzles_created_total: 0,
  hsm_puzzles_solved_total: 0,
  hsm_puzzles_expired_total: 0,
  hsm_puzzles_active: 0,
  // Track 60: Multi-Asset Sharded Mixnets and Blind Confidential Transactions
  hsm_mixnet_nodes_total: 0,
  hsm_mixnet_nodes_active: 0,
  hsm_mixnet_shards_total: 0,
  hsm_mixnet_transactions_created_total: 0,
  hsm_mixnet_transactions_mixed_total: 0,
  hsm_mixnet_transactions_confirmed_total: 0,
  hsm_mixnet_pools_shuffled_total: 0,
  hsm_mixnet_pools_flushed_total: 0,
  hsm_mixnet_relays_total: 0,
  // Track 61: Recursive Proof Aggregation Engine counters
  hsm_rpa_proofs_submitted_total: 0,
  hsm_rpa_proofs_folded_total: 0,
  hsm_rpa_chain_aggregations_total: 0,
  hsm_rpa_tree_aggregations_total: 0,
  hsm_rpa_vdf_aggregations_total: 0,
  hsm_rpa_mixnet_compressions_total: 0,
  hsm_rpa_aggregations_verified_total: 0,
  hsm_rpa_active_proofs: 0,
  // Track 62: PQC Time-Locked Matrix Routing and Temporal Validity Verification
  hsm_ptlm_matrices_initialized_total: 0,
  hsm_ptlm_matrices_routed_total: 0,
  hsm_ptlm_matrices_released_total: 0,
  hsm_ptlm_matrices_expired_total: 0,
  hsm_ptlm_matrices_active: 0,
  hsm_ptlm_routing_nodes_total: 0,
  hsm_ptlm_lattice_keys_generated_total: 0,
  hsm_ptlm_committee_signatures_aggregated_total: 0,
  hsm_ptlm_temporal_proofs_verified_total: 0,
  hsm_ptlm_temporal_proofs_slashed_total: 0,
  hsm_ptlm_batch_verifications_total: 0,
  hsm_ptlm_banned_peers: 0,
  // Track 63: PQC Blind Option Pools & HW-SNARK VDF Aggregators
  hsm_bop_pools_initialized_total: 0,
  hsm_bop_pools_executed_total: 0,
  hsm_bop_pools_settled_total: 0,
  hsm_bop_pools_expired_total: 0,
  hsm_bop_pools_cancelled_total: 0,
  hsm_bop_pools_active: 0,
  hsm_bop_batch_inits_total: 0,
  hsm_bop_committee_signatures_aggregated_total: 0,
  hsm_bop_margin_proofs_verified_total: 0,
  hsm_bop_margin_proofs_slashed_total: 0,
  hsm_bop_batch_verifications_total: 0,
  hsm_bop_hw_snark_proofs_generated_total: 0,
  hsm_bop_hw_snark_proofs_verified_total: 0,
  hsm_bop_banned_peers: 0,
  // Track 64: PQC Prediction Markets & ZK Resolution Validators
  hsm_predmkt_markets_initialized_total: 0,
  hsm_predmkt_markets_finalized_total: 0,
  hsm_predmkt_markets_settled_total: 0,
  hsm_predmkt_markets_disputed_total: 0,
  hsm_predmkt_markets_cancelled_total: 0,
  hsm_predmkt_markets_expired_total: 0,
  hsm_predmkt_markets_active: 0,
  hsm_predmkt_batch_inits_total: 0,
  hsm_predmkt_committee_signatures_aggregated_total: 0,
  hsm_predmkt_resolution_votes_recorded_total: 0,
  hsm_predmkt_resolution_votes_slashed_total: 0,
  hsm_predmkt_batch_verifications_total: 0,
  hsm_predmkt_hw_snark_proofs_generated_total: 0,
  hsm_predmkt_hw_snark_proofs_verified_total: 0,
  hsm_predmkt_banned_peers: 0,
  // Track 65: PQC Fractional Custody & ZK Release Verifiers
  hsm_fracvault_vaults_initialized_total: 0,
  hsm_fracvault_vaults_liquidated_total: 0,
  hsm_fracvault_vaults_settled_total: 0,
  hsm_fracvault_vaults_cancelled_total: 0,
  hsm_fracvault_vaults_active: 0,
  hsm_fracvault_escrows_locked_total: 0,
  hsm_fracvault_escrows_released_total: 0,
  hsm_fracvault_batch_inits_total: 0,
  hsm_fracvault_committee_signatures_aggregated_total: 0,
  hsm_fracvault_releases_recorded_total: 0,
  hsm_fracvault_releases_slashed_total: 0,
  hsm_fracvault_batch_verifications_total: 0,
  hsm_fracvault_hw_snark_proofs_generated_total: 0,
  hsm_fracvault_hw_snark_proofs_verified_total: 0,
  hsm_fracvault_banned_peers: 0,
  // Track 66: PQC Lending Collateral & ZK Solvency Proof Processors
  hsm_lendpool_pools_initialized_total: 0,
  hsm_lendpool_pools_liquidated_total: 0,
  hsm_lendpool_pools_settled_total: 0,
  hsm_lendpool_pools_cancelled_total: 0,
  hsm_lendpool_pools_active: 0,
  hsm_lendpool_rebalances_total: 0,
  hsm_lendpool_batch_inits_total: 0,
  hsm_lendpool_committee_signatures_aggregated_total: 0,
  hsm_lendpool_solvency_proofs_verified_total: 0,
  hsm_lendpool_solvency_proofs_slashed_total: 0,
  hsm_lendpool_batch_verifications_total: 0,
  hsm_lendpool_hw_snark_proofs_generated_total: 0,
  hsm_lendpool_hw_snark_proofs_verified_total: 0,
  hsm_lendpool_banned_peers: 0,
  // Track 67: PQC Insurance Underwriting & ZK Risk Exposure Validators
  hsm_inspault_pools_initialized_total: 0,
  hsm_inspault_pools_liquidated_total: 0,
  hsm_inspault_pools_settled_total: 0,
  hsm_inspault_pools_cancelled_total: 0,
  hsm_inspault_pools_active: 0,
  hsm_inspault_rebalances_total: 0,
  hsm_inspault_batch_inits_total: 0,
  hsm_inspault_committee_signatures_aggregated_total: 0,
  hsm_inspault_claims_verified_total: 0,
  hsm_inspault_claims_slashed_total: 0,
  hsm_inspault_batch_verifications_total: 0,
  hsm_inspault_hw_snark_proofs_generated_total: 0,
  hsm_inspault_hw_snark_proofs_verified_total: 0,
  hsm_inspault_banned_peers: 0,
  // Track 68: PQC Supply Chain Escrow & ZK Order Milestone Validators
  hsm_scordr_orders_initialized_total: 0,
  hsm_scordr_orders_released_total: 0,
  hsm_scordr_orders_settled_total: 0,
  hsm_scordr_orders_cancelled_total: 0,
  hsm_scordr_orders_active: 0,
  hsm_scordr_rebalances_total: 0,
  hsm_scordr_batch_inits_total: 0,
  hsm_scordr_committee_signatures_aggregated_total: 0,
  hsm_scordr_milestones_verified_total: 0,
  hsm_scordr_milestones_slashed_total: 0,
  hsm_scordr_batch_verifications_total: 0,
  hsm_scordr_hw_snark_proofs_generated_total: 0,
  hsm_scordr_hw_snark_proofs_verified_total: 0,
  hsm_scordr_banned_peers: 0,
  // Track 69: PQC Real Estate Tokenization & ZK Title Deed Validators
  hsm_repools_pools_initialized_total: 0,
  hsm_repools_pools_finalized_total: 0,
  hsm_repools_pools_settled_total: 0,
  hsm_repools_pools_cancelled_total: 0,
  hsm_repools_pools_active: 0,
  hsm_repools_rebalances_total: 0,
  hsm_repools_batch_inits_total: 0,
  hsm_repools_committee_signatures_aggregated_total: 0,
  hsm_repools_clearances_verified_total: 0,
  hsm_repools_clearances_slashed_total: 0,
  hsm_repools_batch_verifications_total: 0,
  hsm_repools_hw_snark_proofs_generated_total: 0,
  hsm_repools_hw_snark_proofs_verified_total: 0,
  hsm_repools_banned_peers: 0,
  // Track 70: PQC Carbon Credit Tokenization & ZK Carbon Retirement Validators
  hsm_carpools_pools_initialized_total: 0,
  hsm_carpools_pools_retired_total: 0,
  hsm_carpools_pools_settled_total: 0,
  hsm_carpools_pools_cancelled_total: 0,
  hsm_carpools_pools_active: 0,
  hsm_carpools_rebalances_total: 0,
  hsm_carpools_batch_inits_total: 0,
  hsm_carpools_committee_signatures_aggregated_total: 0,
  hsm_carpools_retirements_verified_total: 0,
  hsm_carpools_retirements_slashed_total: 0,
  hsm_carpools_batch_verifications_total: 0,
  hsm_carpools_hw_snark_proofs_generated_total: 0,
  hsm_carpools_hw_snark_proofs_verified_total: 0,
  hsm_carpools_banned_peers: 0,
  // Track 71: PQC Identity Gating & ZK Identity Gating Validators
  hsm_idgate_pools_initialized_total: 0,
  hsm_idgate_pools_completed_total: 0,
  hsm_idgate_pools_settled_total: 0,
  hsm_idgate_pools_cancelled_total: 0,
  hsm_idgate_pools_active: 0,
  hsm_idgate_rebalances_total: 0,
  hsm_idgate_batch_inits_total: 0,
  hsm_idgate_committee_signatures_aggregated_total: 0,
  hsm_idgate_claims_verified_total: 0,
  hsm_idgate_claims_slashed_total: 0,
  hsm_idgate_batch_verifications_total: 0,
  hsm_idgate_hw_snark_proofs_generated_total: 0,
  hsm_idgate_hw_snark_proofs_verified_total: 0,
  hsm_idgate_banned_peers: 0,
  // Track 72: PQC Health Data Gating & ZK Health Attribute Validators
  hsm_hgate_pools_initialized_total: 0,
  hsm_hgate_pools_completed_total: 0,
  hsm_hgate_pools_settled_total: 0,
  hsm_hgate_pools_cancelled_total: 0,
  hsm_hgate_pools_active: 0,
  hsm_hgate_rebalances_total: 0,
  hsm_hgate_batch_inits_total: 0,
  hsm_hgate_committee_signatures_aggregated_total: 0,
  hsm_hgate_claims_verified_total: 0,
  hsm_hgate_claims_slashed_total: 0,
  hsm_hgate_batch_verifications_total: 0,
  hsm_hgate_hw_snark_proofs_generated_total: 0,
  hsm_hgate_hw_snark_proofs_verified_total: 0,
  hsm_hgate_banned_peers: 0,
  // Track 73: PQC Education Credential Gating & ZK Academic Credential Validators
  hsm_edugate_pools_initialized_total: 0,
  hsm_edugate_pools_accredited_total: 0,
  hsm_edugate_pools_settled_total: 0,
  hsm_edugate_pools_cancelled_total: 0,
  hsm_edugate_pools_active: 0,
  hsm_edugate_rebalances_total: 0,
  hsm_edugate_batch_inits_total: 0,
  hsm_edugate_committee_signatures_aggregated_total: 0,
  hsm_edugate_claims_verified_total: 0,
  hsm_edugate_claims_slashed_total: 0,
  hsm_edugate_batch_verifications_total: 0,
  hsm_edugate_hw_snark_proofs_generated_total: 0,
  hsm_edugate_hw_snark_proofs_verified_total: 0,
  hsm_edugate_banned_peers: 0,
  // Track 26: DKG & zk-SNARKs counters
  hsm_dkg_rounds_started_total: 0,
  hsm_dkg_rounds_completed_total: 0,
  hsm_dkg_shares_verified_total: 0,
  hsm_dkg_shares_rejected_total: 0,
  hsm_dkg_complaints_filed_total: 0,
  hsm_dkg_nodes_disqualified_total: 0,
  hsm_dkg_zk_proofs_generated_total: 0,
  hsm_dkg_zk_proofs_invalid_total: 0,
  // Track 27: PQC Threshold Signatures counters
  hsm_pqc_threshold_sign_total: 0,
  hsm_pqc_threshold_sign_failures_total: 0,
  hsm_pqc_threshold_partial_sign_total: 0,
  hsm_pqc_threshold_partial_verified_total: 0,
  hsm_pqc_threshold_partial_rejected_total: 0,
  hsm_pqc_threshold_verify_total: 0,
  hsm_pqc_threshold_verify_failures_total: 0,
  // Track 28: Confidential Computing Sandboxing counters
  hsm_sandbox_created_total: 0,
  hsm_sandbox_destroyed_total: 0,
  hsm_sandbox_attested_total: 0,
  hsm_sandbox_attestation_failed_total: 0,
  hsm_sandbox_execute_total: 0,
  hsm_sandbox_execute_failures_total: 0,
  hsm_sandbox_zeroized_total: 0,
  hsm_sandbox_active: 0,
  // Track 32: BFT Shard Sync counters
  hsm_shard_append_total: 0,
  hsm_shard_ack_total: 0,
  hsm_shard_commit_total: 0,
  hsm_shard_catchup_batch_total: 0,
  hsm_shard_byzantine_detected_total: 0,
  hsm_shard_lagging_nodes: 0,
  hsm_shard_active: 0,
  // Track 34: Cross-Cluster Migration counters
  hsm_migration_initiated_total: 0,
  hsm_migration_attested_total: 0,
  hsm_migration_committed_total: 0,
  hsm_migration_rolled_back_total: 0,
  hsm_migration_ack_total: 0,
  hsm_migration_verification_failed_total: 0,
  hsm_migration_active: 0,
  // Track 35: Cluster Key Reconciliation counters
  hsm_reconciliation_scans_total: 0,
  hsm_reconciliation_divergence_detected_total: 0,
  hsm_reconciliation_promoted_total: 0,
  hsm_reconciliation_quarantined_total: 0,
  hsm_reconciliation_rollback_blocked_total: 0,
  hsm_reconciliation_promotion_votes_total: 0,
  hsm_reconciliation_divergent_keys: 0,
  // Track 36: ZK Proof-of-Assets counters
  hsm_poa_asset_registered_total: 0,
  hsm_poa_proof_created_total: 0,
  hsm_poa_proof_verified_total: 0,
  hsm_poa_proof_invalid_total: 0,
  hsm_poa_double_count_blocked_total: 0,
  hsm_poa_quorum_signatures_total: 0,
  hsm_poa_active_proofs: 0,
  // Track 37: Multiparty Re-Keying counters
  hsm_rekey_proposed_total: 0,
  hsm_rekey_resharing_submitted_total: 0,
  hsm_rekey_verified_total: 0,
  hsm_rekey_committed_total: 0,
  hsm_rekey_aborted_total: 0,
  hsm_rekey_rollback_blocked_total: 0,
  hsm_rekey_active: 0,
  // Track 38: Encrypted P2P Routing counters
  hsm_p2p_route_discovered_total: 0,
  hsm_p2p_message_encrypted_total: 0,
  hsm_p2p_message_relayed_total: 0,
  hsm_p2p_message_delivered_total: 0,
  hsm_p2p_route_revoked_total: 0,
  hsm_p2p_replay_blocked_total: 0,
  hsm_p2p_active_routes: 0,
  // Track 39: Threshold Account Recovery counters
  hsm_recovery_requested_total: 0,
  hsm_recovery_approved_total: 0,
  hsm_recovery_executed_total: 0,
  hsm_recovery_rejected_total: 0,
  hsm_recovery_replay_blocked_total: 0,
  hsm_recovery_time_lock_blocked_total: 0,
  hsm_recovery_active: 0,
  // Track 73: PQC Education Credential Gating counters
  hsm_education_gating_pool_initialized_total: 0,
  hsm_zk_academic_claim_verified_total: 0,
  hsm_credential_accreditation_completed_total: 0,
  // Track 74: PQC Patent Verification Gating counters
  hsm_patent_gating_pool_initialized_total: 0,
  hsm_zk_patent_claim_verified_total: 0,
  hsm_patent_license_accreditation_completed_total: 0,
  // Track 74 Phase 2: PQC Patent Verification Gating & ZK Patent Claim Validators
  hsm_pgate_pools_initialized_total: 0,
  hsm_pgate_pools_accredited_total: 0,
  hsm_pgate_pools_settled_total: 0,
  hsm_pgate_pools_cancelled_total: 0,
  hsm_pgate_pools_active: 0,
  hsm_pgate_rebalances_total: 0,
  hsm_pgate_batch_inits_total: 0,
  hsm_pgate_committee_signatures_aggregated_total: 0,
  hsm_pgate_claims_verified_total: 0,
  hsm_pgate_claims_slashed_total: 0,
  hsm_pgate_batch_verifications_total: 0,
  hsm_pgate_hw_snark_proofs_generated_total: 0,
  hsm_pgate_hw_snark_proofs_verified_total: 0,
  hsm_pgate_banned_peers: 0,
  // Track 74 Phase 2: PQC Patent Verification Gating & ZK Patent Claim Validators
  hsm_pgate_pools_initialized_total: 0,
  hsm_pgate_pools_accredited_total: 0,
  hsm_pgate_pools_settled_total: 0,
  hsm_pgate_pools_cancelled_total: 0,
  hsm_pgate_pools_active: 0,
  hsm_pgate_rebalances_total: 0,
  hsm_pgate_batch_inits_total: 0,
  hsm_pgate_committee_signatures_aggregated_total: 0,
  hsm_pgate_claims_verified_total: 0,
  hsm_pgate_claims_slashed_total: 0,
  hsm_pgate_batch_verifications_total: 0,
  hsm_pgate_hw_snark_proofs_generated_total: 0,
  hsm_pgate_hw_snark_proofs_verified_total: 0,
  hsm_pgate_banned_peers: 0,
  // Track 75: PQC Energy Certificate Gating counters
  hsm_energy_gating_pool_initialized_total: 0,
  hsm_zk_energy_claim_verified_total: 0,
  hsm_certificate_trading_accreditation_completed_total: 0,
  // Track 76: PQC Supply Chain Provenance Gating counters
  hsm_supply_chain_gating_pool_initialized_total: 0,
  hsm_zk_provenance_claim_verified_total: 0,
  hsm_component_lineage_accreditation_completed_total: 0,
  // Track 76 Phase 2: PQC Supply Chain Provenance Gating & ZK Provenance Claim Validators
  hsm_sgate_pools_initialized_total: 0,
  hsm_sgate_pools_accredited_total: 0,
  hsm_sgate_pools_settled_total: 0,
  hsm_sgate_pools_cancelled_total: 0,
  hsm_sgate_pools_active: 0,
  hsm_sgate_rebalances_total: 0,
  hsm_sgate_batch_inits_total: 0,
  hsm_sgate_committee_signatures_aggregated_total: 0,
  hsm_sgate_claims_verified_total: 0,
  hsm_sgate_claims_slashed_total: 0,
  hsm_sgate_batch_verifications_total: 0,
  hsm_sgate_hw_snark_proofs_generated_total: 0,
  hsm_sgate_hw_snark_proofs_verified_total: 0,
  hsm_sgate_banned_peers: 0,
  // Track 77: PQC Biometric Verification Gating counters
  hsm_biometric_gating_pool_initialized_total: 0,
  hsm_zk_biometric_claim_verified_total: 0,
  hsm_liveness_attestation_accreditation_completed_total: 0,
  // Track 78: PQC Financial Derivatives Gating counters
  hsm_derivative_gating_pool_initialized_total: 0,
  hsm_zk_derivative_claim_verified_total: 0,
  hsm_counterparty_risk_accreditation_completed_total: 0,
  // Track 79: PQC Clinical Trial Verification Gating counters
  hsm_clinical_trial_gating_pool_initialized_total: 0,
  hsm_zk_trial_claim_verified_total: 0,
  hsm_cohort_accreditation_completed_total: 0,
  // Track 80: PQC VRF Audit Sortition Gating counters
  hsm_sortition_gating_pool_initialized_total: 0,
  hsm_zk_sortition_claim_verified_total: 0,
  hsm_validator_accreditation_completed_total: 0,
  // Track 81: PQC Cross-Border Logistics Gating counters
  hsm_logistics_gating_pool_initialized_total: 0,
  hsm_zk_manifest_claim_verified_total: 0,
  hsm_carrier_accreditation_completed_total: 0,
  // Track 82: PQC AI Model Training Gating counters
  hsm_training_gating_pool_initialized_total: 0,
  hsm_zk_training_claim_verified_total: 0,
  hsm_model_accreditation_completed_total: 0,
  // Track 83: PQC Scientific Reproducibility Gating counters
  hsm_research_gating_pool_initialized_total: 0,
  hsm_zk_replication_claim_verified_total: 0,
  hsm_peer_review_accreditation_completed_total: 0,
  // Track 84: PQC DAO Treasury Management Gating counters
  hsm_treasury_gating_pool_initialized_total: 0,
  hsm_zk_proposal_claim_verified_total: 0,
  hsm_voter_accreditation_completed_total: 0,
  // Track 85: PQC Telecom Routing Gating counters
  hsm_telecom_routing_pool_initialized_total: 0,
  hsm_zk_bandwidth_claim_verified_total: 0,
  hsm_routing_accreditation_completed_total: 0,
  // Track 86: PQC Health Insurance Claim Auditing Gating counters
  hsm_insurance_gating_pool_initialized_total: 0,
  hsm_zk_claim_audit_verified_total: 0,
  hsm_actuarial_accreditation_completed_total: 0,
  // Track 87: PQC Space-Asset Telemetry Gating counters
  hsm_orbital_gating_pool_initialized_total: 0,
  hsm_zk_telemetry_claim_verified_total: 0,
  hsm_orbital_accreditation_completed_total: 0,
  // Track 88: PQC Water Rights Allocation Gating counters
  hsm_water_gating_pool_initialized_total: 0,
  hsm_zk_water_claim_verified_total: 0,
  hsm_watershed_accreditation_completed_total: 0,
  // Track 89: PQC Nuclear Safeguards Monitoring Gating counters
  hsm_nuclear_gating_pool_initialized_total: 0,
  hsm_zk_safeguards_claim_verified_total: 0,
  hsm_nuclear_accreditation_completed_total: 0,
  // Track 90: PQC Wildlife Conservation Tracking Gating counters
  hsm_wildlife_gating_pool_initialized_total: 0,
  hsm_zk_conservation_claim_verified_total: 0,
  hsm_biodiversity_accreditation_completed_total: 0,
  // Track 91: PQC Smart-Grid Micro-Transaction Gating counters
  hsm_smartgrid_gating_pool_initialized_total: 0,
  hsm_zk_micro_transaction_claim_verified_total: 0,
  hsm_load_balance_accreditation_completed_total: 0,
  // Track 92: PQC Global Health Epidemiological Surveillance Gating counters
  hsm_epidemiology_gating_pool_initialized_total: 0,
  hsm_zk_epidemiological_claim_verified_total: 0,
  hsm_outbreak_accreditation_completed_total: 0,
  // Track 93: PQC Cultural Heritage Provenance Gating counters
  hsm_heritage_gating_pool_initialized_total: 0,
  hsm_zk_authentication_claim_verified_total: 0,
  hsm_provenance_accreditation_completed_total: 0,
  // Track 94: PQC Ocean Fisheries Allocation Gating counters
  hsm_fisheries_gating_pool_initialized_total: 0,
  hsm_zk_catch_claim_verified_total: 0,
  hsm_quota_accreditation_completed_total: 0,
  // Track 95: PQC Deep-Sea Mineral Rights Gating counters
  hsm_seabed_gating_pool_initialized_total: 0,
  hsm_zk_extraction_claim_verified_total: 0,
  hsm_lease_accreditation_completed_total: 0,
};

// ── Histograms (bucketed) ───────────────────────────────────────
// Latency histograms with buckets in milliseconds.
// Bucket boundaries chosen for HSM operations (typically 10-500ms).
const LATENCY_BUCKETS = [1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000];

const histograms = {
  hsm_wrap_duration_ms: { buckets: LATENCY_BUCKETS, counts: new Array(LATENCY_BUCKETS.length + 1).fill(0), sum: 0, count: 0 },
  hsm_unwrap_duration_ms: { buckets: LATENCY_BUCKETS, counts: new Array(LATENCY_BUCKETS.length + 1).fill(0), sum: 0, count: 0 },
  hsm_create_kek_duration_ms: { buckets: LATENCY_BUCKETS, counts: new Array(LATENCY_BUCKETS.length + 1).fill(0), sum: 0, count: 0 },
};

// Metadata for Prometheus exposition
const META = {
  hsm_wrap_total: { help: 'Total HSM wrapKey operations initiated.', type: 'counter' },
  hsm_wrap_failures_total: { help: 'Total HSM wrapKey operations that failed.', type: 'counter' },
  hsm_unwrap_total: { help: 'Total HSM unwrapKey operations initiated.', type: 'counter' },
  hsm_unwrap_failures_total: { help: 'Total HSM unwrapKey operations that failed.', type: 'counter' },
  hsm_create_kek_total: { help: 'Total KEK creation operations initiated.', type: 'counter' },
  hsm_create_kek_failures_total: { help: 'Total KEK creation operations that failed.', type: 'counter' },
  hsm_rotate_kek_total: { help: 'Total KEK rotation operations initiated.', type: 'counter' },
  hsm_zeroize_total: { help: 'Total KEK zeroization operations completed.', type: 'counter' },
  hsm_circuit_opened_total: { help: 'Total times the HSM circuit breaker transitioned to OPEN state.', type: 'counter' },
  hsm_circuit_closed_total: { help: 'Total times the HSM circuit breaker transitioned to CLOSED state.', type: 'counter' },
  hsm_circuit_half_open_total: { help: 'Total times the HSM circuit breaker transitioned to HALF-OPEN state.', type: 'counter' },
  hsm_recovery_started_total: { help: 'Total cluster node recovery sessions started.', type: 'counter' },
  hsm_recovery_synced_total: { help: 'Total cluster node recovery sessions that reached synced state.', type: 'counter' },
  hsm_recovery_failures_total: { help: 'Total cluster node recovery sessions that failed.', type: 'counter' },
  hsm_recovery_catchup_batches_total: { help: 'Total catch-up batches applied during recovery sync.', type: 'counter' },
  hsm_consensus_leader_elections_total: { help: 'Total leader election cycles started.', type: 'counter' },
  hsm_consensus_leader_elections_won_total: { help: 'Total leader elections won by this node.', type: 'counter' },
  hsm_consensus_quorum_lost_total: { help: 'Total times quorum was lost during consensus operations.', type: 'counter' },
  hsm_consensus_log_replicated_total: { help: 'Total log entries replicated to followers.', type: 'counter' },
  hsm_consensus_log_committed_total: { help: 'Total log entries committed via quorum.', type: 'counter' },
  hsm_consensus_heartbeats_sent_total: { help: 'Total leader heartbeats sent to followers.', type: 'counter' },
  hsm_consensus_rpc_signed_total: { help: 'Total outbound RPC frames signed with Ed25519.', type: 'counter' },
  hsm_consensus_rpc_verified_total: { help: 'Total inbound RPC frames successfully verified.', type: 'counter' },
  hsm_consensus_signature_invalid_total: { help: 'Total inbound RPC frames with invalid signatures.', type: 'counter' },
  hsm_consensus_peer_key_unknown_total: { help: 'Total inbound RPC frames from peers with no registered public key.', type: 'counter' },
  hsm_consensus_replay_detected_total: { help: 'Total RPC frames rejected as replayed (stale nonce or expired timestamp).', type: 'counter' },
  hsm_consensus_nonce_stale_total: { help: 'Total RPC frames rejected with stale nonce (non-monotonic).', type: 'counter' },
  hsm_consensus_timestamp_expired_total: { help: 'Total RPC frames rejected due to expired timestamp.', type: 'counter' },
  hsm_consensus_peer_key_added_total: { help: 'Total peer public keys added via quorum-gated rotation.', type: 'counter' },
  hsm_consensus_peer_key_revoked_total: { help: 'Total peer public keys revoked via quorum-gated rotation.', type: 'counter' },
  hsm_consensus_peer_key_rotation_blocked_total: { help: 'Total peer key rotation attempts blocked (not leader, key not found, etc.).', type: 'counter' },
  hsm_consensus_snapshot_created_total: { help: 'Total log compaction snapshots created by this node.', type: 'counter' },
  hsm_consensus_snapshot_installed_total: { help: 'Total snapshots installed from a leader on this node.', type: 'counter' },
  hsm_consensus_snapshot_rejected_total: { help: 'Total snapshots rejected (stale, invalid signature, etc.).', type: 'counter' },
  hsm_consensus_outbound_signed_total: { help: 'Total outbound RPC frames auto-signed by the engine.', type: 'counter' },
  hsm_consensus_outbound_sign_failed_total: { help: 'Total outbound RPC frames that failed auto-signing.', type: 'counter' },
  // Track 40: Distributed Consensus Coordinator
  hsm_consensus_coord_groups_created_total: { help: 'Total consensus groups created by the coordinator.', type: 'counter' },
  hsm_consensus_coord_groups_destroyed_total: { help: 'Total consensus groups destroyed by the coordinator.', type: 'counter' },
  hsm_consensus_coord_proposals_routed_total: { help: 'Total proposals successfully routed to a consensus group.', type: 'counter' },
  hsm_consensus_coord_proposals_rejected_total: { help: 'Total proposals rejected (group not found, not active, no routing key, etc.).', type: 'counter' },
  hsm_consensus_coord_faults_detected_total: { help: 'Total node faults detected by the fault detector.', type: 'counter' },
  hsm_consensus_coord_view_change_started_total: { help: 'Total view change procedures initiated.', type: 'counter' },
  hsm_consensus_coord_view_change_completed_total: { help: 'Total view change procedures completed successfully.', type: 'counter' },
  hsm_consensus_coord_view_change_aborted_total: { help: 'Total view change procedures aborted (timeout, conflict, etc.).', type: 'counter' },
  hsm_consensus_coord_quorum_verified_total: { help: 'Total proposals that passed cross-group quorum verification.', type: 'counter' },
  hsm_consensus_coord_quorum_denied_total: { help: 'Total proposals denied due to insufficient quorum.', type: 'counter' },
  // Track 41: Hardware Enclave Isolation
  hsm_enclave_bootstrap_total: { help: 'Total enclave bootstrap (initialize) operations.', type: 'counter' },
  hsm_enclave_bootstrap_failed_total: { help: 'Total enclave bootstrap operations that failed.', type: 'counter' },
  hsm_enclave_seal_total: { help: 'Total seal operations inside the enclave boundary.', type: 'counter' },
  hsm_enclave_unseal_total: { help: 'Total unseal operations inside the enclave boundary.', type: 'counter' },
  hsm_enclave_unseal_failed_total: { help: 'Total unseal operations that failed (tamper or auth tag mismatch).', type: 'counter' },
  hsm_enclave_key_provisioned_total: { help: 'Total keys provisioned into the enclave after attestation.', type: 'counter' },
  hsm_enclave_key_provision_blocked_total: { help: 'Total key provisioning attempts blocked (no attestation, untrusted measurement).', type: 'counter' },
  hsm_enclave_attestation_verified_total: { help: 'Total attestation documents that passed verification.', type: 'counter' },
  hsm_enclave_attestation_rejected_total: { help: 'Total attestation documents rejected (bad authority, measurement, expired, bad signature).', type: 'counter' },
  hsm_enclave_active: { help: 'Number of currently active (initialized) enclaves.', type: 'gauge' },
  // Track 42: Enclave Secret-Sealing and Attestation Policy
  hsm_sealing_policy_validated_total: { help: 'Total seal operations that passed policy validation.', type: 'counter' },
  hsm_sealing_policy_blocked_total: { help: 'Total seal operations blocked by policy (bad cipher, key too small, data too large, key expired).', type: 'counter' },
  hsm_unseal_policy_validated_total: { help: 'Total unseal operations that passed policy validation.', type: 'counter' },
  hsm_unseal_policy_blocked_total: { help: 'Total unseal operations blocked by policy (outside enclave boundary).', type: 'counter' },
  hsm_attestation_challenge_issued_total: { help: 'Total attestation challenge nonces issued.', type: 'counter' },
  hsm_attestation_policy_validated_total: { help: 'Total attestation responses that passed policy validation.', type: 'counter' },
  hsm_attestation_replay_detected_total: { help: 'Total attestation responses rejected as replay attacks.', type: 'counter' },
  hsm_attestation_expired_total: { help: 'Total attestation responses rejected as expired.', type: 'counter' },
  hsm_key_provisioning_validated_total: { help: 'Total key provisioning operations that passed policy validation.', type: 'counter' },
  hsm_key_provisioning_blocked_total: { help: 'Total key provisioning operations blocked by policy (no attestation, bad key type, too many keys).', type: 'counter' },
  hsm_sealed_keys_tracked: { help: 'Number of currently tracked sealed keys.', type: 'gauge' },
  // Track 43: Multiparty Auditing and Remote Attestation Logs
  hsm_audit_entry_appended_total: { help: 'Total audit entries appended to the multiparty log.', type: 'counter' },
  hsm_audit_entry_committed_total: { help: 'Total audit entries committed (reached min verifier signatures).', type: 'counter' },
  hsm_audit_entry_pending: { help: 'Number of audit entries currently pending verification.', type: 'gauge' },
  hsm_audit_signature_added_total: { help: 'Total verifier signatures added to audit entries.', type: 'counter' },
  hsm_audit_verification_timeout_total: { help: 'Total audit entries that timed out before reaching quorum.', type: 'counter' },
  hsm_audit_duplicate_signature_total: { help: 'Total duplicate verifier signature attempts rejected.', type: 'counter' },
  hsm_audit_chain_verified_total: { help: 'Total successful full-chain integrity verifications.', type: 'counter' },
  hsm_audit_chain_broken_total: { help: 'Total chain integrity verification failures (tamper detected).', type: 'counter' },
  hsm_audit_verifier_registered_total: { help: 'Total verifiers registered to the audit log.', type: 'counter' },
  hsm_audit_event_type_blocked_total: { help: 'Total audit events rejected due to disallowed event type.', type: 'counter' },
  hsm_audit_committed_entries: { help: 'Number of committed entries in the audit log.', type: 'gauge' },
  // Track 44: Distributed Sharding and Cross-Enclave State Sync
  hsm_cross_enclave_registered_total: { help: 'Total enclaves registered to the cross-enclave sync cluster.', type: 'counter' },
  hsm_cross_enclave_unregistered_total: { help: 'Total enclaves unregistered from the cluster.', type: 'counter' },
  hsm_cross_enclave_stale_detected_total: { help: 'Total enclaves detected as stale and marked offline.', type: 'counter' },
  hsm_cross_enclave_active: { help: 'Number of currently active enclaves in the cluster.', type: 'gauge' },
  hsm_cross_enclave_shard_created_total: { help: 'Total shards created in the cross-enclave sync engine.', type: 'counter' },
  hsm_cross_enclave_shard_reassigned_total: { help: 'Total shard reassignments (after enclave removal or failure).', type: 'counter' },
  hsm_cross_enclave_state_written_total: { help: 'Total state writes across all shards.', type: 'counter' },
  hsm_cross_enclave_state_conflict_total: { help: 'Total state write conflicts detected.', type: 'counter' },
  hsm_cross_enclave_state_too_large_total: { help: 'Total state writes rejected for exceeding size limit.', type: 'counter' },
  hsm_cross_enclave_sync_total: { help: 'Total cross-enclave sync operations.', type: 'counter' },
  hsm_cross_enclave_sync_merged_total: { help: 'Total state entries merged during sync operations.', type: 'counter' },
  hsm_cross_enclave_sync_skipped_total: { help: 'Total state entries skipped during sync (local newer).', type: 'counter' },
  hsm_cross_enclave_shards: { help: 'Number of active shards in the cross-enclave sync engine.', type: 'gauge' },
  // Track 45: Enclave Key Rotation and Cryptographic Heartbeats
  hsm_key_rotation_total: { help: 'Total key rotations performed across all enclaves.', type: 'counter' },
  hsm_key_rotation_blocked_total: { help: 'Total key rotations blocked (quarantined or max epochs reached).', type: 'counter' },
  hsm_key_rotation_skipped_total: { help: 'Total scheduled rotations skipped due to errors.', type: 'counter' },
  hsm_key_revoked_total: { help: 'Total enclave keys revoked.', type: 'counter' },
  hsm_key_quarantined_total: { help: 'Total enclave keys quarantined due to missed heartbeats.', type: 'counter' },
  hsm_key_recovered_total: { help: 'Total enclaves recovered from quarantine via key rotation.', type: 'counter' },
  hsm_heartbeat_issued_total: { help: 'Total heartbeat challenges issued.', type: 'counter' },
  hsm_heartbeat_verified_total: { help: 'Total heartbeat responses successfully verified.', type: 'counter' },
  hsm_heartbeat_expired_total: { help: 'Total heartbeat challenges that expired without response.', type: 'counter' },
  hsm_heartbeat_response_invalid_total: { help: 'Total heartbeat responses that failed HMAC verification.', type: 'counter' },
  hsm_heartbeat_active_keys: { help: 'Number of enclaves with active key status.', type: 'gauge' },
  hsm_heartbeat_quarantined_keys: { help: 'Number of enclaves with quarantined key status.', type: 'gauge' },
  hsm_heartbeat_pending_challenges: { help: 'Number of pending heartbeat challenges awaiting response.', type: 'gauge' },
  // Track 46: Zero-Knowledge Inter-Enclave MPC Handshakes
  hsm_mpc_handshake_initiated_total: { help: 'Total MPC handshakes initiated.', type: 'counter' },
  hsm_mpc_handshake_committed_total: { help: 'Total MPC handshake commitment phases completed (all participants committed).', type: 'counter' },
  hsm_mpc_handshake_proven_total: { help: 'Total MPC handshake proof phases completed (all proofs submitted).', type: 'counter' },
  hsm_mpc_handshake_verified_total: { help: 'Total MPC handshakes where all proofs verified successfully.', type: 'counter' },
  hsm_mpc_handshake_finalized_total: { help: 'Total MPC handshakes finalized with combined public key.', type: 'counter' },
  hsm_mpc_handshake_aborted_total: { help: 'Total MPC handshakes aborted (failed verification or manual abort).', type: 'counter' },
  hsm_mpc_handshake_expired_total: { help: 'Total MPC handshakes that expired before completion.', type: 'counter' },
  hsm_mpc_proof_valid_total: { help: 'Total ZK proofs that passed verification.', type: 'counter' },
  hsm_mpc_proof_invalid_total: { help: 'Total ZK proofs that failed verification.', type: 'counter' },
  hsm_mpc_handshake_active: { help: 'Number of currently active (in-progress) MPC handshakes.', type: 'gauge' },
  // Track 47: Post-Quantum Cryptographic Enclave Migrations
  hsm_pqc_migration_registered_total: { help: 'Total enclaves registered for PQC migration.', type: 'counter' },
  hsm_pqc_migration_planned_total: { help: 'Total PQC migrations planned.', type: 'counter' },
  hsm_pqc_hybrid_activated_total: { help: 'Total enclaves activated in hybrid (classical+PQC) mode.', type: 'counter' },
  hsm_pqc_fully_activated_total: { help: 'Total enclaves fully activated in PQC-only mode.', type: 'counter' },
  hsm_pqc_migration_completed_total: { help: 'Total PQC migrations completed successfully.', type: 'counter' },
  hsm_pqc_migration_rollback_total: { help: 'Total PQC migration rollbacks.', type: 'counter' },
  hsm_pqc_migration_failed_total: { help: 'Total PQC migrations that failed (max attempts reached).', type: 'counter' },
  hsm_pqc_signature_constraint_satisfied_total: { help: 'Total lattice signature constraints satisfied.', type: 'counter' },
  hsm_pqc_signature_constraint_violated_total: { help: 'Total lattice signature constraints violated.', type: 'counter' },
  hsm_pqc_classical_enclaves: { help: 'Number of enclaves still using classical cryptography.', type: 'gauge' },
  hsm_pqc_hybrid_enclaves: { help: 'Number of enclaves in hybrid (classical+PQC) transition mode.', type: 'gauge' },
  hsm_pqc_pqc_enclaves: { help: 'Number of enclaves fully migrated to post-quantum cryptography.', type: 'gauge' },
  // Track 48: Enclave Fault Injection and Byzantine Chaos Testing
  hsm_fault_injected_total: { help: 'Total faults injected into enclaves.', type: 'counter' },
  hsm_fault_resolved_total: { help: 'Total faults resolved (manually or via recovery).', type: 'counter' },
  hsm_fault_expired_total: { help: 'Total faults that expired (duration elapsed).', type: 'counter' },
  hsm_fault_cancelled_total: { help: 'Total faults cancelled manually.', type: 'counter' },
  hsm_fault_byzantine_total: { help: 'Total byzantine faults injected (equivocation, omission, divergence).', type: 'counter' },
  hsm_fault_network_partition_total: { help: 'Total network partition faults injected.', type: 'counter' },
  hsm_fault_crash_total: { help: 'Total enclave crash faults injected.', type: 'counter' },
  hsm_fault_key_corruption_total: { help: 'Total key corruption faults injected.', type: 'counter' },
  hsm_fault_timing_attack_total: { help: 'Total timing attack faults injected.', type: 'counter' },
  hsm_fault_active: { help: 'Number of currently active faults.', type: 'gauge' },
  hsm_fault_scenario_completed_total: { help: 'Total fault scenarios completed successfully.', type: 'counter' },
  hsm_fault_scenario_failed_total: { help: 'Total fault scenarios that failed.', type: 'counter' },
  // Track 49: Dynamic Enclave Rescaling and Predictive Load Balancing
  hsm_rescaling_scale_up_total: { help: 'Total scale-up actions executed.', type: 'counter' },
  hsm_rescaling_scale_down_total: { help: 'Total scale-down actions executed.', type: 'counter' },
  hsm_rescaling_rebalance_total: { help: 'Total shard rebalance actions executed.', type: 'counter' },
  hsm_rescaling_failed_total: { help: 'Total rescaling actions that failed.', type: 'counter' },
  hsm_rescaling_chaos_triggered_total: { help: 'Total rescaling actions triggered by chaos events.', type: 'counter' },
  hsm_rescaling_active_enclaves: { help: 'Number of currently active enclaves in the rescaling cluster.', type: 'gauge' },
  hsm_rescaling_average_load: { help: 'Current average load across all active enclaves (0.0-1.0).', type: 'gauge' },
  hsm_rescaling_predicted_load: { help: 'Predicted average load based on forecasting algorithm (0.0-1.0).', type: 'gauge' },
  hsm_rescaling_imbalance: { help: 'Current load imbalance ratio across enclaves (0.0 = balanced).', type: 'gauge' },
  // Track 50: Confidential Federated Learning and ZK Model Aggregation
  hsm_fl_rounds_initiated_total: { help: 'Total federated learning rounds initiated.', type: 'counter' },
  hsm_fl_rounds_completed_total: { help: 'Total federated learning rounds completed successfully.', type: 'counter' },
  hsm_fl_rounds_failed_total: { help: 'Total federated learning rounds that failed.', type: 'counter' },
  hsm_fl_rounds_expired_total: { help: 'Total federated learning rounds that expired (timeout).', type: 'counter' },
  hsm_fl_gradients_submitted_total: { help: 'Total gradient updates submitted by participants.', type: 'counter' },
  hsm_fl_gradients_verified_total: { help: 'Total gradient updates that passed ZK proof verification.', type: 'counter' },
  hsm_fl_gradients_rejected_total: { help: 'Total gradient updates that failed ZK proof verification.', type: 'counter' },
  hsm_fl_active_rounds: { help: 'Number of currently active federated learning rounds.', type: 'gauge' },
  hsm_fl_global_model_version: { help: 'Current global model version (incremented per completed round).', type: 'gauge' },
  hsm_fl_participants_total: { help: 'Total participant enclaves across all rounds.', type: 'counter' },
  // Track 51: Homomorphic Encryption Over Mesh Topologies
  hsm_he_mesh_nodes_total: { help: 'Total nodes registered in the HE mesh topology.', type: 'gauge' },
  hsm_he_mesh_edges_total: { help: 'Total edges (links) in the HE mesh topology.', type: 'gauge' },
  hsm_he_mesh_active_nodes: { help: 'Number of active nodes in the HE mesh.', type: 'gauge' },
  hsm_he_mesh_queries_created_total: { help: 'Total HE mesh queries created.', type: 'counter' },
  hsm_he_mesh_queries_completed_total: { help: 'Total HE mesh queries completed successfully.', type: 'counter' },
  hsm_he_mesh_queries_failed_total: { help: 'Total HE mesh queries that failed.', type: 'counter' },
  hsm_he_mesh_queries_expired_total: { help: 'Total HE mesh queries that expired (timeout).', type: 'counter' },
  hsm_he_mesh_hops_executed_total: { help: 'Total HE mesh hops executed across all queries.', type: 'counter' },
  hsm_he_mesh_active_queries: { help: 'Number of currently active HE mesh queries.', type: 'gauge' },
  // Track 52: Secure Multi-Party Inner Product and Encrypted Search Indexes
  hsm_sip_indexes_built_total: { help: 'Total blind search indexes built.', type: 'counter' },
  hsm_sip_indexes_active: { help: 'Number of currently active search indexes.', type: 'gauge' },
  hsm_sip_queries_total: { help: 'Total secure inner-product search queries initiated.', type: 'counter' },
  hsm_sip_queries_completed_total: { help: 'Total search queries completed successfully.', type: 'counter' },
  hsm_sip_queries_failed_total: { help: 'Total search queries that failed.', type: 'counter' },
  hsm_sip_parties_total: { help: 'Total parties registered in the secure search cluster.', type: 'gauge' },
  hsm_sip_parties_active: { help: 'Number of currently active parties.', type: 'gauge' },
  hsm_sip_documents_indexed_total: { help: 'Total documents indexed across all indexes.', type: 'counter' },
  hsm_sip_search_results_total: { help: 'Total search results returned across all queries.', type: 'counter' },
  // Track 53: Zero-Knowledge Range Proofs and Auditable Asset Solvency
  hsm_zk_range_proofs_generated_total: { help: 'Total ZK range proofs generated.', type: 'counter' },
  hsm_zk_range_proofs_verified_total: { help: 'Total ZK range proofs verified successfully.', type: 'counter' },
  hsm_zk_range_proofs_invalid_total: { help: 'Total ZK range proofs that failed verification.', type: 'counter' },
  hsm_zk_range_proofs_revoked_total: { help: 'Total ZK range proofs revoked.', type: 'counter' },
  hsm_zk_range_proofs_active: { help: 'Number of currently active ZK range proofs.', type: 'gauge' },
  hsm_zk_batch_proofs_total: { help: 'Total batch range proof operations.', type: 'counter' },
  hsm_zk_solvency_audits_total: { help: 'Total solvency audits initiated.', type: 'counter' },
  hsm_zk_solvency_audits_solvent_total: { help: 'Total solvency audits that concluded solvent.', type: 'counter' },
  hsm_zk_solvency_audits_insolvent_total: { help: 'Total solvency audits that concluded insolvent.', type: 'counter' },
  // Track 54: Multi-Party Threshold Cryptography and Distributed Decryption Circuits
  hsm_tdc_keysets_created_total: { help: 'Total threshold key sets created.', type: 'counter' },
  hsm_tdc_keysets_active: { help: 'Number of currently active threshold key sets.', type: 'gauge' },
  hsm_tdc_circuits_initiated_total: { help: 'Total distributed decryption circuits initiated.', type: 'counter' },
  hsm_tdc_circuits_completed_total: { help: 'Total decryption circuits completed successfully.', type: 'counter' },
  hsm_tdc_circuits_failed_total: { help: 'Total decryption circuits that failed.', type: 'counter' },
  hsm_tdc_circuits_expired_total: { help: 'Total decryption circuits that expired (timeout).', type: 'counter' },
  hsm_tdc_partial_shares_submitted_total: { help: 'Total partial decryption shares submitted.', type: 'counter' },
  hsm_tdc_partial_shares_verified_total: { help: 'Total partial decryption shares verified.', type: 'counter' },
  hsm_tdc_partial_shares_invalid_total: { help: 'Total partial decryption shares that failed verification.', type: 'counter' },
  // Track 55: ZK Verifiable Secret Sharing and Proactive Secret Sharing
  hsm_vss_sessions_total: { help: 'Total VSS sessions initiated.', type: 'counter' },
  hsm_vss_sessions_completed_total: { help: 'Total VSS sessions completed (secret reconstructed).', type: 'counter' },
  hsm_vss_shares_verified_total: { help: 'Total VSS shares verified successfully.', type: 'counter' },
  hsm_vss_shares_invalid_total: { help: 'Total VSS shares that failed verification.', type: 'counter' },
  hsm_vss_complaints_total: { help: 'Total complaints filed in VSS sessions.', type: 'counter' },
  hsm_vss_disqualifications_total: { help: 'Total nodes disqualified from VSS sessions.', type: 'counter' },
  hsm_pss_epochs_total: { help: 'Total PSS epochs started.', type: 'counter' },
  hsm_pss_epochs_active: { help: 'Number of currently active PSS epochs.', type: 'gauge' },
  hsm_pss_refreshes_total: { help: 'Total proactive share refreshes performed.', type: 'counter' },
  hsm_pss_recoveries_total: { help: 'Total share recoveries performed.', type: 'counter' },
  // Track 56: Oblivious RAM and Secure Side-Channel Memory Attenuation
  hsm_oram_blocks_total: { help: 'Total logical blocks stored in ORAM.', type: 'gauge' },
  hsm_oram_reads_total: { help: 'Total ORAM read operations.', type: 'counter' },
  hsm_oram_writes_total: { help: 'Total ORAM write operations.', type: 'counter' },
  hsm_oram_deletes_total: { help: 'Total ORAM delete operations.', type: 'counter' },
  hsm_oram_dummy_accesses_total: { help: 'Total dummy ORAM accesses for pattern obfuscation.', type: 'counter' },
  hsm_oram_stash_size: { help: 'Current ORAM stash size (blocks in temporary buffer).', type: 'gauge' },
  hsm_oram_reshuffles_total: { help: 'Total ORAM stash reshuffles.', type: 'counter' },
  hsm_oram_stash_evictions_total: { help: 'Total blocks evicted from ORAM stash.', type: 'counter' },
  // Track 57: zk-SNARK Enclave Verifiers
  hsm_snark_circuits_compiled_total: { help: 'Total arithmetic circuits compiled.', type: 'counter' },
  hsm_snark_circuits_active: { help: 'Number of active compiled circuits.', type: 'gauge' },
  hsm_snark_setups_generated_total: { help: 'Total trusted setups generated.', type: 'counter' },
  hsm_snark_setups_active: { help: 'Number of active trusted setups.', type: 'gauge' },
  hsm_snark_proofs_generated_total: { help: 'Total zk-SNARK proofs generated.', type: 'counter' },
  hsm_snark_proofs_verified_total: { help: 'Total zk-SNARK proofs verified successfully.', type: 'counter' },
  hsm_snark_proofs_invalid_total: { help: 'Total zk-SNARK proofs that failed verification.', type: 'counter' },
  hsm_snark_proofs_aggregated_total: { help: 'Total proof aggregations performed.', type: 'counter' },
  hsm_snark_setups_destroyed_total: { help: 'Total trusted setups destroyed (toxic waste cleanup).', type: 'counter' },
  // Track 58: Multi-Key FHE Relinearization Engine
  hsm_mfhe_key_pairs_total: { help: 'Total multi-key FHE key pairs generated.', type: 'counter' },
  hsm_mfhe_key_pairs_active: { help: 'Number of active multi-key FHE key pairs.', type: 'gauge' },
  hsm_mfhe_relin_keys_total: { help: 'Total relinearization keys generated.', type: 'counter' },
  hsm_mfhe_encryptions_total: { help: 'Total multi-key FHE encryptions.', type: 'counter' },
  hsm_mfhe_decryptions_total: { help: 'Total multi-key FHE decryptions.', type: 'counter' },
  hsm_mfhe_homomorphic_ops_total: { help: 'Total homomorphic operations performed.', type: 'counter' },
  hsm_mfhe_relinearizations_total: { help: 'Total relinearization operations performed.', type: 'counter' },
  hsm_mfhe_key_switches_total: { help: 'Total key switching operations performed.', type: 'counter' },
  hsm_mfhe_bootstraps_total: { help: 'Total bootstrapping operations performed.', type: 'counter' },
  // Track 59: VDF and Time-Locked Enclave Puzzles
  hsm_vdf_created_total: { help: 'Total VDF instances created.', type: 'counter' },
  hsm_vdf_evaluated_total: { help: 'Total VDF evaluations completed.', type: 'counter' },
  hsm_vdf_verified_total: { help: 'Total VDF proofs verified.', type: 'counter' },
  hsm_vdf_active: { help: 'Number of active VDF instances.', type: 'gauge' },
  hsm_puzzles_created_total: { help: 'Total time-locked puzzles created.', type: 'counter' },
  hsm_puzzles_solved_total: { help: 'Total time-locked puzzles solved.', type: 'counter' },
  hsm_puzzles_expired_total: { help: 'Total time-locked puzzles expired.', type: 'counter' },
  hsm_puzzles_active: { help: 'Number of active time-locked puzzles.', type: 'gauge' },
  // Track 60: Multi-Asset Sharded Mixnets and Blind Confidential Transactions
  hsm_mixnet_nodes_total: { help: 'Total mixnet nodes registered.', type: 'counter' },
  hsm_mixnet_nodes_active: { help: 'Number of active mixnet nodes.', type: 'gauge' },
  hsm_mixnet_shards_total: { help: 'Number of mixnet shards.', type: 'gauge' },
  hsm_mixnet_transactions_created_total: { help: 'Total blind transactions created.', type: 'counter' },
  hsm_mixnet_transactions_mixed_total: { help: 'Total transactions mixed through the mixnet.', type: 'counter' },
  hsm_mixnet_transactions_confirmed_total: { help: 'Total transactions confirmed.', type: 'counter' },
  hsm_mixnet_pools_shuffled_total: { help: 'Total pools shuffled.', type: 'counter' },
  hsm_mixnet_pools_flushed_total: { help: 'Total pools flushed.', type: 'counter' },
  hsm_mixnet_relays_total: { help: 'Total relay hops processed.', type: 'counter' },
  // Track 61: Recursive Proof Aggregation Engine
  hsm_rpa_proofs_submitted_total: { help: 'Total proofs submitted for aggregation.', type: 'counter' },
  hsm_rpa_proofs_folded_total: { help: 'Total proof folding operations performed.', type: 'counter' },
  hsm_rpa_chain_aggregations_total: { help: 'Total chain aggregations performed.', type: 'counter' },
  hsm_rpa_tree_aggregations_total: { help: 'Total tree aggregations performed.', type: 'counter' },
  hsm_rpa_vdf_aggregations_total: { help: 'Total VDF proof aggregations performed.', type: 'counter' },
  hsm_rpa_mixnet_compressions_total: { help: 'Total mixnet state compressions performed.', type: 'counter' },
  hsm_rpa_aggregations_verified_total: { help: 'Total aggregations verified.', type: 'counter' },
  hsm_rpa_active_proofs: { help: 'Number of active proofs in the aggregation pool.', type: 'gauge' },
  // Track 62: PQC Time-Locked Matrix Routing and Temporal Validity Verification
  hsm_ptlm_matrices_initialized_total: { help: 'Total time-locked matrices initialized.', type: 'counter' },
  hsm_ptlm_matrices_routed_total: { help: 'Total matrices routed through time-lock nodes.', type: 'counter' },
  hsm_ptlm_matrices_released_total: { help: 'Total matrices released after temporal verification.', type: 'counter' },
  hsm_ptlm_matrices_expired_total: { help: 'Total matrices expired.', type: 'counter' },
  hsm_ptlm_matrices_active: { help: 'Number of active time-locked matrices.', type: 'gauge' },
  hsm_ptlm_routing_nodes_total: { help: 'Total routing nodes registered.', type: 'counter' },
  hsm_ptlm_lattice_keys_generated_total: { help: 'Total lattice key pairs generated.', type: 'counter' },
  hsm_ptlm_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations.', type: 'counter' },
  hsm_ptlm_temporal_proofs_verified_total: { help: 'Total temporal proofs verified.', type: 'counter' },
  hsm_ptlm_temporal_proofs_slashed_total: { help: 'Total temporal proofs slashed.', type: 'counter' },
  hsm_ptlm_batch_verifications_total: { help: 'Total batch verifications performed.', type: 'counter' },
  hsm_ptlm_banned_peers: { help: 'Number of banned peers.', type: 'gauge' },
  // Track 63: PQC Blind Option Pools & HW-SNARK VDF Aggregators
  hsm_bop_pools_initialized_total: { help: 'Total blind option pools initialized.', type: 'counter' },
  hsm_bop_pools_executed_total: { help: 'Total option contracts executed.', type: 'counter' },
  hsm_bop_pools_settled_total: { help: 'Total option contracts settled cross-chain.', type: 'counter' },
  hsm_bop_pools_expired_total: { help: 'Total option pools expired.', type: 'counter' },
  hsm_bop_pools_cancelled_total: { help: 'Total option pools cancelled.', type: 'counter' },
  hsm_bop_pools_active: { help: 'Number of active blind option pools.', type: 'gauge' },
  hsm_bop_batch_inits_total: { help: 'Total batch pool initializations.', type: 'counter' },
  hsm_bop_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations.', type: 'counter' },
  hsm_bop_margin_proofs_verified_total: { help: 'Total margin adequacy proofs verified.', type: 'counter' },
  hsm_bop_margin_proofs_slashed_total: { help: 'Total margin adequacy proofs slashed.', type: 'counter' },
  hsm_bop_batch_verifications_total: { help: 'Total batch margin verifications performed.', type: 'counter' },
  hsm_bop_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated.', type: 'counter' },
  hsm_bop_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified.', type: 'counter' },
  hsm_bop_banned_peers: { help: 'Number of banned peers in option pool hub.', type: 'gauge' },
  // Track 64: PQC Prediction Markets & ZK Resolution Validators
  hsm_predmkt_markets_initialized_total: { help: 'Total prediction markets initialized.', type: 'counter' },
  hsm_predmkt_markets_finalized_total: { help: 'Total prediction markets finalized.', type: 'counter' },
  hsm_predmkt_markets_settled_total: { help: 'Total prediction markets settled cross-chain.', type: 'counter' },
  hsm_predmkt_markets_disputed_total: { help: 'Total prediction markets escalated to dispute resolution.', type: 'counter' },
  hsm_predmkt_markets_cancelled_total: { help: 'Total prediction markets cancelled.', type: 'counter' },
  hsm_predmkt_markets_expired_total: { help: 'Total prediction markets expired.', type: 'counter' },
  hsm_predmkt_markets_active: { help: 'Number of active prediction markets.', type: 'gauge' },
  hsm_predmkt_batch_inits_total: { help: 'Total batch market initializations.', type: 'counter' },
  hsm_predmkt_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for markets.', type: 'counter' },
  hsm_predmkt_resolution_votes_recorded_total: { help: 'Total resolution votes recorded.', type: 'counter' },
  hsm_predmkt_resolution_votes_slashed_total: { help: 'Total resolution votes slashed.', type: 'counter' },
  hsm_predmkt_batch_verifications_total: { help: 'Total batch vote verifications performed.', type: 'counter' },
  hsm_predmkt_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for market resolution.', type: 'counter' },
  hsm_predmkt_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for market resolution.', type: 'counter' },
  hsm_predmkt_banned_peers: { help: 'Number of banned peers in prediction market hub.', type: 'gauge' },
  // Track 65: PQC Fractional Custody & ZK Release Verifiers
  hsm_fracvault_vaults_initialized_total: { help: 'Total fractional custody vaults initialized.', type: 'counter' },
  hsm_fracvault_vaults_liquidated_total: { help: 'Total fractional custody vaults liquidated.', type: 'counter' },
  hsm_fracvault_vaults_settled_total: { help: 'Total fractional custody vaults settled cross-chain.', type: 'counter' },
  hsm_fracvault_vaults_cancelled_total: { help: 'Total fractional custody vaults cancelled.', type: 'counter' },
  hsm_fracvault_vaults_active: { help: 'Number of active fractional custody vaults.', type: 'gauge' },
  hsm_fracvault_escrows_locked_total: { help: 'Total escrow locks created.', type: 'counter' },
  hsm_fracvault_escrows_released_total: { help: 'Total escrow locks released.', type: 'counter' },
  hsm_fracvault_batch_inits_total: { help: 'Total batch vault initializations.', type: 'counter' },
  hsm_fracvault_committee_signatures_aggregated_total: { help: 'Total custodian committee signature aggregations.', type: 'counter' },
  hsm_fracvault_releases_recorded_total: { help: 'Total fractional releases recorded.', type: 'counter' },
  hsm_fracvault_releases_slashed_total: { help: 'Total fractional releases slashed.', type: 'counter' },
  hsm_fracvault_batch_verifications_total: { help: 'Total batch release verifications performed.', type: 'counter' },
  hsm_fracvault_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for fractional releases.', type: 'counter' },
  hsm_fracvault_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for fractional releases.', type: 'counter' },
  hsm_fracvault_banned_peers: { help: 'Number of banned peers in fractional custody hub.', type: 'gauge' },
  // Track 66: PQC Lending Collateral & ZK Solvency Proof Processors
  hsm_lendpool_pools_initialized_total: { help: 'Total lending collateral pools initialized.', type: 'counter' },
  hsm_lendpool_pools_liquidated_total: { help: 'Total lending collateral pools liquidated.', type: 'counter' },
  hsm_lendpool_pools_settled_total: { help: 'Total lending collateral pools settled cross-chain.', type: 'counter' },
  hsm_lendpool_pools_cancelled_total: { help: 'Total lending collateral pools cancelled.', type: 'counter' },
  hsm_lendpool_pools_active: { help: 'Number of active lending collateral pools.', type: 'gauge' },
  hsm_lendpool_rebalances_total: { help: 'Total collateral rebalances performed.', type: 'counter' },
  hsm_lendpool_batch_inits_total: { help: 'Total batch pool initializations.', type: 'counter' },
  hsm_lendpool_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for lending pools.', type: 'counter' },
  hsm_lendpool_solvency_proofs_verified_total: { help: 'Total ZK solvency proofs verified.', type: 'counter' },
  hsm_lendpool_solvency_proofs_slashed_total: { help: 'Total ZK solvency proofs slashed.', type: 'counter' },
  hsm_lendpool_batch_verifications_total: { help: 'Total batch solvency proof verifications performed.', type: 'counter' },
  hsm_lendpool_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for solvency.', type: 'counter' },
  hsm_lendpool_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for solvency.', type: 'counter' },
  hsm_lendpool_banned_peers: { help: 'Number of banned peers in lending collateral hub.', type: 'gauge' },
  // Track 67: PQC Insurance Underwriting & ZK Risk Exposure Validators
  hsm_inspault_pools_initialized_total: { help: 'Total insurance underwriting pools initialized.', type: 'counter' },
  hsm_inspault_pools_liquidated_total: { help: 'Total insurance underwriting pools liquidated.', type: 'counter' },
  hsm_inspault_pools_settled_total: { help: 'Total insurance underwriting pools settled cross-chain.', type: 'counter' },
  hsm_inspault_pools_cancelled_total: { help: 'Total insurance underwriting pools cancelled.', type: 'counter' },
  hsm_inspault_pools_active: { help: 'Number of active insurance underwriting pools.', type: 'gauge' },
  hsm_inspault_rebalances_total: { help: 'Total risk exposure rebalances performed.', type: 'counter' },
  hsm_inspault_batch_inits_total: { help: 'Total batch pool initializations for insurance underwriting.', type: 'counter' },
  hsm_inspault_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for insurance pools.', type: 'counter' },
  hsm_inspault_claims_verified_total: { help: 'Total ZK claim eligibility proofs verified.', type: 'counter' },
  hsm_inspault_claims_slashed_total: { help: 'Total ZK claim eligibility proofs slashed.', type: 'counter' },
  hsm_inspault_batch_verifications_total: { help: 'Total batch claim verifications performed.', type: 'counter' },
  hsm_inspault_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for risk exposure.', type: 'counter' },
  hsm_inspault_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for risk exposure.', type: 'counter' },
  hsm_inspault_banned_peers: { help: 'Number of banned peers in insurance underwriting hub.', type: 'gauge' },
  // Track 68: PQC Supply Chain Escrow & ZK Order Milestone Validators
  hsm_scordr_orders_initialized_total: { help: 'Total supply chain orders initialized.', type: 'counter' },
  hsm_scordr_orders_released_total: { help: 'Total supply chain escrow releases.', type: 'counter' },
  hsm_scordr_orders_settled_total: { help: 'Total supply chain orders settled cross-chain.', type: 'counter' },
  hsm_scordr_orders_cancelled_total: { help: 'Total supply chain orders cancelled.', type: 'counter' },
  hsm_scordr_orders_active: { help: 'Number of active supply chain orders.', type: 'gauge' },
  hsm_scordr_rebalances_total: { help: 'Total delivery epoch rebalances performed.', type: 'counter' },
  hsm_scordr_batch_inits_total: { help: 'Total batch order initializations for supply chain.', type: 'counter' },
  hsm_scordr_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for supply chain orders.', type: 'counter' },
  hsm_scordr_milestones_verified_total: { help: 'Total ZK delivery milestone proofs verified.', type: 'counter' },
  hsm_scordr_milestones_slashed_total: { help: 'Total ZK delivery milestone proofs slashed.', type: 'counter' },
  hsm_scordr_batch_verifications_total: { help: 'Total batch milestone verifications performed.', type: 'counter' },
  hsm_scordr_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for milestones.', type: 'counter' },
  hsm_scordr_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for milestones.', type: 'counter' },
  hsm_scordr_banned_peers: { help: 'Number of banned peers in supply chain escrow hub.', type: 'gauge' },
  // Track 69: PQC Real Estate Tokenization & ZK Title Deed Validators
  hsm_repools_pools_initialized_total: { help: 'Total real estate tokenization pools initialized.', type: 'counter' },
  hsm_repools_pools_finalized_total: { help: 'Total title deed transfers finalized.', type: 'counter' },
  hsm_repools_pools_settled_total: { help: 'Total real estate pools settled cross-chain.', type: 'counter' },
  hsm_repools_pools_cancelled_total: { help: 'Total real estate pools cancelled.', type: 'counter' },
  hsm_repools_pools_active: { help: 'Number of active real estate tokenization pools.', type: 'gauge' },
  hsm_repools_rebalances_total: { help: 'Total valuation rebalances performed.', type: 'counter' },
  hsm_repools_batch_inits_total: { help: 'Total batch pool initializations for real estate.', type: 'counter' },
  hsm_repools_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for real estate pools.', type: 'counter' },
  hsm_repools_clearances_verified_total: { help: 'Total ZK encumbrance clearance proofs verified.', type: 'counter' },
  hsm_repools_clearances_slashed_total: { help: 'Total ZK encumbrance clearance proofs slashed.', type: 'counter' },
  hsm_repools_batch_verifications_total: { help: 'Total batch clearance verifications performed.', type: 'counter' },
  hsm_repools_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for clearances.', type: 'counter' },
  hsm_repools_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for clearances.', type: 'counter' },
  hsm_repools_banned_peers: { help: 'Number of banned peers in real estate tokenization hub.', type: 'gauge' },
  // Track 70: PQC Carbon Credit Tokenization & ZK Carbon Retirement Validators
  hsm_carpools_pools_initialized_total: { help: 'Total carbon credit tokenization pools initialized.', type: 'counter' },
  hsm_carpools_pools_retired_total: { help: 'Total carbon credit retirements finalized.', type: 'counter' },
  hsm_carpools_pools_settled_total: { help: 'Total carbon credit pools settled cross-chain.', type: 'counter' },
  hsm_carpools_pools_cancelled_total: { help: 'Total carbon credit pools cancelled.', type: 'counter' },
  hsm_carpools_pools_active: { help: 'Number of active carbon credit tokenization pools.', type: 'gauge' },
  hsm_carpools_rebalances_total: { help: 'Total tonnage rebalances performed.', type: 'counter' },
  hsm_carpools_batch_inits_total: { help: 'Total batch pool initializations for carbon credit.', type: 'counter' },
  hsm_carpools_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for carbon pools.', type: 'counter' },
  hsm_carpools_retirements_verified_total: { help: 'Total ZK retirement proofs verified.', type: 'counter' },
  hsm_carpools_retirements_slashed_total: { help: 'Total ZK retirement proofs slashed.', type: 'counter' },
  hsm_carpools_batch_verifications_total: { help: 'Total batch retirement verifications performed.', type: 'counter' },
  hsm_carpools_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for retirements.', type: 'counter' },
  hsm_carpools_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for retirements.', type: 'counter' },
  hsm_carpools_banned_peers: { help: 'Number of banned peers in carbon credit tokenization hub.', type: 'gauge' },
  // Track 71: PQC Identity Gating & ZK Identity Gating Validators
  hsm_idgate_pools_initialized_total: { help: 'Total identity gating pools initialized.', type: 'counter' },
  hsm_idgate_pools_completed_total: { help: 'Total sovereign identity gating completions finalized.', type: 'counter' },
  hsm_idgate_pools_settled_total: { help: 'Total identity gating pools settled cross-chain.', type: 'counter' },
  hsm_idgate_pools_cancelled_total: { help: 'Total identity gating pools cancelled.', type: 'counter' },
  hsm_idgate_pools_active: { help: 'Number of active identity gating pools.', type: 'gauge' },
  hsm_idgate_rebalances_total: { help: 'Total credential depth rebalances performed.', type: 'counter' },
  hsm_idgate_batch_inits_total: { help: 'Total batch pool initializations for identity gating.', type: 'counter' },
  hsm_idgate_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for identity gating pools.', type: 'counter' },
  hsm_idgate_claims_verified_total: { help: 'Total ZK attribute claim proofs verified.', type: 'counter' },
  hsm_idgate_claims_slashed_total: { help: 'Total ZK attribute claim proofs slashed.', type: 'counter' },
  hsm_idgate_batch_verifications_total: { help: 'Total batch attribute claim verifications performed.', type: 'counter' },
  hsm_idgate_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for attribute claims.', type: 'counter' },
  hsm_idgate_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for attribute claims.', type: 'counter' },
  hsm_idgate_banned_peers: { help: 'Number of banned peers in identity gating hub.', type: 'gauge' },
  // Track 72: PQC Health Data Gating & ZK Health Attribute Validators
  hsm_hgate_pools_initialized_total: { help: 'Total health data gating pools initialized.', type: 'counter' },
  hsm_hgate_pools_completed_total: { help: 'Total health record gating completions finalized.', type: 'counter' },
  hsm_hgate_pools_settled_total: { help: 'Total health data gating pools settled cross-chain.', type: 'counter' },
  hsm_hgate_pools_cancelled_total: { help: 'Total health data gating pools cancelled.', type: 'counter' },
  hsm_hgate_pools_active: { help: 'Number of active health data gating pools.', type: 'gauge' },
  hsm_hgate_rebalances_total: { help: 'Total diagnostic observation depth rebalances performed.', type: 'counter' },
  hsm_hgate_batch_inits_total: { help: 'Total batch pool initializations for health data gating.', type: 'counter' },
  hsm_hgate_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for health gating pools.', type: 'counter' },
  hsm_hgate_claims_verified_total: { help: 'Total ZK health claim proofs verified.', type: 'counter' },
  hsm_hgate_claims_slashed_total: { help: 'Total ZK health claim proofs slashed.', type: 'counter' },
  hsm_hgate_batch_verifications_total: { help: 'Total batch health claim verifications performed.', type: 'counter' },
  hsm_hgate_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for health claims.', type: 'counter' },
  hsm_hgate_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for health claims.', type: 'counter' },
  hsm_hgate_banned_peers: { help: 'Number of banned peers in health data gating hub.', type: 'gauge' },
  // Track 73: PQC Education Credential Gating & ZK Academic Credential Validators
  hsm_edugate_pools_initialized_total: { help: 'Total education credential gating pools initialized.', type: 'counter' },
  hsm_edugate_pools_accredited_total: { help: 'Total credential accreditation completions finalized.', type: 'counter' },
  hsm_edugate_pools_settled_total: { help: 'Total education credential gating pools settled cross-chain.', type: 'counter' },
  hsm_edugate_pools_cancelled_total: { help: 'Total education credential gating pools cancelled.', type: 'counter' },
  hsm_edugate_pools_active: { help: 'Number of active education credential gating pools.', type: 'gauge' },
  hsm_edugate_rebalances_total: { help: 'Total credential depth rebalances performed.', type: 'counter' },
  hsm_edugate_batch_inits_total: { help: 'Total batch pool initializations for education credential gating.', type: 'counter' },
  hsm_edugate_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for education gating pools.', type: 'counter' },
  hsm_edugate_claims_verified_total: { help: 'Total ZK academic claim proofs verified.', type: 'counter' },
  hsm_edugate_claims_slashed_total: { help: 'Total ZK academic claim proofs slashed.', type: 'counter' },
  hsm_edugate_batch_verifications_total: { help: 'Total batch academic claim verifications performed.', type: 'counter' },
  hsm_edugate_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for academic claims.', type: 'counter' },
  hsm_edugate_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for academic claims.', type: 'counter' },
  hsm_edugate_banned_peers: { help: 'Number of banned peers in education credential gating hub.', type: 'gauge' },
  // Track 74 Phase 2: PQC Patent Verification Gating & ZK Patent Claim Validators
  hsm_pgate_pools_initialized_total: { help: 'Total patent verification gating pools initialized.', type: 'counter' },
  hsm_pgate_pools_accredited_total: { help: 'Total patent license accreditation completions finalized.', type: 'counter' },
  hsm_pgate_pools_settled_total: { help: 'Total patent verification gating pools settled cross-chain.', type: 'counter' },
  hsm_pgate_pools_cancelled_total: { help: 'Total patent verification gating pools cancelled.', type: 'counter' },
  hsm_pgate_pools_active: { help: 'Number of active patent verification gating pools.', type: 'gauge' },
  hsm_pgate_rebalances_total: { help: 'Total claim scope depth rebalances performed.', type: 'counter' },
  hsm_pgate_batch_inits_total: { help: 'Total batch pool initializations for patent verification gating.', type: 'counter' },
  hsm_pgate_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for patent gating pools.', type: 'counter' },
  hsm_pgate_claims_verified_total: { help: 'Total ZK patent claim proofs verified.', type: 'counter' },
  hsm_pgate_claims_slashed_total: { help: 'Total ZK patent claim proofs slashed.', type: 'counter' },
  hsm_pgate_batch_verifications_total: { help: 'Total batch patent claim verifications performed.', type: 'counter' },
  hsm_pgate_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for patent claims.', type: 'counter' },
  hsm_pgate_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for patent claims.', type: 'counter' },
  hsm_pgate_banned_peers: { help: 'Number of banned peers in patent verification gating hub.', type: 'gauge' },
  // Track 76 Phase 2: PQC Supply Chain Provenance Gating & ZK Provenance Claim Validators
  hsm_sgate_pools_initialized_total: { help: 'Total supply chain provenance gating pools initialized.', type: 'counter' },
  hsm_sgate_pools_accredited_total: { help: 'Total component lineage accreditation completions finalized.', type: 'counter' },
  hsm_sgate_pools_settled_total: { help: 'Total supply chain provenance gating pools settled cross-chain.', type: 'counter' },
  hsm_sgate_pools_cancelled_total: { help: 'Total supply chain provenance gating pools cancelled.', type: 'counter' },
  hsm_sgate_pools_active: { help: 'Number of active supply chain provenance gating pools.', type: 'gauge' },
  hsm_sgate_rebalances_total: { help: 'Total component lineage depth rebalances performed.', type: 'counter' },
  hsm_sgate_batch_inits_total: { help: 'Total batch pool initializations for supply chain provenance gating.', type: 'counter' },
  hsm_sgate_committee_signatures_aggregated_total: { help: 'Total committee signature aggregations for supply chain gating pools.', type: 'counter' },
  hsm_sgate_claims_verified_total: { help: 'Total ZK provenance claim proofs verified.', type: 'counter' },
  hsm_sgate_claims_slashed_total: { help: 'Total ZK provenance claim proofs slashed.', type: 'counter' },
  hsm_sgate_batch_verifications_total: { help: 'Total batch provenance claim verifications performed.', type: 'counter' },
  hsm_sgate_hw_snark_proofs_generated_total: { help: 'Total hardware-accelerated SNARK proofs generated for provenance claims.', type: 'counter' },
  hsm_sgate_hw_snark_proofs_verified_total: { help: 'Total hardware-accelerated SNARK proofs verified for provenance claims.', type: 'counter' },
  hsm_sgate_banned_peers: { help: 'Number of banned peers in supply chain provenance gating hub.', type: 'gauge' },
  hsm_dkg_rounds_started_total: { help: 'Total DKG protocol rounds initiated.', type: 'counter' },
  hsm_dkg_rounds_completed_total: { help: 'Total DKG protocol rounds that completed successfully.', type: 'counter' },
  hsm_dkg_shares_verified_total: { help: 'Total DKG shares that passed commitment verification.', type: 'counter' },
  hsm_dkg_shares_rejected_total: { help: 'Total DKG shares that failed commitment verification.', type: 'counter' },
  hsm_dkg_complaints_filed_total: { help: 'Total DKG complaints filed by nodes against peers.', type: 'counter' },
  hsm_dkg_nodes_disqualified_total: { help: 'Total DKG nodes disqualified due to verified complaints.', type: 'counter' },
  hsm_dkg_zk_proofs_generated_total: { help: 'Total zk-SNARK validation parameters generated.', type: 'counter' },
  hsm_dkg_zk_proofs_invalid_total: { help: 'Total zk-SNARK validation parameters rejected as invalid or forged.', type: 'counter' },
  hsm_pqc_threshold_sign_total: { help: 'Total PQC threshold signature aggregation operations.', type: 'counter' },
  hsm_pqc_threshold_sign_failures_total: { help: 'Total PQC threshold signature aggregations that failed.', type: 'counter' },
  hsm_pqc_threshold_partial_sign_total: { help: 'Total PQC partial signature generation operations.', type: 'counter' },
  hsm_pqc_threshold_partial_verified_total: { help: 'Total PQC partial signatures that passed verification.', type: 'counter' },
  hsm_pqc_threshold_partial_rejected_total: { help: 'Total PQC partial signatures that failed verification.', type: 'counter' },
  hsm_pqc_threshold_verify_total: { help: 'Total PQC threshold signature verification operations.', type: 'counter' },
  hsm_pqc_threshold_verify_failures_total: { help: 'Total PQC threshold signature verifications that failed.', type: 'counter' },
  hsm_sandbox_created_total: { help: 'Total confidential sandboxes created.', type: 'counter' },
  hsm_sandbox_destroyed_total: { help: 'Total confidential sandboxes destroyed.', type: 'counter' },
  hsm_sandbox_attested_total: { help: 'Total sandbox attestations that passed.', type: 'counter' },
  hsm_sandbox_attestation_failed_total: { help: 'Total sandbox attestations that failed.', type: 'counter' },
  hsm_sandbox_execute_total: { help: 'Total sandbox execute operations.', type: 'counter' },
  hsm_sandbox_execute_failures_total: { help: 'Total sandbox execute operations that failed.', type: 'counter' },
  hsm_sandbox_zeroized_total: { help: 'Total sandbox zeroization operations.', type: 'counter' },
  hsm_sandbox_active: { help: 'Current number of active sandboxes.', type: 'gauge' },
  hsm_shard_append_total: { help: 'Total shard entries appended.', type: 'counter' },
  hsm_shard_ack_total: { help: 'Total shard entry acknowledgments received.', type: 'counter' },
  hsm_shard_commit_total: { help: 'Total shard entries committed via quorum.', type: 'counter' },
  hsm_shard_catchup_batch_total: { help: 'Total catch-up batches streamed to lagging nodes.', type: 'counter' },
  hsm_shard_byzantine_detected_total: { help: 'Total nodes flagged as byzantine due to divergence.', type: 'counter' },
  hsm_shard_lagging_nodes: { help: 'Current number of lagging nodes across all shards.', type: 'gauge' },
  hsm_shard_active: { help: 'Current number of active shards being tracked.', type: 'gauge' },
  hsm_migration_initiated_total: { help: 'Total cross-cluster migrations initiated.', type: 'counter' },
  hsm_migration_attested_total: { help: 'Total cross-cluster migrations attested.', type: 'counter' },
  hsm_migration_committed_total: { help: 'Total cross-cluster migrations committed via quorum.', type: 'counter' },
  hsm_migration_rolled_back_total: { help: 'Total cross-cluster migrations rolled back.', type: 'counter' },
  hsm_migration_ack_total: { help: 'Total migration acknowledgments received from destination nodes.', type: 'counter' },
  hsm_migration_verification_failed_total: { help: 'Total migrations that failed verification.', type: 'counter' },
  hsm_migration_active: { help: 'Current number of active (in-progress) migrations.', type: 'gauge' },
  hsm_reconciliation_scans_total: { help: 'Total key reconciliation scans performed.', type: 'counter' },
  hsm_reconciliation_divergence_detected_total: { help: 'Total key divergences detected across scans.', type: 'counter' },
  hsm_reconciliation_promoted_total: { help: 'Total key epochs promoted via quorum.', type: 'counter' },
  hsm_reconciliation_quarantined_total: { help: 'Total keys quarantined due to unrecoverable divergence.', type: 'counter' },
  hsm_reconciliation_rollback_blocked_total: { help: 'Total key epoch rollback attempts blocked.', type: 'counter' },
  hsm_reconciliation_promotion_votes_total: { help: 'Total promotion votes cast by healthy nodes.', type: 'counter' },
  hsm_reconciliation_divergent_keys: { help: 'Current number of keys with unresolved divergence.', type: 'gauge' },
  hsm_poa_asset_registered_total: { help: 'Total assets registered for proof-of-assets.', type: 'counter' },
  hsm_poa_proof_created_total: { help: 'Total ZK proof-of-assets drafts created.', type: 'counter' },
  hsm_poa_proof_verified_total: { help: 'Total ZK proof-of-assets successfully verified.', type: 'counter' },
  hsm_poa_proof_invalid_total: { help: 'Total ZK proof-of-assets marked invalid.', type: 'counter' },
  hsm_poa_double_count_blocked_total: { help: 'Total asset double-counting attempts blocked.', type: 'counter' },
  hsm_poa_quorum_signatures_total: { help: 'Total quorum signatures collected on proofs.', type: 'counter' },
  hsm_poa_active_proofs: { help: 'Current number of active (non-terminal) proofs.', type: 'gauge' },
  hsm_rekey_proposed_total: { help: 'Total re-keying rounds proposed.', type: 'counter' },
  hsm_rekey_resharing_submitted_total: { help: 'Total shareholder resharings submitted.', type: 'counter' },
  hsm_rekey_verified_total: { help: 'Total re-keying rounds verified.', type: 'counter' },
  hsm_rekey_committed_total: { help: 'Total re-keying rounds committed via quorum.', type: 'counter' },
  hsm_rekey_aborted_total: { help: 'Total re-keying rounds aborted.', type: 'counter' },
  hsm_rekey_rollback_blocked_total: { help: 'Total re-keying epoch rollback attempts blocked.', type: 'counter' },
  hsm_rekey_active: { help: 'Current number of active (in-progress) re-keying rounds.', type: 'gauge' },
  hsm_p2p_route_discovered_total: { help: 'Total P2P routes discovered via BFS.', type: 'counter' },
  hsm_p2p_message_encrypted_total: { help: 'Total P2P messages encrypted with onion layers.', type: 'counter' },
  hsm_p2p_message_relayed_total: { help: 'Total P2P messages relayed through hops.', type: 'counter' },
  hsm_p2p_message_delivered_total: { help: 'Total P2P messages successfully delivered.', type: 'counter' },
  hsm_p2p_route_revoked_total: { help: 'Total P2P routes revoked.', type: 'counter' },
  hsm_p2p_replay_blocked_total: { help: 'Total P2P replay attacks blocked.', type: 'counter' },
  hsm_p2p_active_routes: { help: 'Current number of active P2P routes.', type: 'gauge' },
  hsm_recovery_requested_total: { help: 'Total account recovery requests initiated.', type: 'counter' },
  hsm_recovery_approved_total: { help: 'Total guardian approvals submitted.', type: 'counter' },
  hsm_recovery_executed_total: { help: 'Total account recoveries successfully executed.', type: 'counter' },
  hsm_recovery_rejected_total: { help: 'Total account recovery requests rejected.', type: 'counter' },
  hsm_recovery_replay_blocked_total: { help: 'Total replay attacks blocked during recovery.', type: 'counter' },
  hsm_recovery_time_lock_blocked_total: { help: 'Total recovery attempts blocked by time-lock.', type: 'counter' },
  hsm_recovery_active: { help: 'Current number of active (in-progress) account recoveries.', type: 'gauge' },
  hsm_wrap_duration_ms: { help: 'Latency of HSM wrapKey operations in milliseconds.', type: 'histogram' },
  hsm_unwrap_duration_ms: { help: 'Latency of HSM unwrapKey operations in milliseconds.', type: 'histogram' },
  hsm_create_kek_duration_ms: { help: 'Latency of KEK creation operations in milliseconds.', type: 'histogram' },
};

/**
 * Increment a counter.
 * @param {string} name - counter name
 * @param {number} [value=1] - increment amount
 */
function incrementCounter(name, value = 1) {
  if (counters[name] !== undefined) {
    counters[name] += value;
  }
}

/**
 * Observe a latency value in a histogram.
 * @param {string} name - histogram name
 * @param {number} durationMs - observed duration in milliseconds
 */
function observeHistogram(name, durationMs) {
  const h = histograms[name];
  if (!h) return;
  h.sum += durationMs;
  h.count++;
  for (let i = 0; i < h.buckets.length; i++) {
    if (durationMs <= h.buckets[i]) {
      h.counts[i]++;
      return;
    }
  }
  // Overflow bucket (+Inf)
  h.counts[h.counts.length - 1]++;
}

/**
 * Reset all metrics to zero. Primarily for testing.
 */
function reset() {
  for (const key of Object.keys(counters)) {
    counters[key] = 0;
  }
  for (const key of Object.keys(histograms)) {
    histograms[key].counts.fill(0);
    histograms[key].sum = 0;
    histograms[key].count = 0;
  }
}

/**
 * Get all metrics as a flat object (for programmatic access).
 * @returns {object} metric name -> value
 */
function getMetrics() {
  const result = { ...counters };
  for (const [name, h] of Object.entries(histograms)) {
    result[`${name}_count`] = h.count;
    result[`${name}_sum`] = h.sum;
    for (let i = 0; i < h.buckets.length; i++) {
      result[`${name}_bucket{le="${h.buckets[i]}"}`] = h.counts[i];
    }
    result[`${name}_bucket{le="+Inf"}`] = h.count;
  }
  return result;
}

/**
 * Render metrics in Prometheus exposition format.
 * @returns {string} Prometheus text format
 */
function renderPrometheus() {
  const lines = [];

  // Counters
  for (const [name, value] of Object.entries(counters)) {
    const meta = META[name];
    if (!meta) continue;
    lines.push(`# HELP ${name} ${meta.help}`);
    lines.push(`# TYPE ${name} ${meta.type}`);
    lines.push(`${name} ${value}`);
  }

  // Histograms
  for (const [name, h] of Object.entries(histograms)) {
    const meta = META[name];
    if (!meta) continue;
    lines.push(`# HELP ${name} ${meta.help}`);
    lines.push(`# TYPE ${name} ${meta.type}`);
    // Cumulative bucket counts
    let cumulative = 0;
    for (let i = 0; i < h.buckets.length; i++) {
      cumulative += h.counts[i];
      lines.push(`${name}_bucket{le="${h.buckets[i]}"} ${cumulative}`);
    }
    cumulative += h.counts[h.counts.length - 1];
    lines.push(`${name}_bucket{le="+Inf"} ${cumulative}`);
    lines.push(`${name}_sum ${h.sum}`);
    lines.push(`${name}_count ${h.count}`);
  }

  return lines.join('\n') + '\n';
}

module.exports = {
  incrementCounter,
  observeHistogram,
  reset,
  getMetrics,
  renderPrometheus,
  counters,
  histograms,
};

// TEST APPEND
