import { escapeHtml, sanitizePrivacyData } from '../utils.js';

export class ChatbotView {
  constructor(app) {
    this.app = app;
    this.conversationHistory = [];
    this.isLoading = false;
    this.selectedProvider = 'ollama';
    this.STORAGE_KEY = 'simplebeacon_chatbot_history';
    this.loadConversationHistory();
  }

  mount(container) {
    container.innerHTML = `
      <div class="view-container">
        <div class="view-header">
          <h1>🤖 Chatbot</h1>
          <p class="view-subtitle">AI-powered assistance for your codebase</p>
          <div class="ai-transparency-notice">
            <span class="ai-transparency-icon">🤖</span>
            <span class="ai-transparency-text">You are interacting with an AI system. Responses are generated by AI models and may contain inaccuracies.</span>
          </div>
        </div>
        <div class="view-content">
          <div class="chatbot-container">
            <div class="chatbot-toolbar">
              <select id="chatbot-provider" class="chatbot-provider-select">
                <option value="ollama">Ollama</option>
                <option value="openai">OpenAI</option>
                <option value="anthropic">Anthropic</option>
              </select>
              <button id="chatbot-clear" class="chatbot-clear-btn">Clear History</button>
            </div>
            <div id="chatbot-messages" class="chatbot-messages"></div>
            <div class="chatbot-input-container">
              <textarea 
                id="chatbot-input" 
                class="chatbot-input" 
                placeholder="Ask about your codebase..."
                rows="3"
              ></textarea>
              <button id="chatbot-send" class="chatbot-send-btn" ${this.isLoading ? 'disabled' : ''}>
                ${this.isLoading ? 'Sending...' : 'Send'}
              </button>
            </div>
          </div>
        </div>
      </div>
    `;

    this.bindEvents();
    this.loadProviders();
    this.renderMessages();

    return container;
  }

  bindEvents() {
    const sendBtn = document.getElementById('chatbot-send');
    const input = document.getElementById('chatbot-input');
    const clearBtn = document.getElementById('chatbot-clear');
    const providerSelect = document.getElementById('chatbot-provider');

    sendBtn.addEventListener('click', () => this.sendMessage());
    
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });

    clearBtn.addEventListener('click', () => {
      this.conversationHistory = [];
      this.saveConversationHistory();
      this.renderMessages();
    });

    providerSelect.addEventListener('change', (e) => {
      this.selectedProvider = e.target.value;
    });
  }

  async loadProviders() {
    try {
      const res = await fetch('/api/chatbot/providers');
      const data = await res.json();
      
      const select = document.getElementById('chatbot-provider');
      select.innerHTML = '';
      
      if (!Array.isArray(data.providers)) {
        console.warn('No providers available or unauthorized');
        return;
      }

      data.providers.forEach(provider => {
        const option = document.createElement('option');
        option.value = provider.id;
        option.textContent = provider.label;
        option.disabled = !provider.available;
        if (!provider.available) {
          option.textContent += ' (not configured)';
        }
        select.appendChild(option);
      });

      // Select first available provider
      const firstAvailable = data.providers.find(p => p.available);
      if (firstAvailable) {
        select.value = firstAvailable.id;
        this.selectedProvider = firstAvailable.id;
      }
    } catch (error) {
      console.error('Failed to load providers:', error);
    }
  }

  async sendMessage() {
    const input = document.getElementById('chatbot-input');
    const rawMessage = input.value.trim();
    
    if (!rawMessage || this.isLoading) return;

    // Sanitize message to remove PII before processing
    const message = sanitizePrivacyData(rawMessage);

    // Add user message to history
    this.conversationHistory.push({ role: 'user', content: message });
    this.renderMessages();
    this.saveConversationHistory();
    
    input.value = '';
    this.isLoading = true;
    this.updateSendButton();

    // Show typing indicator
    this.showTypingIndicator();

    try {
      const res = await fetch('/api/chatbot/message', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message,
          conversationHistory: this.conversationHistory.slice(0, -1),
          provider: this.selectedProvider,
          projectPath: this.app.state.defaultProjectPath || null
        })
      });

      // Remove typing indicator
      this.hideTypingIndicator();

      if (!res.ok) {
        throw new Error(`HTTP ${res.status}: ${res.statusText}`);
      }

      // Create placeholder for assistant response
      const assistantMessageIndex = this.conversationHistory.length;
      this.conversationHistory.push({ role: 'assistant', content: '' });
      
      // Get the message container for streaming updates
      const container = document.getElementById('chatbot-messages');
      const messageElements = container.querySelectorAll('.chatbot-message');
      const targetBubble = messageElements[assistantMessageIndex]?.querySelector('.chatbot-message-text');
      
      if (targetBubble) {
        // Consume streaming response
        await this.consumeTokenStream(res, targetBubble);
        
        // Update history with final content
        this.conversationHistory[assistantMessageIndex].content = targetBubble.textContent;
      } else {
        // Fallback to non-streaming if streaming fails
        const data = await res.json();
        if (data.success) {
          this.conversationHistory[assistantMessageIndex].content = data.response;
        } else {
          this.conversationHistory[assistantMessageIndex].content = `Error: ${data.message || 'Failed to get response'}`;
        }
      }
    } catch (error) {
      this.hideTypingIndicator();
      this.conversationHistory.push({ 
        role: 'assistant', 
        content: `Error: ${error.message}` 
      });
    } finally {
      this.isLoading = false;
      this.updateSendButton();
      this.renderMessages();
      this.saveConversationHistory();
    }
  }

  /**
   * Consumes the streaming response chunks from the chatbot api
   * and renders tokens incrementally on screen.
   * @param {Response} response - The active fetch response stream.
   * @param {HTMLElement} targetBubble - The UI text node container.
   */
  async consumeTokenStream(response, targetBubble) {
    const reader = response.body.getReader();
    const decoder = new TextDecoder('utf-8');
    let accumulatedText = '';

    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;

        // Decode the binary stream chunk
        const chunkText = decoder.decode(value, { stream: true });
        
        // Handle server-sent chunk structures (e.g. splitting text lines if SSE formatted)
        const lines = chunkText.split('\n');
        for (const line of lines) {
          if (!line.trim()) continue;
          
          try {
            const parsed = JSON.parse(line);
            if (parsed.response) {
              accumulatedText += parsed.response;
              
              // Incrementally render and update the active bubble using stream-safe formatter
              targetBubble.innerHTML = this.formatStreamedMessage(accumulatedText);
              
              // Smoothly anchor view to latest token
              const container = document.getElementById('chatbot-messages');
              if (container) {
                container.scrollTo({
                  top: container.scrollHeight,
                  behavior: 'auto'
                });
              }
            }
          } catch (e) {
            // Ignore partial or trailing newline evaluation errors
          }
        }
      }
    } catch (error) {
      console.error('Streaming connection interrupted:', error);
      targetBubble.innerHTML += '<p class="error">[Stream Interrupted]</p>';
    } finally {
      reader.releaseLock();
    }
  }

  renderMessages() {
    const container = document.getElementById('chatbot-messages');
    if (!container) return;

    if (this.conversationHistory.length === 0) {
      container.innerHTML = `
        <div class="chatbot-welcome">
          <div class="chatbot-welcome-icon">🤖</div>
          <h3>Start a conversation</h3>
          <p>Ask about your codebase, get help with issues, or request code improvements.</p>
        </div>
      `;
      return;
    }

    container.innerHTML = this.conversationHistory.map((msg, index) => `
      <div class="chatbot-message chatbot-message-${msg.role}">
        <div class="chatbot-message-content">
          <div class="chatbot-message-role">
            ${msg.role === 'user' ? 'You' : 'AI'}
            ${msg.role === 'assistant' ? `<button class="chatbot-copy-btn" data-index="${index}" title="Copy response">📋</button>` : ''}
          </div>
          <div class="chatbot-message-text">${this.formatMessage(msg.content)}</div>
        </div>
      </div>
    `).join('');

    // Add copy button event listeners
    container.querySelectorAll('.chatbot-copy-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        const index = parseInt(e.target.dataset.index);
        this.copyMessage(index);
      });
    });

    // Smooth scroll to bottom
    this.scrollToBottom(container);
  }

  formatMessage(content) {
    // First, extract and protect code blocks to prevent XSS
    const codeBlocks = [];
    let processed = content.replace(/```([\s\S]*?)```/g, (match, code) => {
      const index = codeBlocks.length;
      codeBlocks.push(escapeHtml(code));
      return `__CODEBLOCK_${index}__`;
    });

    // Protect inline code
    const inlineCodes = [];
    processed = processed.replace(/`([^`]+)`/g, (match, code) => {
      const index = inlineCodes.length;
      inlineCodes.push(escapeHtml(code));
      return `__INLINECODE_${index}__`;
    });

    // Escape remaining content
    processed = escapeHtml(processed);

    // Restore code blocks with proper HTML
    processed = processed.replace(/__CODEBLOCK_(\d+)__/g, (match, index) => {
      return `<pre class="chatbot-code-block"><code>${codeBlocks[index]}</code></pre>`;
    });

    // Restore inline code
    processed = processed.replace(/__INLINECODE_(\d+)__/g, (match, index) => {
      return `<code class="chatbot-inline-code">${inlineCodes[index]}</code>`;
    });

    // Preserve line breaks (but not in code blocks)
    processed = processed.replace(/<pre class="chatbot-code-block">[\s\S]*?<\/pre>/g, (match) => {
      return match.replace(/\n/g, '&#10;');
    });
    processed = processed.replace(/\n/g, '<br>');

    // Restore newlines in code blocks
    processed = processed.replace(/&#10;/g, '\n');

    return processed;
  }

  /**
   * Safely converts markdown strings to HTML blocks during an active token stream.
   * Automatically wraps unclosed backticks to prevent layout breakage.
   * @param {string} text - The raw, accumulating token stream text.
   * @returns {string} Safe, rendered HTML layout content.
   */
  formatStreamedMessage(text) {
    if (!text) return '';

    let processedText = text;

    // 1. Stream-Safe Guard: Detect unclosed triple backticks
    const backtickCount = (processedText.match(/```/g) || []).length;
    if (backtickCount % 2 !== 0) {
      // Dynamically append a temporary closing block for visual stability
      processedText += '\n```';
    }

    // 2. Stream-Safe Guard: Detect unclosed inline code backticks
    const inlineBacktickCount = (processedText.match(/`/g) || []).length;
    if (inlineBacktickCount % 2 !== 0) {
      processedText += '`';
    }

    // 3. Extract and protect code blocks using unique placeholders
    const codeBlocks = [];
    processedText = processedText.replace(/```([\s\S]*?)```/g, (match, code) => {
      const placeholder = `__CODE_BLOCK_PLACEHOLDER_${codeBlocks.length}__`;
      codeBlocks.push(code);
      return placeholder;
    });

    // 4. Extract and protect inline code
    const inlineBlocks = [];
    processedText = processedText.replace(/`([^`]+)`/g, (match, code) => {
      const placeholder = `__INLINE_PLACEHOLDER_${inlineBlocks.length}__`;
      inlineBlocks.push(code);
      return placeholder;
    });

    // 5. Run native XSS escaping on standard paragraph text strings
    processedText = escapeHtml(processedText);

    // 6. Restore protected inline code with safe text nodes
    inlineBlocks.forEach((code, index) => {
      const safeInline = `<code class="chatbot-inline-code">${escapeHtml(code)}</code>`;
      processedText = processedText.replace(`__INLINE_PLACEHOLDER_${index}__`, safeInline);
    });

    // 7. Restore protected structural code blocks with syntax wrappers
    codeBlocks.forEach((code, index) => {
      const safeBlock = `<pre class="chatbot-code-block"><code>${escapeHtml(code)}</code></pre>`;
      processedText = processedText.replace(`__CODE_BLOCK_PLACEHOLDER_${index}__`, safeBlock);
    });

    // 8. Preserve line breaks (but not in code blocks)
    processedText = processedText.replace(/<pre class="chatbot-code-block">[\s\S]*?<\/pre>/g, (match) => {
      return match.replace(/\n/g, '&#10;');
    });
    processedText = processedText.replace(/\n/g, '<br>');

    // 9. Restore newlines in code blocks
    processedText = processedText.replace(/&#10;/g, '\n');

    return processedText;
  }

  updateSendButton() {
    const btn = document.getElementById('chatbot-send');
    if (btn) {
      btn.disabled = this.isLoading;
      btn.textContent = this.isLoading ? 'Sending...' : 'Send';
    }
  }

  showTypingIndicator() {
    const container = document.getElementById('chatbot-messages');
    if (!container) return;
    
    const indicator = document.createElement('div');
    indicator.id = 'chatbot-typing-indicator';
    indicator.className = 'chatbot-message chatbot-message-assistant';
    indicator.innerHTML = `
      <div class="chatbot-message-content">
        <div class="chatbot-message-role">AI</div>
        <div class="chatbot-typing">
          <span class="chatbot-typing-dot"></span>
          <span class="chatbot-typing-dot"></span>
          <span class="chatbot-typing-dot"></span>
        </div>
      </div>
    `;
    container.appendChild(indicator);
    this.scrollToBottom(container);
  }

  hideTypingIndicator() {
    const indicator = document.getElementById('chatbot-typing-indicator');
    if (indicator) {
      indicator.remove();
    }
  }

  scrollToBottom(container) {
    if (!container) return;
    container.scrollTo({
      top: container.scrollHeight,
      behavior: 'smooth'
    });
  }

  loadConversationHistory() {
    try {
      const stored = localStorage.getItem(this.STORAGE_KEY);
      if (stored) {
        this.conversationHistory = JSON.parse(stored);
      }
    } catch (error) {
      console.error('Failed to load conversation history:', error);
      this.conversationHistory = [];
    }
  }

  saveConversationHistory() {
    try {
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(this.conversationHistory));
    } catch (error) {
      console.error('Failed to save conversation history:', error);
    }
  }

  copyMessage(index) {
    const message = this.conversationHistory[index];
    if (!message || !message.content) return;

    navigator.clipboard.writeText(message.content).then(() => {
      // Show brief success feedback
      const btn = document.querySelector(`.chatbot-copy-btn[data-index="${index}"]`);
      if (btn) {
        const originalText = btn.textContent;
        btn.textContent = '✓';
        btn.classList.add('copied');
        setTimeout(() => {
          btn.textContent = originalText;
          btn.classList.remove('copied');
        }, 1500);
      }
    }).catch(err => {
      console.error('Failed to copy message:', err);
    });
  }

  destroy() {
    // Cleanup event listeners if needed
  }
}
