/**
 * UploadView — Post-payment scan report upload for certificate generation.
 * Route: #/upload?token=<licenseToken>
 */
export class UploadView {
  constructor(app) {
    this.app = app;
    this.reportData = null;
  }

  mount(container, params = {}) {
    const prefillToken = params.token || '';
    const sessionId = params.session_id || '';
    const autoLookup = Boolean(sessionId && !prefillToken);

    container.innerHTML = `
      <div class="page-header">
        <h1>Upload Scan Report</h1>
        <p class="page-subtitle">
          Your scan ran locally. Upload the report JSON to generate your Executive Risk Certificate.
        </p>
      </div>

      <div class="card notice-card" style="background: rgba(245,158,11,0.08); border-color: rgba(245,158,11,0.25); color: #FCD34D;">
        <p style="margin:0">
          <strong>Privacy-first:</strong> Your source code never left your machine. Only the scan report JSON
          (findings summary, no code) is uploaded for certificate generation.
        </p>
      </div>

      <div class="card">
        <h2 style="font-size:1.1rem;margin-bottom:16px;display:flex;align-items:center;gap:8px;">
          <span style="display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:linear-gradient(135deg,#2563EB,#1D4ED8);color:white;font-size:0.85rem;font-weight:700;">1</span>
          License Token
        </h2>
        <div class="form-group">
          <label for="upload-license-token" style="display:block;font-size:0.85rem;color:var(--text-muted);margin-bottom:8px;">License Token</label>
          <input type="text" id="upload-license-token" class="form-input" placeholder="sb_euai_17805..." autocomplete="off" value="${this.escapeHtml(prefillToken)}" ${autoLookup ? 'disabled' : ''}>
          <p id="upload-token-help" style="font-size:0.8rem;color:var(--text-muted);margin-top:6px;">${autoLookup ? 'Retrieving your license token from checkout...' : 'Paste the license token from your payment confirmation email.'}</p>
        </div>
      </div>

      <div class="card">
        <h2 style="font-size:1.1rem;margin-bottom:16px;display:flex;align-items:center;gap:8px;">
          <span style="display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:linear-gradient(135deg,#2563EB,#1D4ED8);color:white;font-size:0.85rem;font-weight:700;">2</span>
          Scan Report JSON
        </h2>
        <div class="form-group">
          <label style="display:block;font-size:0.85rem;color:var(--text-muted);margin-bottom:8px;">Report File</label>
          <div class="drop-zone" id="upload-drop-zone" style="border:2px dashed var(--border);border-radius:12px;padding:40px 24px;text-align:center;cursor:pointer;transition:border-color 0.2s,background 0.2s;background:var(--bg-input);">
            <div style="font-size:2rem;margin-bottom:12px;">&#128193;</div>
            <p style="color:var(--text-muted);font-size:0.9rem;">Drag your <code>.simplebeacon/report.json</code> here<br>or click to browse</p>
            <p id="upload-file-name" style="color:var(--text-main);font-weight:500;margin-top:8px;font-family:var(--font-mono);font-size:0.85rem;"></p>
            <input type="file" id="upload-file-input" accept=".json,application/json" style="display:none;">
          </div>
          <p style="font-size:0.8rem;color:var(--text-muted);margin-top:6px;">
            Generated by: <code>npx simplebeacon scan --gate --offline --format json --output .simplebeacon/report.json</code>
          </p>
        </div>

        <div id="upload-scan-preview" style="display:none;">
          <label style="display:block;font-size:0.85rem;color:var(--text-muted);margin-bottom:8px;margin-top:16px;">Scan Preview</label>
          <div id="upload-scan-meta" class="scan-meta" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:12px;margin-bottom:12px;"></div>
          <div id="upload-preview-content" style="background:var(--bg-input);border:1px solid var(--border);border-radius:10px;padding:16px;font-family:var(--font-mono);font-size:0.8rem;max-height:180px;overflow-y:auto;white-space:pre-wrap;word-break:break-word;color:var(--text-muted);"></div>
        </div>
      </div>

      <div class="card">
        <h2 style="font-size:1.1rem;margin-bottom:16px;display:flex;align-items:center;gap:8px;">
          <span style="display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:linear-gradient(135deg,#2563EB,#1D4ED8);color:white;font-size:0.85rem;font-weight:700;">3</span>
          Generate Certificate
        </h2>
        <button class="btn btn-primary" id="upload-submit-btn" disabled style="width:100%;">
          <span>&#128229;</span> Upload &amp; Generate Certificate
        </button>
        <div id="upload-status" style="margin-top:16px;padding:14px 18px;border-radius:10px;font-size:0.9rem;display:none;"></div>
      </div>
    `;

    this.bindEvents(container, sessionId);
  }

  bindEvents(container, sessionId) {
    const licenseInput = container.querySelector('#upload-license-token');
    const tokenHelp = container.querySelector('#upload-token-help');

    // Auto-lookup license token from Stripe checkout session
    if (sessionId) {
      fetch(`/api/simplebeacon/billing/session?session_id=${encodeURIComponent(sessionId)}`)
        .then((res) => res.json())
        .then((data) => {
          if (data.licenseToken) {
            licenseInput.value = data.licenseToken;
            licenseInput.disabled = false;
            tokenHelp.textContent = 'License token auto-filled from checkout. Scan your project locally, then upload the report JSON below.';
            tokenHelp.style.color = 'var(--success)';
            this.reportData = null; // trigger updateSubmit via bind
            // Manually trigger submit update since we can't access updateSubmit here directly
            const submitBtn = container.querySelector('#upload-submit-btn');
            submitBtn.disabled = true; // still need file
          } else {
            licenseInput.disabled = false;
            tokenHelp.textContent = 'Could not retrieve license token from checkout. Paste it manually from your email.';
            tokenHelp.style.color = 'var(--error)';
          }
        })
        .catch(() => {
          licenseInput.disabled = false;
          tokenHelp.textContent = 'Could not retrieve license token from checkout. Paste it manually from your email.';
          tokenHelp.style.color = 'var(--error)';
        });
    }

    const dropZone = container.querySelector('#upload-drop-zone');
    const fileInput = container.querySelector('#upload-file-input');
    const fileName = container.querySelector('#upload-file-name');
    const submitBtn = container.querySelector('#upload-submit-btn');
    const status = container.querySelector('#upload-status');
    const scanPreview = container.querySelector('#upload-scan-preview');
    const scanMeta = container.querySelector('#upload-scan-meta');
    const previewContent = container.querySelector('#upload-preview-content');

    const updateSubmit = () => {
      const hasToken = licenseInput.value.trim().length > 10;
      const hasFile = this.reportData !== null;
      submitBtn.disabled = !(hasToken && hasFile);
    };

    licenseInput.addEventListener('input', updateSubmit);

    dropZone.addEventListener('click', () => fileInput.click());
    dropZone.addEventListener('dragover', (e) => {
      e.preventDefault();
      dropZone.style.borderColor = 'var(--accent)';
      dropZone.style.background = 'rgba(37,99,235,0.05)';
    });
    dropZone.addEventListener('dragleave', () => {
      dropZone.style.borderColor = 'var(--border)';
      dropZone.style.background = 'var(--bg-input)';
    });
    dropZone.addEventListener('drop', (e) => {
      e.preventDefault();
      dropZone.style.borderColor = 'var(--border)';
      dropZone.style.background = 'var(--bg-input)';
      const file = e.dataTransfer.files[0];
      if (file) this.handleFile(file, fileName, scanPreview, scanMeta, previewContent, updateSubmit);
    });
    fileInput.addEventListener('change', (e) => {
      if (e.target.files[0]) {
        this.handleFile(e.target.files[0], fileName, scanPreview, scanMeta, previewContent, updateSubmit);
      }
    });

    submitBtn.addEventListener('click', async () => {
      const token = licenseInput.value.trim();
      if (!token || !this.reportData) return;

      submitBtn.disabled = true;
      this.showStatus(status, 'Uploading scan report and generating certificate...', 'loading');

      try {
        const response = await fetch('/api/reports/upload', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({ reportJson: this.reportData, licenseToken: token })
        });

        const result = await response.json();

        if (result.success) {
          this.showStatus(
            status,
            `Certificate generated successfully! Delivery ID: ${result.deliveryId}. Check your inbox for the ZIP bundle containing the audit report, certificate, and all JSON artifacts.`,
            'success'
          );
        } else {
          this.showStatus(status, result.error || 'Upload failed', 'error');
        }
      } catch (err) {
        this.showStatus(status, 'Network error — please check your connection and try again. (' + err.message + ')', 'error');
      } finally {
        submitBtn.disabled = false;
      }
    });
  }

  handleFile(file, fileNameEl, scanPreviewEl, scanMetaEl, previewContentEl, updateSubmit) {
    if (!file.name.endsWith('.json')) {
      const status = document.getElementById('upload-status');
      this.showStatus(status, 'Please upload a .json file', 'error');
      return;
    }
    fileNameEl.textContent = file.name;
    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        this.reportData = JSON.parse(e.target.result);
        this.renderPreview(this.reportData, scanMetaEl, previewContentEl);
        scanPreviewEl.style.display = 'block';
        updateSubmit();
      } catch (err) {
        const status = document.getElementById('upload-status');
        this.showStatus(status, 'Invalid JSON file', 'error');
        this.reportData = null;
        updateSubmit();
      }
    };
    reader.readAsText(file);
  }

  renderPreview(data, scanMetaEl, previewContentEl) {
    const gate = data.gate || data.results?.simplebeacon?.gate || {};
    const gatePass = gate.pass ?? false;
    const detectedIssues = data.detectedIssues || data.rawIssues || [];
    const rawIssues = data.rawIssues || detectedIssues || [];
    const quality = data.qualityScore ?? data.results?.simplebeacon?.qualityScore ?? (rawIssues.length ? Math.max(0, 100 - rawIssues.length * 2) : '—');
    const files = data.repositoryFilesTotal ?? data.totalFiles ?? data.filesAnalyzed ?? data.summary?.files ?? '—';
    const issues = data.issueCount ?? gate.blockingCount ?? detectedIssues.length ?? rawIssues.length ?? '—';
    const project = data.projectRoot || data.scanTargetRoot || (Array.isArray(data.scanPaths) ? data.scanPaths[0] : null) || '—';

    scanMetaEl.innerHTML = `
      <div style="background:var(--bg-input);border:1px solid var(--border);border-radius:8px;padding:12px;text-align:center;">
        <div style="font-size:1.3rem;font-weight:700;color:${gatePass ? 'var(--success)' : 'var(--error)'};">${gatePass ? 'PASS' : 'REVIEW'}</div>
        <div style="font-size:0.75rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-top:4px;">Gate</div>
      </div>
      <div style="background:var(--bg-input);border:1px solid var(--border);border-radius:8px;padding:12px;text-align:center;">
        <div style="font-size:1.3rem;font-weight:700;color:var(--text-main);">${quality}%</div>
        <div style="font-size:0.75rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-top:4px;">Quality</div>
      </div>
      <div style="background:var(--bg-input);border:1px solid var(--border);border-radius:8px;padding:12px;text-align:center;">
        <div style="font-size:1.3rem;font-weight:700;color:var(--text-main);">${files}</div>
        <div style="font-size:0.75rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-top:4px;">Files</div>
      </div>
      <div style="background:var(--bg-input);border:1px solid var(--border);border-radius:8px;padding:12px;text-align:center;">
        <div style="font-size:1.3rem;font-weight:700;color:var(--text-main);">${issues}</div>
        <div style="font-size:0.75rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-top:4px;">Issues</div>
      </div>
      <div style="background:var(--bg-input);border:1px solid var(--border);border-radius:8px;padding:12px;text-align:center;">
        <div style="font-size:0.9rem;font-weight:700;color:var(--text-main);word-break:break-all;">${project}</div>
        <div style="font-size:0.75rem;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-top:4px;">Project</div>
      </div>
    `;

    const snippet = JSON.stringify(data, null, 2).slice(0, 1200);
    previewContentEl.textContent = snippet + (snippet.length >= 1200 ? '\n\n... (truncated for preview)' : '');
  }

  showStatus(el, message, type) {
    el.style.display = 'block';
    el.textContent = message;
    if (type === 'success') {
      el.style.background = 'rgba(16,185,129,0.1)';
      el.style.border = '1px solid rgba(16,185,129,0.3)';
      el.style.color = 'var(--success)';
    } else if (type === 'error') {
      el.style.background = 'rgba(239,68,68,0.1)';
      el.style.border = '1px solid rgba(239,68,68,0.3)';
      el.style.color = 'var(--error)';
    } else if (type === 'loading') {
      el.style.background = 'rgba(37,99,235,0.1)';
      el.style.border = '1px solid rgba(37,99,235,0.3)';
      el.style.color = '#60A5FA';
    }
  }

  escapeHtml(str) {
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  destroy() {}
}
