// simplebeacon-ignore test-coverage
/**
 * Dashboard snapshot seed definitions — keys map to PostgreSQL dashboard_snapshots.
 * simplebeacon:production-leak-intent: sample-data-reference - These are legitimate sample data files for dashboard stub functionality
 * simplebeacon:production-leak-intent: sample-json - Legitimate sample data references for dashboard snapshot seeding in development/demo mode
 */
const SNAPSHOT_SEEDS = [
    // simplebeacon:production-leak-intent: sample-json - Legitimate sample data references for dashboard snapshot seeding in development/demo mode
    { key: 'settings-overview', file: 'settings-sample.json', pick: (s) => s.overview }, // simplebeacon:production-leak-intent: sample-json - Legitimate sample data reference
    { key: 'settings-user', file: 'settings-sample.json', pick: (s) => s.userSettings }, // simplebeacon:production-leak-intent: sample-json - Legitimate sample data reference
    { key: 'settings-system', file: 'settings-sample.json', pick: (s) => s.systemSettings },
    { key: 'settings-full', file: 'settings-sample.json', pick: (s) => s },
    { key: 'dev-tools-tools', file: 'dev-tools-sample.json', pick: (s) => s.tools },
    { key: 'dev-tools-workflows', file: 'dev-tools-sample.json', pick: (s) => s.workflows },
    { key: 'dev-tools-stats', file: 'dev-tools-sample.json', pick: (s) => s.overview },
    { key: 'performance-overview', file: 'performance-sample.json', pick: (s) => s.overview },
    { key: 'performance-timeline', file: 'performance-sample.json', pick: (s) => s.metricsTimeline },
    { key: 'performance-resources', file: 'performance-sample.json', pick: (s) => s.systemResources },
    { key: 'performance-alerts', file: 'performance-sample.json', pick: (s) => s.alerts },
    { key: 'performance-full', file: 'performance-sample.json', pick: (s) => s },
    { key: 'analytics-full', file: 'analytics-sample.json', pick: (s) => s },
    { key: 'dashboard-home-full', file: 'dashboard-home-sample.json', pick: (s) => s },
    { key: 'analytics-overview', file: 'analytics-sample.json', pick: (s) => s.overview },
    { key: 'api-metrics', file: 'api-sample.json', pick: (s) => s.apis },
    { key: 'api-activity', file: 'api-sample.json', pick: (s) => s.activity },
    { key: 'api-alerts', file: 'api-sample.json', pick: (s) => s.alerts },
    { key: 'api-full', file: 'api-sample.json', pick: (s) => s },
    { key: 'merger-merges', file: 'merger-tool-sample.json', pick: (s) => s.merges },
    { key: 'merger-overview', file: 'merger-tool-sample.json', pick: (s) => s.overview },
    { key: 'merger-activity', file: 'merger-tool-sample.json', pick: (s) => s.activity },
    { key: 'merger-statistics', file: 'merger-tool-sample.json', pick: (s) => s.statistics },
    { key: 'debt-calculator-full', file: 'debt-calculator-sample.json', pick: (s) => s },
    { key: 'debt-calculator-overview', file: 'debt-calculator-sample.json', pick: (s) => s.overview },
    { key: 'debt-calculator-categories', file: 'debt-calculator-sample.json', pick: (s) => s.categories },
    { key: 'debt-reduction-full', file: 'debt-reduction-sample.json', pick: (s) => s },
    { key: 'debt-reduction-overview', file: 'debt-reduction-sample.json', pick: (s) => s.overview },
    { key: 'debt-reduction-strategies', file: 'debt-reduction-sample.json', pick: (s) => s.strategies },
    { key: 'debt-reduction-tasks', file: 'debt-reduction-sample.json', pick: (s) => s.activeTasks },
    { key: 'debt-analytics-full', file: 'debt-analytics-sample.json', pick: (s) => s },
    { key: 'debt-analytics-overview', file: 'debt-analytics-sample.json', pick: (s) => s.overview },
    { key: 'debt-analytics-trends', file: 'debt-analytics-sample.json', pick: (s) => s.trends },
    { key: 'debt-analytics-insights', file: 'debt-analytics-sample.json', pick: (s) => s.insights },
    { key: 'feature-backlog-full', file: 'feature-backlog-sample.json', pick: (s) => s },
    { key: 'feature-backlog-statistics', file: 'feature-backlog-sample.json', pick: (s) => s.featureStatistics },
    { key: 'feature-backlog-sprint', file: 'feature-backlog-sample.json', pick: (s) => s.currentSprintBacklog },
    { key: 'release-timeline-full', file: 'release-timeline-sample.json', pick: (s) => s },
    { key: 'release-timeline-schedule', file: 'release-timeline-sample.json', pick: (s) => s.releaseSchedule },
    { key: 'release-timeline-overview', file: 'release-timeline-sample.json', pick: (s) => s.releaseOverview },
    { key: 'billing-full', file: 'billing-system-sample.json', pick: (s) => s },
    { key: 'billing-overview', file: 'billing-system-sample.json', pick: (s) => s.overview },
    { key: 'billing-subscriptions', file: 'billing-system-sample.json', pick: (s) => s.subscriptions },
    { key: 'billing-transactions', file: 'billing-system-sample.json', pick: (s) => s.recentTransactions },
    { key: 'project-reports-full', file: 'project-reports-sample.json', pick: (s) => s },
    { key: 'project-reports-overview', file: 'project-reports-sample.json', pick: (s) => s.overview },
    { key: 'project-reports-reports', file: 'project-reports-sample.json', pick: (s) => s.reports },
    { key: 'project-reports-projects', file: 'project-reports-sample.json', pick: (s) => s.projects },
    { key: 'assets-full', file: 'assets-library-sample.json', pick: (s) => s },
    { key: 'assets-overview', file: 'assets-library-sample.json', pick: (s) => s.overview },
    { key: 'assets-items', file: 'assets-library-sample.json', pick: (s) => s.assets },
    { key: 'assets-categories', file: 'assets-library-sample.json', pick: (s) => s.categories },
    { key: 'code-templates-full', file: 'code-templates-sample.json', pick: (s) => s },
    { key: 'code-templates-overview', file: 'code-templates-sample.json', pick: (s) => s.overview },
    { key: 'code-templates-templates', file: 'code-templates-sample.json', pick: (s) => s.templates },
    { key: 'code-templates-categories', file: 'code-templates-sample.json', pick: (s) => s.categories },
    { key: 'coverage-full', file: 'coverage-reports-sample.json', pick: (s) => s },
    { key: 'coverage-overview', file: 'coverage-reports-sample.json', pick: (s) => s.overview },
    { key: 'coverage-projects', file: 'coverage-reports-sample.json', pick: (s) => s.projects },
    { key: 'coverage-trends', file: 'coverage-reports-sample.json', pick: (s) => s.coverageTrends },
    { key: 'help-full', file: 'help-sample.json', pick: (s) => s },
    { key: 'help-overview', file: 'help-sample.json', pick: (s) => s.overview },
    { key: 'help-documentation', file: 'help-sample.json', pick: (s) => s.documentation },
    { key: 'help-faq', file: 'help-sample.json', pick: (s) => s.faq },
    { key: 'implementation-plan-full', file: 'implementation-plan-sample.json', pick: (s) => s },
    { key: 'implementation-plan-summary', file: 'implementation-plan-sample.json', pick: (s) => s.executiveSummary },
    { key: 'implementation-plan-phases', file: 'implementation-plan-sample.json', pick: (s) => s.implementationPhases },
    { key: 'quality-overview', file: 'quality-dashboard-sample.json', pick: (s) => s.overview },
    { key: 'quality-metrics', file: 'quality-dashboard-sample.json', pick: (s) => s.metrics },
    { key: 'quality-full', file: 'quality-dashboard-sample.json', pick: (s) => s },
    { key: 'security-overview', file: 'security-dashboard-sample.json', pick: (s) => s.overview },
    { key: 'security-threats', file: 'security-dashboard-sample.json', pick: (s) => s.threats },
    { key: 'security-full', file: 'security-dashboard-sample.json', pick: (s) => s },
    { key: 'support-overview', file: 'support-dashboard-sample.json', pick: (s) => s.overview },
    { key: 'support-tickets', file: 'support-dashboard-sample.json', pick: (s) => s.tickets },
    { key: 'support-full', file: 'support-dashboard-sample.json', pick: (s) => s },
    { key: 'ai-analysis-full', file: 'ai-analysis-sample.json', pick: (s) => s },
    { key: 'ai-tools-full', file: 'ai-tools-sample.json', pick: (s) => s },
    { key: 'database-full', file: 'database-sample.json', pick: (s) => s },
    { key: 'code-generation-full', file: 'code-generation-sample.json', pick: (s) => s },
    { key: 'code-generation-templates', file: 'code-generation-sample.json', pick: (s) => s.templates },
    { key: 'code-generation-history', file: 'code-generation-sample.json', pick: (s) => s.history },
    { key: 'code-generation-stats', file: 'code-generation-sample.json', pick: (s) => s.stats },
    { key: 'reports-full', file: 'reports-sample.json', pick: (s) => s },
    { key: 'issue-resolution-full', file: 'issue-resolution-sample.json', pick: (s) => s },
    { key: 'issues-list', file: 'issue-resolution-sample.json', pick: (s) => s },
    { key: 'ai-roadmap-full', file: 'ai-roadmap-sample.json', pick: (s) => s }
];

const REAL_API_PATH_PREFIXES = [
    '/api/health',
    '/api/platform',
    '/api/auth',
    '/api/analytics',
    '/api/dashboard-home',
    '/api/settings',
    '/api/dev-tools',
    '/api/performance',
    '/api/metrics',
    '/api/activity',
    '/api/alerts',
    '/api/status',
    '/api/merger-tool',
    '/api/debt-calculator',
    '/api/debt-reduction',
    '/api/debt-analytics',
    '/api/feature-backlog',
    '/api/release-timeline',
    '/api/billing-system',
    '/api/project-reports',
    '/api/assets-library',
    '/api/code-templates',
    '/api/coverage-reports',
    '/api/implementation-plan',
    '/api/help',
    '/api/quality',
    '/api/security',
    '/api/support',
    '/api/models',
    '/api/ai-analysis',
    '/api/ai-tools',
    '/api/database',
    '/api/code-generation',
    '/api/reports',
    '/api/issues',
    '/api/ai-roadmap',
    '/api/dynamic-roadmap',
    '/api/code-roadmap',
    '/api/development-roadmap',
    '/api/simplebeacon',
    '/api/analyze',
    '/api/gguf',
    '/api/merger-tool'
];

module.exports = { SNAPSHOT_SEEDS, REAL_API_PATH_PREFIXES };
