/**
 * Plan definitions — single source of truth for SimpleBeacon pricing tiers.
 * Consumed by checkout, token generation, and dashboard tier gating.
 */

'use strict';

const PLANS = {
    starter: {
        id: 'starter',
        tag: 'Starter',
        name: 'Free',
        price: 0,
        priceLabel: '$0',
        billing: 'free',
        description: 'For solo devs and side projects. Catch AI slop before it ships.',
        features: [
            'Up to 50 files per scan',
            'Gate scan: credentials + AI patterns',
            'AI Slop Cop: placeholder debris detection',
            'CLI + VS Code extension',
            'Text output only'
        ],
        footnote: 'No credit card required',
        cta: 'Install Free',
        ctaLink: 'https://marketplace.visualstudio.com/items?itemName=simplebeacon.simplebeacon-vscode',
        moduleAccess: ['gate', 'llm-slop'],
        limits: { maxFilesPerScan: 50, maxFindingsShown: 5, showQualityScore: false },
        defaultTtlDays: 365,
        stripePriceId: null,
        popular: false
    },

    pro: {
        id: 'pro',
        tag: 'Pro',
        name: 'Continuous Shield',
        price: 9,
        priceLabel: '$9/mo',
        billing: 'monthly',
        defaultTtlDays: 30,
        description: 'Remove the free-tier walls that block real work.',
        features: [
            'Unlimited files per scan (Free: 50)',
            'All findings shown (Free: 5 only)',
            'Quality score visible (Free: hidden)',
            '48 analyzer engines (AI Slop Cop full suite)',
            'GitHub Action + CI gate',
            'Export reports (JSON, Markdown)',
            'Priority email support'
        ],
        footnote: 'Cancel anytime · 7-day money-back guarantee',
        cta: 'Subscribe',
        ctaAction: 'checkout',
        moduleAccess: [
            'gate',
            'consolidation',
            'mock-data',
            'roadmap',
            'codebase',
            'file-reduction',
            'data-quality',
            'cleanup',
            'npm-audit',
            'compliance',
            'eu-ai-act',
            'dependency-vulns',
            'build-readiness',
            'ai-indicators',
            'governance',
            'junk-files',
            'ai-residue',
            'performance',
            'type-safety',
            'documentation',
            'test-coverage',
            'accessibility',
            'i18n',
            'sensitive-data',
            'config-drift',
            'security-headers',
            'database-patterns',
            'framework-practices',
            'workspace-health',
            'unused-deps',
            'api-contract',
            'complexity',
            'fix-preview',
            'llm-slop',
            'token-bleed',
            'production-leak',
            'fiction-kpi',
            'architecture-drift'
        ],
        limits: { maxFilesPerScan: null, maxFindingsShown: null, showQualityScore: true },
        stripePriceId: 'price_pro_monthly',
        popular: true
    },

    enterprise: {
        id: 'enterprise',
        tag: 'Enterprise',
        name: 'Compliance Suite',
        price: null,
        priceLabel: 'Custom',
        billing: 'annual',
        description: 'Board-ready compliance. EU AI Act, SOC 2 evidence packs, and analyst support.',
        features: [
            'Everything in Pro',
            '48 analyzer modules (full CLI + dashboard suite)',
            'Team management (5+ seats)',
            'SSO authentication',
            'Custom rule development',
            'Dedicated support channel + SLA',
            'Self-hosted / air-gapped option'
        ],
        footnote: 'Annual contract · Volume discounts available',
        cta: 'Contact Sales',
        ctaLink: 'contact.html?topic=enterprise',
        moduleAccess: [
            'gate',
            'consolidation',
            'mock-data',
            'roadmap',
            'codebase',
            'file-reduction',
            'data-quality',
            'cleanup',
            'npm-audit',
            'compliance',
            'eu-ai-act',
            'dependency-vulns',
            'build-readiness',
            'ai-indicators',
            'governance',
            'junk-files',
            'ai-residue',
            'performance',
            'type-safety',
            'documentation',
            'test-coverage',
            'accessibility',
            'i18n',
            'sensitive-data',
            'config-drift',
            'security-headers',
            'database-patterns',
            'framework-practices',
            'workspace-health',
            'unused-deps',
            'api-contract',
            'complexity',
            'fix-preview',
            'llm-slop',
            'token-bleed',
            'production-leak',
            'fiction-kpi',
            'architecture-drift',
            'sync-io',
            'eval-danger',
            'inner-html-xss',
            'prototype-pollution',
            'unhandled-promise',
            'magic-number',
            'missing-strict-mode',
            'uninitialized-read',
            'unvalidated-redirect',
            'missing-rate-limit',
            'insecure-random',
            'logging-secrets',
            'hardcoded-confidence',
            'hardcoded-completion',
            'mock-path-leak',
            'sample-json-ref',
            'governance-marker',
            'ai-placeholder-comment',
            'ai-placeholder-block',
            'markdown-fence-leak',
            'empty-stub-function',
            'arrow-stub',
            'roadmap-marker'
        ],
        limits: { maxFilesPerScan: null, maxFindingsShown: null, showQualityScore: true },
        defaultTtlDays: 365,
        stripePriceId: null,
        popular: false
    },

    trial: {
        id: 'trial',
        tag: 'Trial',
        name: '14-Day Trial',
        price: 0,
        priceLabel: '$0',
        billing: 'trial',
        description: 'Full Developer tier features for 14 days. No credit card required.',
        features: [
            'Unlimited files per scan',
            'All findings shown',
            'Quality score visible',
            '38 IDE rules + 38 CLI modules (AI Slop Cop full suite)',
            'GitHub Action + CI gate',
            'Export reports (JSON, Markdown)'
        ],
        footnote: 'No credit card required · Reverts to the free tier after 14 days',
        cta: 'Start Free Trial',
        ctaAction: 'checkout',
        moduleAccess: [
            'gate',
            'consolidation',
            'mock-data',
            'roadmap',
            'codebase',
            'file-reduction',
            'data-quality',
            'cleanup',
            'npm-audit',
            'compliance',
            'eu-ai-act',
            'dependency-vulns',
            'build-readiness',
            'ai-indicators',
            'governance',
            'junk-files',
            'ai-residue',
            'performance',
            'type-safety',
            'documentation',
            'test-coverage',
            'accessibility',
            'i18n',
            'sensitive-data',
            'config-drift',
            'security-headers',
            'database-patterns',
            'framework-practices',
            'workspace-health',
            'unused-deps',
            'api-contract',
            'complexity',
            'fix-preview',
            'llm-slop',
            'token-bleed',
            'production-leak',
            'fiction-kpi',
            'architecture-drift'
        ],
        limits: { maxFilesPerScan: null, maxFindingsShown: null, showQualityScore: true },
        defaultTtlDays: 14,
        stripePriceId: null,
        popular: false
    }
};

function getPlan(tierId) {
    return PLANS[tierId] || null;
}

function getModuleAccess(tierId) {
    const plan = getPlan(tierId);
    return plan ? plan.moduleAccess : [];
}

function getLimits(tierId) {
    const plan = getPlan(tierId);
    return plan ? plan.limits : { maxFilesPerScan: 0, maxFindingsShown: 0, showQualityScore: false };
}

module.exports = { PLANS, getPlan, getModuleAccess, getLimits };
