// Count, rate-limit, retry, pagination, and token constants

const DEFAULT_RECORD_COUNT_BASE = 100;
const DEFAULT_RANDOM_MAX = 1000;

const DEFAULT_PAGE_SIZE = 20;
const MAX_PAGE_SIZE = 100;
const MAX_PAGINATION_LIMIT = 1000;

const MAX_BATCH_SIZE = 500;
const MAX_BULK_INSERT_SIZE = 1000;

const MAX_RATE_LIMIT = 2000;
const MAX_ANALYZE_RATE_LIMIT = 1000;
const AUTH_RATE_LIMIT = 15;
const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;

const MAX_RETRIES = 10;
const RETRY_BACKOFF_BASE_MS = 1000;
const RETRY_BACKOFF_MAX_MS = 30_000;

const TOKEN_EXPIRY_HOURS = 24;
const REFRESH_TOKEN_EXPIRY_DAYS = 7;
const MAX_LOGIN_ATTEMPTS = 5;
const LOCKOUT_DURATION_MINUTES = 30;

module.exports = Object.freeze({
  DEFAULT_RECORD_COUNT_BASE,
  DEFAULT_RANDOM_MAX,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  MAX_PAGINATION_LIMIT,
  MAX_BATCH_SIZE,
  MAX_BULK_INSERT_SIZE,
  MAX_RATE_LIMIT,
  MAX_ANALYZE_RATE_LIMIT,
  AUTH_RATE_LIMIT,
  RATE_LIMIT_WINDOW_MS,
  MAX_RETRIES,
  RETRY_BACKOFF_BASE_MS,
  RETRY_BACKOFF_MAX_MS,
  TOKEN_EXPIRY_HOURS,
  REFRESH_TOKEN_EXPIRY_DAYS,
  MAX_LOGIN_ATTEMPTS,
  LOCKOUT_DURATION_MINUTES
});
