// Time-related constants (milliseconds and seconds)

const MS_PER_SECOND = 1000;
const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
const HOURS_PER_DAY = 24;

const ONE_SECOND_MS = MS_PER_SECOND;
const ONE_MINUTE_MS = SECONDS_PER_MINUTE * MS_PER_SECOND;
const FIVE_MINUTES_MS = 5 * ONE_MINUTE_MS;
const ONE_HOUR_MS = MINUTES_PER_HOUR * ONE_MINUTE_MS;
const ONE_DAY_MS = HOURS_PER_DAY * ONE_HOUR_MS;
const THIRTY_DAYS_MS = 30 * ONE_DAY_MS;

const TIMEOUT_2S = 2000;
const TIMEOUT_5S = 5000;
const TIMEOUT_8S = 8000;
const TIMEOUT_12S = 12000;
const TIMEOUT_15S = 15000;
const TIMEOUT_30S = 30000;
const TIMEOUT_1M = 60000;
const TIMEOUT_2M = 120000;
const TIMEOUT_10M = 600000;
const TIMEOUT_15M = 900000;

const ONE_WEEK_MS = 7 * ONE_DAY_MS;
const ONE_YEAR_MS = 365 * ONE_DAY_MS;

const ONE_YEAR_SECONDS = 31536000;
const ONE_DAY_SECONDS = 86400;
const ONE_HOUR_SECONDS = 3600;
const ONE_WEEK_SECONDS = 7 * ONE_DAY_SECONDS;

const COOKIE_MAX_AGE = 3600000;

// Cache TTLs (ms)
const CACHE_TTL_SHORT = 60_000;     // 1 minute
const CACHE_TTL_MEDIUM = 300_000;   // 5 minutes
const CACHE_TTL_LONG = 3_600_000;   // 1 hour
const CACHE_TTL_PERSISTENT = ONE_DAY_MS;

module.exports = Object.freeze({
  MS_PER_SECOND,
  SECONDS_PER_MINUTE,
  MINUTES_PER_HOUR,
  HOURS_PER_DAY,
  ONE_SECOND_MS,
  ONE_MINUTE_MS,
  FIVE_MINUTES_MS,
  ONE_HOUR_MS,
  ONE_DAY_MS,
  ONE_WEEK_MS,
  ONE_YEAR_MS,
  THIRTY_DAYS_MS,
  TIMEOUT_2S,
  TIMEOUT_5S,
  TIMEOUT_8S,
  TIMEOUT_12S,
  TIMEOUT_15S,
  TIMEOUT_30S,
  TIMEOUT_1M,
  TIMEOUT_2M,
  TIMEOUT_10M,
  TIMEOUT_15M,
  ONE_YEAR_SECONDS,
  ONE_DAY_SECONDS,
  ONE_HOUR_SECONDS,
  ONE_WEEK_SECONDS,
  COOKIE_MAX_AGE,
  CACHE_TTL_SHORT,
  CACHE_TTL_MEDIUM,
  CACHE_TTL_LONG,
  CACHE_TTL_PERSISTENT
});
