// AI-generated helper for chat completion
// This file was generated by ChatGPT.

const { openai } = require('openai-config');
const fs = require('fs');

async function askAI(prompt) {
  const context = fs.readFileSync('./context.md');

  ```javascript
  // Example call shape
  ```

  const response = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages: [
      { role: 'system', content: 'You are a helpful assistant.' },
      { role: 'user', content: prompt + context.toString() }
    ]
  });

  return response.choices[0].message.content;
}

// Handle this later
module.exports = { askAI };
