import {
  createContext,
  useContext,
  useEffect,
  useState,
  useMemo,
  type ReactNode,
} from "react";
import { apiUrl } from "@/config";

// ── Types ────────────────────────────────────────────────────────────────────

interface BrandConfig {
  productName: string;
  tagline: string;
  logoUrl: string | null;
  logoDarkUrl: string | null;
  faviconUrl: string | null;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  surfaceColor: string;
  textColor: string;
  reportHeader: string;
  reportFooter: string;
  emailFromName: string;
  emailFromAddress: string;
  emailTemplateColor: string;
  customCss: string | null;
  customDomain: string | null;
  customSubdomain: string | null;
  legalName: string;
  privacyPolicyUrl: string | null;
  termsUrl: string | null;
  supportUrl: string | null;
  helpUrl: string | null;
}

interface BrandInjection {
  brand: BrandConfig;
  partnerId: string | null;
  resolvedAt: string;
}

interface BrandContextValue {
  brand: BrandConfig;
  partnerId: string | null;
  isWhitelabeled: boolean;
  loading: boolean;
  error: string | null;
  refresh: () => void;
}

// ── Default brand (matches DEFAULT_BRAND in whitelabel-config-store.cjs) ─────

const DEFAULT_BRAND: BrandConfig = {
  productName: "SimpleBeacon",
  tagline: "AI Compliance, Automated",
  logoUrl: null,
  logoDarkUrl: null,
  faviconUrl: null,
  primaryColor: "#4A90D9",
  secondaryColor: "#36A64F",
  accentColor: "#FF6600",
  backgroundColor: "#0F172A",
  surfaceColor: "#1E293B",
  textColor: "#F1F5F9",
  reportHeader: "SimpleBeacon Compliance Report",
  reportFooter:
    "Generated by SimpleBeacon.ai — EU AI Act Article 50 Disclosure: Outputs may be AI-generated.",
  emailFromName: "SimpleBeacon",
  emailFromAddress: "notifications@simplebeacon.ai",
  emailTemplateColor: "#4A90D9",
  customCss: null,
  customDomain: null,
  customSubdomain: null,
  legalName: "SimpleBeacon AI, Inc.",
  privacyPolicyUrl: null,
  termsUrl: null,
  supportUrl: null,
  helpUrl: null,
};

// ── Context ──────────────────────────────────────────────────────────────────

const BrandContext = createContext<BrandContextValue>({
  brand: DEFAULT_BRAND,
  partnerId: null,
  isWhitelabeled: false,
  loading: true,
  error: null,
  refresh: () => {},
});

// ── CSS Variable Injection ───────────────────────────────────────────────────

/**
 * Apply brand CSS variables to :root at runtime.
 * Replaces the server-injected <style id="whitelabel-brand-css"> block
 * so that runtime brand changes (e.g., after fetch fallback) are reflected.
 */
function applyBrandCss(brand: BrandConfig) {
  const cssLines = [
    ":root {",
    `  --brand-primary: ${brand.primaryColor};`,
    `  --brand-secondary: ${brand.secondaryColor};`,
    `  --brand-accent: ${brand.accentColor};`,
    `  --brand-background: ${brand.backgroundColor};`,
    `  --brand-surface: ${brand.surfaceColor};`,
    `  --brand-text: ${brand.textColor};`,
    `  --brand-product-name: "${brand.productName}";`,
    `  --brand-tagline: "${brand.tagline}";`,
    `  --brand-report-header: "${brand.reportHeader}";`,
    "}",
  ];

  if (brand.customCss) {
    cssLines.push("", brand.customCss);
  }

  const cssText = cssLines.join("\n");

  // Replace or create the brand style element
  let styleEl = document.getElementById("whitelabel-brand-css");
  if (!styleEl) {
    styleEl = document.createElement("style");
    styleEl.id = "whitelabel-brand-css";
    document.head.appendChild(styleEl);
  }
  styleEl.textContent = cssText;

  // Update document title with product name
  if (brand.productName && brand.productName !== "SimpleBeacon") {
    document.title = `${brand.productName} — ${brand.tagline}`;
  }

  // Update favicon if provided
  if (brand.faviconUrl) {
    let faviconLink =
      document.querySelector<HTMLLinkElement>('link[rel="icon"]');
    if (!faviconLink) {
      faviconLink = document.createElement("link");
      faviconLink.rel = "icon";
      document.head.appendChild(faviconLink);
    }
    faviconLink.href = brand.faviconUrl;
  }
}

// ── Provider ─────────────────────────────────────────────────────────────────

export function BrandProvider({ children }: { children: ReactNode }) {
  const [brand, setBrand] = useState<BrandConfig>(DEFAULT_BRAND);
  const [partnerId, setPartnerId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [refreshKey, setRefreshKey] = useState(0);

  useEffect(() => {
    let cancelled = false;

    async function loadBrand() {
      // 1. Check server-injected brand config (from whitelabel-middleware)
      const injected = (window as any).__SIMPLEBEACON_BRAND__ as
        BrandInjection | undefined;
      if (injected && injected.brand) {
        if (cancelled) return;
        setBrand(injected.brand);
        setPartnerId(injected.partnerId);
        applyBrandCss(injected.brand);
        setLoading(false);
        return;
      }

      // 2. Fallback: fetch from /api/whitelabel/resolve
      try {
        const hostname = window.location.hostname;
        const response = await fetch(
          `${apiUrl("whitelabel/resolve")}?domain=${encodeURIComponent(hostname)}`,
          { headers: { Accept: "application/json" } },
        );
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        if (cancelled) return;
        if (data.found && data.brand) {
          setBrand(data.brand);
          setPartnerId(data.partnerId || null);
          applyBrandCss(data.brand);
        } else {
          // No partner found — use default brand
          applyBrandCss(DEFAULT_BRAND);
        }
      } catch (err) {
        if (cancelled) return;
        setError(err instanceof Error ? err.message : "Failed to load brand");
        // Apply default brand CSS even on error
        applyBrandCss(DEFAULT_BRAND);
      } finally {
        if (!cancelled) setLoading(false);
      }
    }

    loadBrand();
    return () => {
      cancelled = true;
    };
  }, [refreshKey]);

  const value = useMemo<BrandContextValue>(
    () => ({
      brand,
      partnerId,
      isWhitelabeled: partnerId !== null,
      loading,
      error,
      refresh: () => setRefreshKey((k) => k + 1),
    }),
    [brand, partnerId, loading, error],
  );

  return (
    <BrandContext.Provider value={value}>{children}</BrandContext.Provider>
  );
}

// ── Hook ─────────────────────────────────────────────────────────────────────

export function useBrand(): BrandContextValue {
  return useContext(BrandContext);
}

export { DEFAULT_BRAND };
export type { BrandConfig, BrandInjection, BrandContextValue };
