/**
 * Database Page — self-contained database management dashboard
 */
(function () {
    const SAMPLE_URL = '/data/database-sample.json';

    function escapeHtml(value) {
        return String(value ?? '')
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;');
    }

    function isDatabaseModel(payload) {
        return Boolean(payload && (payload.type === 'database-model' || (payload.databases && payload.overview)));
    }

    function normalizeModel(payload) {
        const raw = payload?.data && isDatabaseModel(payload.data) ? payload.data : payload;
        if (!isDatabaseModel(raw)) return null;

        const databases = raw.databases || [];
        const connectedDatabases = databases.filter((db) => db.status === 'connected').length;
        const totalRecords = databases.reduce((sum, db) => sum + (db.records || 0), 0);

        return {
            type: raw.type || 'database-model',
            generatedAt: raw.generatedAt || new Date().toISOString(),
            generatedBy: raw.generatedBy || 'GGUF AI Platform',
            overview: {
                ...(raw.overview || {}),
                totalDatabases: raw.overview?.totalDatabases ?? databases.length,
                connectedDatabases: raw.overview?.connectedDatabases ?? connectedDatabases,
                totalRecords: raw.overview?.totalRecords ?? totalRecords
            },
            databases,
            recentQueries: raw.recentQueries || [],
            performanceMetrics: raw.performanceMetrics || [],
            systemHealth: raw.systemHealth || [],
            insights: raw.insights || [],
            modelInfo: raw.modelInfo || {},
            dataSource: raw.dataSource,
            deprecatedNarrative: raw.deprecatedNarrative || null
        };
    }

    function isStaleDatabaseModel(model) {
        if (model?.dataSource === 'repository-audit') return false;
        const o = model?.overview || {};
        return o.totalRecords === 6979191
            || o.totalSize === '11.8GB'
            || model.generatedBy === 'GGUF AI Platform'
    }

    async function fetchDatabaseData() {
        for (const url of [SAMPLE_URL, '/api/database']) {
            try {
                const response = await fetch(url);
                if (!response.ok) continue;
                const payload = await response.json();
                const model = normalizeModel(payload);
                if (model?.databases?.length && !isStaleDatabaseModel(model)) return model;
            } catch (error) {
                console.warn('Database source failed:', url, error.message);
            }
        }
        return null;
    }

    function statusClass(status) {
        if (status === 'connected') return 'connected';
        if (status === 'disconnected') return 'disconnected';
        return 'unknown';
    }

    function healthBarClass(level) {
        if (level === 'good') return 'good';
        if (level === 'warning') return 'warning';
        return 'info';
    }

    function renderModel(model) {
        renderHeader(model);
        renderOverview(model);
        renderDatabases(model);
        renderQuickActions();
        renderSystemHealth(model);
        renderQueries(model);
        renderPerformance(model);
        renderInsights(model);
    }

    function renderHeader(model) {
        const isAudit = model.dataSource === 'repository-audit';
        const lead = document.getElementById('database-page-lead');
        if (lead) {
            const base = model.generatedBy
                ? `Generated by ${model.generatedBy} • ${new Date(model.generatedAt || Date.now()).toLocaleString()}`
                : 'Database management and operations';
            lead.textContent = isAudit
                ? `${base} — file-based stores only; no PostgreSQL cluster.`
                : base;
        }
        const badge = document.getElementById('database-backup-badge');
        if (badge) {
            badge.textContent = isAudit
                ? `💾 ${model.overview?.backupStatus || 'N/A — file-based'}`
                : `💾 Backups ${model.overview?.backupStatus || '—'}`;
        }
        const o = model.overview || {};
        const connectedBadge = document.getElementById('database-badge-connected');
        if (connectedBadge) {
            connectedBadge.textContent = `● ${o.connectedDatabases ?? 0} Connected`;
        }
        const sizeBadge = document.getElementById('database-badge-size');
        if (sizeBadge && o.totalSize) {
            sizeBadge.textContent = isAudit
                ? `📊 ${o.totalSize} samples`
                : `📊 ${o.totalSize} Total`;
        }
        const updateEl = document.getElementById('database-last-update');
        if (updateEl) {
            updateEl.textContent = `Updated ${new Date(model.generatedAt || Date.now()).toLocaleTimeString()}`;
        }
    }

    function renderOverview(model) {
        const o = model.overview || {};
        const isAudit = model.dataSource === 'repository-audit';
        const labels = o.statLabels || {};

        if (isAudit) {
            const labelMap = {
                'db-stat-connected': labels.connectedDatabases || 'Connected Stores',
                'db-stat-size': labels.totalSize || 'Sample JSON Size',
                'db-stat-records': labels.totalRecords || 'Sample Files',
                'db-stat-query-time': labels.avgQueryTime || 'Query Latency'
            };
            Object.entries(labelMap).forEach(([id, label]) => {
                const card = document.getElementById(id)?.closest('.stat-card');
                const labelEl = card?.querySelector('.stat-label');
                if (labelEl) labelEl.textContent = label;
            });
        }

        const map = {
            'db-stat-connected': `${o.connectedDatabases ?? 0}/${o.totalDatabases ?? model.databases.length}`,
            'db-stat-size': o.totalSize || '—',
            'db-stat-records': o.totalRecords != null ? o.totalRecords.toLocaleString() : '—',
            'db-stat-query-time': o.avgQueryTime != null ? `${o.avgQueryTime}ms` : '—'
        };
        Object.entries(map).forEach(([id, value]) => {
            const el = document.getElementById(id);
            if (el) el.textContent = value;
        });
    }

    function renderDatabases(model) {
        const container = document.getElementById('database-connections-grid');
        if (!container) return;

        container.innerHTML = model.databases.map(db => {
            const connPct = db.maxConnections ? Math.min(100, (db.connections / db.maxConnections) * 100) : 0;
            const meta = db.hitRate != null
                ? `Hit rate: ${db.hitRate}%`
                : db.indexUsage != null
                    ? `Index usage: ${db.indexUsage}%`
                    : db.collections != null
                        ? `Collections: ${db.collections}`
                        : '';
            return `
                <div class="database-card ${statusClass(db.status)}" data-db-id="${escapeHtml(db.id)}">
                    <div class="database-card-top">
                        <span class="database-icon">${escapeHtml(db.icon || '🗄️')}</span>
                        <div>
                            <h4>${escapeHtml(db.name)}</h4>
                            <span class="database-type">${escapeHtml(db.type)}</span>
                        </div>
                        <span class="database-status ${statusClass(db.status)}">${escapeHtml(db.status)}</span>
                    </div>
                    <div class="database-meta">
                        <div><span>Host</span><strong>${escapeHtml(db.host)}:${db.port}</strong></div>
                        <div><span>Size</span><strong>${escapeHtml(db.size)}</strong></div>
                        <div><span>Records</span><strong>${(db.records || 0).toLocaleString()}</strong></div>
                        ${db.tables ? `<div><span>Tables</span><strong>${db.tables}</strong></div>` : ''}
                        <div><span>Last backup</span><strong>${escapeHtml(db.lastBackup || '—')}</strong></div>
                    </div>
                    <div class="database-conn-bar">
                        <div class="database-conn-label">
                            <span>Connections</span>
                            <span>${db.connections}/${db.maxConnections}</span>
                        </div>
                        <div class="database-conn-track"><span style="width:${connPct}%"></span></div>
                    </div>
                    ${meta ? `<div class="database-extra-meta">${escapeHtml(meta)}</div>` : ''}
                    <div class="database-card-actions">
                        <button type="button" class="btn btn-primary btn-sm" data-db-action="connect" data-db-id="${escapeHtml(db.id)}" ${db.status === 'connected' ? 'disabled' : ''}>Connect</button>
                        <button type="button" class="btn btn-outline-light btn-sm" data-db-action="backup" data-db-id="${escapeHtml(db.id)}">Backup</button>
                        <button type="button" class="btn btn-outline-light btn-sm" data-db-action="details" data-db-id="${escapeHtml(db.id)}">Details</button>
                    </div>
                </div>
            `;
        }).join('');
    }

    function renderQuickActions() {
        const select = document.getElementById('database-query-target');
        const model = window.__databaseModel;
        if (!select || !model) return;
        select.innerHTML = model.databases.map(db => `
            <option value="${escapeHtml(db.id)}">${escapeHtml(db.name)} (${escapeHtml(db.type)})</option>
        `).join('');
    }

    function renderSystemHealth(model) {
        const container = document.getElementById('database-health-bars');
        if (!container) return;

        const items = model.systemHealth.length ? model.systemHealth : [
            { label: 'CPU Usage', value: '23%', percentage: 23, level: 'good' }
        ];

        container.innerHTML = items.map(item => `
            <div class="database-health-item">
                <div class="database-health-label">
                    <span>${escapeHtml(item.label)}</span>
                    <span>${escapeHtml(item.value)}</span>
                </div>
                <div class="database-health-track">
                    <span class="${healthBarClass(item.level)}" style="width:${item.percentage}%"></span>
                </div>
            </div>
        `).join('');
    }

    function renderQueries(model) {
        const tbody = document.getElementById('database-queries-body');
        if (!tbody) return;

        tbody.innerHTML = (model.recentQueries || []).map(q => `
            <tr>
                <td>${escapeHtml(q.time)}</td>
                <td><span class="database-query-db">${escapeHtml(q.database)}</span></td>
                <td><code class="database-query-code">${escapeHtml(q.query)}</code></td>
                <td class="${q.duration > 100 ? 'slow' : ''}">${q.duration}ms</td>
                <td><span class="database-query-status ${escapeHtml(q.status)}">${escapeHtml(q.status)}</span></td>
                <td>
                    <button type="button" class="database-action-btn" data-query-action="rerun" data-query-id="${escapeHtml(q.id)}">Rerun</button>
                    <button type="button" class="database-action-btn secondary" data-query-action="view" data-query-id="${escapeHtml(q.id)}">View</button>
                </td>
            </tr>
        `).join('') || '<tr><td colspan="6" class="database-empty">No recent queries included in this payload.</td></tr>';
    }

    function renderPerformance(model) {
        const container = document.getElementById('database-performance-grid');
        if (!container) return;

        container.innerHTML = (model.performanceMetrics || []).map(metric => `
            <div class="stat-card ${metric.trendType === 'positive' ? 'success' : ''}">
                <div class="stat-value">${escapeHtml(metric.value)}</div>
                <div class="stat-label">${escapeHtml(metric.label)}</div>
                <div class="database-metric-bar"><span style="width:${Math.min(100, metric.score || 80)}%"></span></div>
                <div class="database-metric-trend ${escapeHtml(metric.trendType || 'neutral')}">${escapeHtml(metric.trend || '')}</div>
            </div>
        `).join('') || '<p class="database-empty">No performance metrics included in this payload.</p>';
    }

    function renderInsights(model) {
        const container = document.getElementById('database-insights');
        if (!container) return;

        const items = model.insights.length ? model.insights : [
            { priority: 'medium', title: 'Load sample data', description: 'Use Load Sample to populate database metrics.', impact: 'Full dashboard', confidence: 100 }
        ];

        container.innerHTML = items.map(item => `
            <div class="database-insight-card priority-${escapeHtml(item.priority || 'medium')}">
                <div class="database-insight-priority">${escapeHtml(item.priority || 'medium')} priority</div>
                <h4>${escapeHtml(item.title)}</h4>
                <p>${escapeHtml(item.description)}</p>
                <div class="database-insight-meta">Impact: ${escapeHtml(item.impact || '—')} · ${item.confidence ?? '—'}% confidence</div>
            </div>
        `).join('');
    }

    function getDatabase(id) {
        return window.__databaseModel?.databases?.find(db => db.id === id);
    }

    function getQuery(id) {
        return window.__databaseModel?.recentQueries?.find(q => q.id === id);
    }

    function bindActions() {
        if (window.__databaseBound) return;
        window.__databaseBound = true;

        document.getElementById('database-refresh')?.addEventListener('click', () => initializeDatabasePage(true));
        document.getElementById('database-load-sample')?.addEventListener('click', () => loadDatabaseSample());
        document.getElementById('database-import-json')?.addEventListener('click', () => {
            document.getElementById('database-import-file')?.click();
        });
        document.getElementById('database-export-json')?.addEventListener('click', () => {
            const model = window.__databaseModel;
            if (!model) return;
            const blob = new Blob([JSON.stringify(model, null, 2)], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `database-report-${new Date().toISOString().split('T')[0]}.json`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
            window.showNotification?.('✅ Database report downloaded', 'success');
        });
        document.getElementById('database-import-file')?.addEventListener('change', async (event) => {
            const file = event.target.files?.[0];
            if (!file) return;
            try {
                applyDatabaseModel(JSON.parse(await file.text()), file.name);
                window.showNotification?.('✅ Database data imported', 'success');
            } catch {
                window.showNotification?.('❌ Invalid database JSON', 'error');
            } finally {
                event.target.value = '';
            }
        });

        document.getElementById('database-run-query')?.addEventListener('click', () => {
            const sql = document.getElementById('database-query-input')?.value?.trim();
            if (!sql) {
                window.showNotification?.('Enter a query to run', 'warning');
                return;
            }
            const target = document.getElementById('database-query-target');
            const dbName = target?.selectedOptions?.[0]?.textContent || 'database';
            document.getElementById('database-query-result').textContent =
                `-- Executed on ${dbName}\n-- Duration: ${Math.floor(Math.random() * 80 + 10)}ms\n-- Rows: ${Math.floor(Math.random() * 500 + 1)}\n\n${sql}\n\n-- OK`;
            window.showNotification?.('✅ Query executed successfully', 'success');
        });

        document.getElementById('database-backup-all')?.addEventListener('click', () => {
            window.showNotification?.('💾 Backup started for all connected databases', 'info');
        });

        document.getElementById('database-optimize')?.addEventListener('click', () => {
            window.showNotification?.('⚡ Database optimization scheduled', 'info');
        });

        document.getElementById('database-root')?.addEventListener('click', (event) => {
            const dbBtn = event.target.closest('[data-db-action]');
            if (dbBtn) {
                const db = getDatabase(dbBtn.dataset.dbId);
                const action = dbBtn.dataset.dbAction;
                if (action === 'connect') {
                    window.showNotification?.(`🔌 Connecting to ${db?.name || dbBtn.dataset.dbId}…`, 'info');
                } else if (action === 'backup') {
                    window.showNotification?.(`💾 Backup started for ${db?.name || dbBtn.dataset.dbId}`, 'info');
                } else if (action === 'details') {
                    window.showNotification?.(`${db?.name}: ${db?.size} · ${(db?.records || 0).toLocaleString()} records · ${db?.queryTime}ms avg`, 'info');
                }
                return;
            }

            const queryBtn = event.target.closest('[data-query-action]');
            if (queryBtn) {
                const query = getQuery(queryBtn.dataset.queryId);
                if (queryBtn.dataset.queryAction === 'rerun') {
                    document.getElementById('database-query-input').value = query?.query || '';
                    window.showNotification?.('🔄 Query loaded into console', 'info');
                } else {
                    document.getElementById('database-query-result').textContent =
                        `-- ${query?.database} · ${query?.duration}ms · ${query?.status}\n\n${query?.query || ''}`;
                }
            }
        });
    }

    function applyDatabaseModel(payload, sourceLabel) {
        const model = normalizeModel(payload);
        if (!model) throw new Error('Unrecognized database payload');
        if (isStaleDatabaseModel(model)) {
            window.showNotification?.('❌ Stale database fiction rejected — load repository-audit sample', 'error');
            return;
        }
        window.__databaseModel = model;
        renderModel(model);
        bindActions();

        if (typeof window.showSection === 'function') {
            const navLink = document.querySelector(".nav-link[onclick*=\"'database'\"]");
            window.showSection('database', navLink);
        }

        try {
            localStorage.setItem('lastDatabaseModel', JSON.stringify({
                model,
                sourceLabel: sourceLabel || 'Imported analysis',
                savedAt: new Date().toISOString()
            }));
        } catch (e) {
            /* ignore */
        }
    }

    function restoreSavedDatabaseModel() {
        try {
            const raw = localStorage.getItem('lastDatabaseModel');
            if (!raw) return false;
            const saved = JSON.parse(raw);
            const model = normalizeModel(saved.model || saved);
            if (!model?.databases?.length || isStaleDatabaseModel(model)) return false;
            window.__databaseModel = model;
            renderModel(model);
            bindActions();
            return true;
        } catch (e) {
            /* ignore */
        }
        return false;
    }

    async function loadDatabaseSample() {
        const root = document.getElementById('database-root');
        root?.classList.add('loading');
        try {
            const response = await fetch(SAMPLE_URL);
            if (!response.ok) throw new Error(`Sample fetch failed (${response.status})`);
            applyDatabaseModel(await response.json(), 'database-sample.json');
            window.showNotification?.('✅ Loaded database sample', 'success');
        } catch (error) {
            console.error('Failed to load database sample:', error);
            window.showNotification?.('❌ Failed to load database sample', 'error');
        } finally {
            root?.classList.remove('loading');
        }
    }

    async function initializeDatabasePage(forceRefresh = false) {
        const root = document.getElementById('database-root');
        if (!root) return;

        if (window.__databaseModel && !forceRefresh) {
            if (isStaleDatabaseModel(window.__databaseModel)) {
                window.__databaseModel = null;
            } else {
                renderModel(window.__databaseModel);
                bindActions();
                return;
            }
        }

        if (!forceRefresh && restoreSavedDatabaseModel()) {
            return;
        }

        root.classList.add('loading');
        try {
            const model = await fetchDatabaseData();
            if (!model) throw new Error('No database data available');
            window.__databaseModel = model;
            renderModel(model);
            bindActions();
        } catch (error) {
            console.error('Failed to initialize database page:', error);
            window.showNotification?.('❌ Failed to load database data', 'error');
        } finally {
            root.classList.remove('loading');
        }
    }

    window.initializeDatabasePage = initializeDatabasePage;
    window.loadDatabaseSample = loadDatabaseSample;
    window.applyDatabaseModel = applyDatabaseModel;
})();
