/**
 * Stripe Setup Script
 * This script helps you set up Stripe for the AI Coding Intelligence Dashboard
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log('🚀 AI Coding Intelligence Dashboard - Stripe Setup');
console.log('===================================================\n');

console.log('📋 To get started, you need a Stripe account:');
console.log('1. Go to https://stripe.com and sign up for a free account');
console.log('2. Navigate to https://dashboard.stripe.com/apikeys');
console.log('3. Copy your test publishable key and secret key\n');

const questions = [
    {
        key: 'STRIPE_PUBLIC_KEY',
        question: 'Enter your Stripe publishable key (pk_test_...): ',
        placeholder: 'pk_test_your_publishable_key_here'
    },
    {
        key: 'STRIPE_SECRET_KEY',
        question: 'Enter your Stripe secret key (sk_test_...): ',
        placeholder: 'sk_test_your_secret_key_here'
    },
    {
        key: 'STRIPE_WEBHOOK_SECRET',
        question: 'Enter your Stripe webhook secret (whsec_...) or press Enter to skip: ',
        placeholder: '',
        optional: true
    },
    {
        key: 'APP_URL',
        question: 'Enter your application URL (default: http://localhost:9000): ',
        placeholder: 'http://localhost:9000',
        default: 'http://localhost:9000'
    }
];

const answers = {};

async function askQuestion(index) {
    if (index >= questions.length) {
        rl.close();
        generateEnvFile();
        createStripeProducts();
        return;
    }

    const q = questions[index];
    
    rl.question(q.question, (answer) => {
        answers[q.key] = answer || q.default || q.placeholder;
        askQuestion(index + 1);
    });
}

function generateEnvFile() {
    const envContent = `# AI Coding Intelligence Dashboard - Environment Configuration
# Generated by Stripe setup script

# Server Configuration
PORT=3000
NODE_ENV=development

# Application URLs
APP_URL=${answers.APP_URL}

# Stripe Configuration
STRIPE_PUBLIC_KEY=${answers.STRIPE_PUBLIC_KEY}
STRIPE_SECRET_KEY=${answers.STRIPE_SECRET_KEY}
STRIPE_WEBHOOK_SECRET=${answers.STRIPE_WEBHOOK_SECRET || 'whsec_your_webhook_secret_here'}

# Stripe Price IDs (Will be created below)
STRIPE_BASIC_PRICE_ID=
STRIPE_PRO_PRICE_ID=
STRIPE_ENTERPRISE_PRICE_ID=

# Subscription Configuration
ENABLE_SUBSCRIPTIONS=true
TRIAL_PERIOD_DAYS=14
`;

    const envPath = path.join(__dirname, '../.env');
    
    // Check if .env already exists
    if (fs.existsSync(envPath)) {
        console.log('\n⚠️  .env file already exists. Skipping creation.');
        console.log('📝 Please update your existing .env file with the following values:');
        console.log(envContent);
    } else {
        fs.writeFileSync(envPath, envContent);
        console.log('\n✅ .env file created successfully!');
    }
}

async function createStripeProducts() {
    console.log('\n📦 Next steps to create Stripe products and prices:');
    console.log('1. Go to https://dashboard.stripe.com/products');
    console.log('2. Create the following products:');
    
    const products = [
        {
            name: 'Basic Plan - AI Coding Intelligence',
            description: 'Perfect for individual developers',
            price: 29,
            features: ['100 scans/month', 'Basic code analysis', 'Email support', 'Standard reports']
        },
        {
            name: 'Pro Plan - AI Coding Intelligence',
            description: 'For professional developers and growing teams',
            price: 79,
            features: ['Unlimited scans', 'Advanced AI analysis', 'Priority support', 'API access', 'Advanced reports']
        },
        {
            name: 'Enterprise Plan - AI Coding Intelligence',
            description: 'For large teams and enterprise organizations',
            price: 199,
            features: ['Everything in Pro', 'Dedicated support', 'SLA guarantees', 'Custom development', 'Team collaboration']
        }
    ];

    products.forEach((product, index) => {
        console.log(`\n   ${index + 1}. ${product.name}`);
        console.log(`      Price: $${product.price}/month`);
        console.log(`      Description: ${product.description}`);
        console.log(`      Features: ${product.features.join(', ')}`);
    });

    console.log('\n3. For each product, create a monthly recurring price');
    console.log('4. Copy the Price IDs and update your .env file:');
    console.log('   STRIPE_BASIC_PRICE_ID=price_xxxxx');
    console.log('   STRIPE_PRO_PRICE_ID=price_xxxxx');
    console.log('   STRIPE_ENTERPRISE_PRICE_ID=price_xxxxx');

    console.log('\n🔗 Webhook Setup:');
    console.log('1. Go to https://dashboard.stripe.com/webhooks');
    console.log('2. Add webhook endpoint: https://your-domain.com/api/webhook');
    console.log('3. Select events to listen for:');
    console.log('   - checkout.session.completed');
    console.log('   - customer.subscription.updated');
    console.log('   - customer.subscription.deleted');
    console.log('   - invoice.payment_succeeded');
    console.log('   - invoice.payment_failed');
    console.log('4. Copy the webhook signing secret and update STRIPE_WEBHOOK_SECRET in .env');

    console.log('\n🎉 Setup complete! You can now start the server with: npm start');
}

// Start asking questions
askQuestion(0);