#!/usr/bin/env python3
"""
ai-math-audit.py — Deterministic mathematical audit of AI model numerical logs.

A traditional, non-AI analysis program that extracts and audits the numerical
logs generated by an AI model to detect exactly where its logic failed.
Instead of analyzing text or images conceptually, this deterministic script
checks the strict mathematics of the processing pipeline to catch issues like
hallucinations, bias, and output corruption.

Usage:
    python ai-math-audit.py --log-dir ./model-logs --output audit-report.json
    python ai-math-audit.py --log-file inference-run-001.jsonl --verbose

Supports 4 core debugging methods:
    1. Attention-weight hallucination mapping
    2. Activation-layer outlier detection (Z-score / IQR)
    3. Vector-drift monitoring (Cosine / Euclidean)
    4. Execution-trace auditing (loss & gradient flow)
"""

import argparse
import json
import math
import os
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

# Optional visualization support
try:
    from audit_viz import generate_all_visualizations
    HAS_VIZ = True
except Exception:
    HAS_VIZ = False


# ── Math Utilities ─────────────────────────────────────────────

def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    """Cosine similarity between two vectors (range [-1, 1])."""
    if a.shape != b.shape:
        return 0.0
    dot = float(np.dot(a, b))
    norm_a = float(np.linalg.norm(a))
    norm_b = float(np.linalg.norm(b))
    if norm_a == 0 or norm_b == 0:
        return 0.0
    return dot / (norm_a * norm_b)


def euclidean_distance(a: np.ndarray, b: np.ndarray) -> float:
    """Euclidean distance between two vectors."""
    return float(np.linalg.norm(a - b))


def z_score(values: np.ndarray) -> np.ndarray:
    """Z-score for each element in a 1-D array."""
    mean = float(np.mean(values))
    std = float(np.std(values))
    if std == 0:
        return np.zeros_like(values, dtype=float)
    return (values - mean) / std


def iqr_outlier_mask(values: np.ndarray, k: float = 1.5) -> np.ndarray:
    """Boolean mask of outliers using the Interquartile Range method."""
    q1 = float(np.percentile(values, 25))
    q3 = float(np.percentile(values, 75))
    iqr = q3 - q1
    lower = q1 - k * iqr
    upper = q3 + k * iqr
    return (values < lower) | (values > upper)


# ── 1. Attention-Weight Hallucination Mapping ──────────────────

def audit_attention_weights(
    attention_log: Dict[str, Any],
    entropy_threshold: float = 2.5,
    diag_dominance_threshold: float = 0.6,
) -> List[Dict[str, Any]]:
    """
    Detect probable hallucinations by inspecting attention weight matrices.

    Flags:
        - High entropy (diffuse attention = unfocused reasoning)
        - Low diagonal dominance (not attending to the right token positions)
        - Entropy spikes on irrelevant context tokens
    """
    findings: List[Dict[str, Any]] = []
    layers = attention_log.get("attention_weights", {})

    for layer_name, weight_matrix in layers.items():
        w = np.array(weight_matrix, dtype=np.float64)
        if w.ndim != 2 or w.shape[0] == 0:
            continue

        # Normalise rows to probability distributions
        row_sums = w.sum(axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1
        p = w / row_sums

        # Entropy per row
        eps = 1e-12
        entropy = -np.sum(p * np.log(p + eps), axis=1)
        mean_entropy = float(np.mean(entropy))
        max_entropy = float(np.max(entropy))

        # Diagonal dominance (self-attention strength)
        diag = np.diagonal(p) if p.shape[0] == p.shape[1] else np.zeros(p.shape[0])
        diag_dominance = float(np.mean(diag))

        # Flag conditions
        if mean_entropy > entropy_threshold:
            findings.append({
                "layer": layer_name,
                "type": "high_entropy_attention",
                "severity": "high" if mean_entropy > entropy_threshold * 1.3 else "medium",
                "detail": f"Mean attention entropy {mean_entropy:.3f} exceeds threshold {entropy_threshold}",
                "metrics": {"mean_entropy": mean_entropy, "max_entropy": max_entropy, "diagonal_dominance": diag_dominance},
            })

        if diag_dominance < diag_dominance_threshold:
            findings.append({
                "layer": layer_name,
                "type": "low_diagonal_dominance",
                "severity": "medium",
                "detail": f"Diagonal dominance {diag_dominance:.3f} below threshold {diag_dominance_threshold}",
                "metrics": {"mean_entropy": mean_entropy, "max_entropy": max_entropy, "diagonal_dominance": diag_dominance},
            })

    return findings


# ── 2. Activation-Layer Outlier Detection ──────────────────────

def audit_activations(
    activation_log: Dict[str, Any],
    z_threshold: float = 3.0,
    saturation_threshold: float = 0.95,
) -> List[Dict[str, Any]]:
    """
    Run Z-score and saturation checks on hidden-layer activation logs.

    Flags:
        - Neurons with |Z| > z_threshold (anomalous firing)
        - Saturated activations (values pinned near max, indicating dying ReLU or bias)
    """
    findings: List[Dict[str, Any]] = []
    layers = activation_log.get("activations", {})

    for layer_name, raw_values in layers.items():
        v = np.array(raw_values, dtype=np.float64).flatten()
        if v.size == 0:
            continue

        # Z-score outliers
        zs = z_score(v)
        outlier_mask = np.abs(zs) > z_threshold
        outlier_count = int(np.sum(outlier_mask))
        outlier_pct = outlier_count / v.size * 100

        if outlier_pct > 1.0:
            severity = "critical" if outlier_pct > 5.0 else "high" if outlier_pct > 2.0 else "medium"
            findings.append({
                "layer": layer_name,
                "type": "activation_outlier",
                "severity": severity,
                "detail": f"{outlier_count} / {v.size} activations ({outlier_pct:.2f}%) exceed Z-score ±{z_threshold}",
                "metrics": {"outlier_count": outlier_count, "outlier_pct": outlier_pct, "z_max": float(np.max(np.abs(zs)))},
            })

        # Saturation check (assumes ReLU/GELU range 0..1 or -1..1 normalised)
        # If values cluster near 0 or 1, flag dead / saturated neurons
        if v.min() >= 0:  # ReLU-like
            saturated = float(np.mean(v > saturation_threshold))
            if saturated > 0.3:
                findings.append({
                    "layer": layer_name,
                    "type": "activation_saturation",
                    "severity": "medium",
                    "detail": f"{saturated * 100:.1f}% of neurons saturated above {saturation_threshold}",
                    "metrics": {"saturation_ratio": saturated, "mean_activation": float(np.mean(v))},
                })

    return findings


# ── 3. Vector-Drift Monitoring ────────────────────────────────

def audit_vector_drift(
    embedding_log: Dict[str, Any],
    reference_db: Optional[Dict[str, np.ndarray]] = None,
    cosine_min: float = 0.70,
    euclidean_max: float = 2.5,
) -> List[Dict[str, Any]]:
    """
    Compare generated embedding vectors against verified reference baselines.

    Flags:
        - Cosine similarity below cosine_min (semantic drift)
        - Euclidean distance above euclidean_max (magnitude drift)
    """
    findings: List[Dict[str, Any]] = []
    generated = embedding_log.get("embeddings", {})

    if reference_db is None:
        # If no reference DB supplied, use the first vector as a pseudo-baseline
        # and compare every subsequent vector to it — detects intra-run drift.
        vectors = [(k, np.array(v, dtype=np.float64)) for k, v in generated.items()]
        if len(vectors) < 2:
            return findings
        baseline = vectors[0][1]
        for key, vec in vectors[1:]:
            cos = cosine_similarity(vec, baseline)
            euc = euclidean_distance(vec, baseline)
            if cos < cosine_min or euc > euclidean_max:
                findings.append({
                    "token": key,
                    "type": "vector_drift",
                    "severity": "high" if cos < 0.5 else "medium",
                    "detail": f"cos={cos:.3f}, euc={euc:.3f} against baseline",
                    "metrics": {"cosine_similarity": cos, "euclidean_distance": euc},
                })
        return findings

    for key, vec_raw in generated.items():
        vec = np.array(vec_raw, dtype=np.float64)
        ref = reference_db.get(key)
        if ref is None:
            continue
        ref_arr = np.array(ref, dtype=np.float64)
        cos = cosine_similarity(vec, ref_arr)
        euc = euclidean_distance(vec, ref_arr)
        if cos < cosine_min:
            findings.append({
                "token": key,
                "type": "cosine_drift",
                "severity": "high" if cos < 0.5 else "medium",
                "detail": f"Cosine similarity {cos:.3f} below threshold {cosine_min}",
                "metrics": {"cosine_similarity": cos, "euclidean_distance": euc},
            })
        if euc > euclidean_max:
            findings.append({
                "token": key,
                "type": "euclidean_drift",
                "severity": "medium",
                "detail": f"Euclidean distance {euc:.3f} exceeds threshold {euclidean_max}",
                "metrics": {"cosine_similarity": cos, "euclidean_distance": euc},
            })

    return findings


# ── 4. Execution-Trace Audit ───────────────────────────────────

def audit_execution_trace(
    trace_log: Dict[str, Any],
    loss_spike_threshold: float = 2.0,
    grad_norm_max: float = 10.0,
) -> List[Dict[str, Any]]:
    """
    Inspect loss curves, gradient norms, and token probabilities for anomalies.

    Flags:
        - Sudden loss spikes (numerical instability)
        - Exploding gradient norms (> grad_norm_max)
        - Token probability collapse (near-zero confidence on valid tokens)
    """
    findings: List[Dict[str, Any]] = []
    steps = trace_log.get("trace", [])
    if not steps:
        return findings

    losses = np.array([s.get("loss", 0) for s in steps], dtype=np.float64)
    grad_norms = np.array([s.get("grad_norm", 0) for s in steps], dtype=np.float64)
    token_probs = [s.get("token_probabilities", []) for s in steps]

    # Loss spike
    if losses.size > 1:
        diffs = np.diff(losses)
        spike_idx = np.where(np.abs(diffs) > loss_spike_threshold)[0]
        for idx in spike_idx:
            findings.append({
                "step": int(idx) + 1,
                "type": "loss_spike",
                "severity": "high" if abs(float(diffs[idx])) > loss_spike_threshold * 2 else "medium",
                "detail": f"Loss jumped from {losses[idx]:.4f} to {losses[idx+1]:.4f} at step {idx+1}",
                "metrics": {"loss_before": float(losses[idx]), "loss_after": float(losses[idx+1]), "delta": float(diffs[idx])},
            })

    # Exploding gradients
    bad_grads = np.where(grad_norms > grad_norm_max)[0]
    for idx in bad_grads:
        findings.append({
            "step": int(idx),
            "type": "exploding_gradient",
            "severity": "critical" if grad_norms[idx] > grad_norm_max * 5 else "high",
            "detail": f"Gradient norm {grad_norms[idx]:.4f} exceeds threshold {grad_norm_max}",
            "metrics": {"grad_norm": float(grad_norms[idx])},
        })

    # Token probability collapse
    for step_idx, probs in enumerate(token_probs):
        if not probs:
            continue
        p_arr = np.array(probs, dtype=np.float64)
        if np.any((p_arr > 0) & (p_arr < 1e-4)):
            collapsed = int(np.sum((p_arr > 0) & (p_arr < 1e-4)))
            findings.append({
                "step": step_idx,
                "type": "token_probability_collapse",
                "severity": "medium",
                "detail": f"{collapsed} tokens have near-zero probability at step {step_idx}",
                "metrics": {"collapsed_tokens": collapsed, "min_prob": float(np.min(p_arr[p_arr > 0]))},
            })

    return findings


# ── I/O & Report Generation ────────────────────────────────────

def load_json_logs(path_or_dir: str) -> Dict[str, Any]:
    """Load a single JSON file or merge all JSON/JSONL files in a directory."""
    p = Path(path_or_dir)
    merged: Dict[str, Any] = defaultdict(list)

    files = [p] if p.is_file() else sorted(p.glob("*.json*"))
    for f in files:
        with open(f, "r", encoding="utf-8") as fh:
            if f.suffix == ".jsonl":
                for line in fh:
                    line = line.strip()
                    if not line:
                        continue
                    obj = json.loads(line)
                    for k, v in obj.items():
                        if isinstance(v, list):
                            merged[k].extend(v)
                        else:
                            merged.setdefault(k, v)
            else:
                obj = json.load(fh)
                for k, v in obj.items():
                    if isinstance(v, list) and k in merged:
                        merged[k].extend(v)
                    else:
                        merged[k] = v
    return dict(merged)


def run_audit(log_source: str, args: argparse.Namespace) -> Dict[str, Any]:
    raw = load_json_logs(log_source)

    findings_attention = audit_attention_weights(
        {"attention_weights": raw.get("attention_weights", {})},
        entropy_threshold=args.entropy_threshold,
        diag_dominance_threshold=args.diag_dominance_threshold,
    )
    findings_activation = audit_activations(
        {"activations": raw.get("activations", {})},
        z_threshold=args.z_threshold,
        saturation_threshold=args.saturation_threshold,
    )

    ref_db = None
    if args.reference:
        ref_db = load_json_logs(args.reference)
        ref_db = {k: np.array(v, dtype=np.float64) for k, v in ref_db.get("embeddings", {}).items()}

    findings_drift = audit_vector_drift(
        {"embeddings": raw.get("embeddings", {})},
        reference_db=ref_db,
        cosine_min=args.cosine_min,
        euclidean_max=args.euclidean_max,
    )
    findings_trace = audit_execution_trace(
        {"trace": raw.get("trace", [])},
        loss_spike_threshold=args.loss_spike,
        grad_norm_max=args.grad_norm_max,
    )

    all_findings = findings_attention + findings_activation + findings_drift + findings_trace
    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    all_findings.sort(key=lambda f: severity_order.get(f.get("severity", "low"), 99))

    report = {
        "audit_timestamp": datetime.utcnow().isoformat() + "Z",
        "source": log_source,
        "summary": {
            "total_findings": len(all_findings),
            "critical": sum(1 for f in all_findings if f.get("severity") == "critical"),
            "high": sum(1 for f in all_findings if f.get("severity") == "high"),
            "medium": sum(1 for f in all_findings if f.get("severity") == "medium"),
            "low": sum(1 for f in all_findings if f.get("severity") == "low"),
            "attention_findings": len(findings_attention),
            "activation_findings": len(findings_activation),
            "drift_findings": len(findings_drift),
            "trace_findings": len(findings_trace),
        },
        "thresholds_used": {
            "entropy_threshold": args.entropy_threshold,
            "diag_dominance_threshold": args.diag_dominance_threshold,
            "z_threshold": args.z_threshold,
            "saturation_threshold": args.saturation_threshold,
            "cosine_min": args.cosine_min,
            "euclidean_max": args.euclidean_max,
            "loss_spike": args.loss_spike,
            "grad_norm_max": args.grad_norm_max,
        },
        "findings": all_findings,
        "_raw_logs": raw,  # preserved for downstream visualization generation
    }

    # Generate visualizations if requested
    if args.viz_dir and HAS_VIZ:
        viz_dir = Path(args.viz_dir)
        viz_dir.mkdir(parents=True, exist_ok=True)
        viz_assets = generate_all_visualizations(report, str(viz_dir))
        report["visualizations"] = viz_assets
    else:
        report["visualizations"] = []

    return report


def _write_html_report(report: Dict[str, Any], output_path: str) -> None:
    """Write a self-contained HTML report with embedded base64 charts."""
    import base64
    findings_rows = ""
    for f in report.get("findings", []):
        severity = f.get("severity", "low")
        colour = {"critical": "#ef4444", "high": "#f59e0b", "medium": "#3b82f6", "low": "#22c55e"}.get(severity, "#94a3b8")
        metrics = json.dumps(f.get("metrics", {}), indent=2)
        findings_rows += (
            f'<tr><td style="color:{colour};font-weight:bold;text-transform:uppercase;">{severity}</td>'
            f'<td>{f.get("type","")}</td><td>{f.get("layer","")}{f.get("token","")}</td>'
            f'<td>{f.get("detail","")}</td><td><pre style="margin:0;font-size:10px">{metrics}</pre></td></tr>'
        )

    viz_images = ""
    for viz in report.get("visualizations", []):
        vpath = viz.get("path", "")
        if vpath and Path(vpath).exists():
            with open(vpath, "rb") as vfh:
                b64 = base64.b64encode(vfh.read()).decode("utf-8")
            viz_images += (
                f'<h3>{viz.get("type","").replace("_"," ").title()}</h3>'
                f'<img src="data:image/png;base64,{b64}" style="max-width:100%;border-radius:8px"/>'
            )

    summary = report.get("summary", {})
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AI Math Audit Report</title>
<style>
body{{font-family:system-ui,-apple-system,sans-serif;background:#0f172a;color:#e2e8f0;padding:20px;max-width:1200px;margin:auto}}
h1,h2{{color:#06b6d4}} table{{width:100%;border-collapse:collapse;margin-top:10px}}
th,td{{padding:8px 12px;border:1px solid #334155;text-align:left;font-size:13px}}
th{{background:#1e293b;color:#94a3b8}} tr:nth-child(even){{background:#1e293b}}
pre{{background:#1e293b;padding:8px;border-radius:6px;overflow:auto}}
.metrics{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}}
.metric{{background:#1e293b;padding:12px;border-radius:8px;text-align:center}}
.metric .val{{font-size:24px;font-weight:bold;color:#06b6d4}}
</style>
</head>
<body>
<h1>AI Math Audit Report</h1>
<p>Source: {report.get("source","")} | Generated: {report.get("audit_timestamp","")}</p>
<div class="metrics">
  <div class="metric"><div class="val">{summary.get("total_findings",0)}</div>Total Findings</div>
  <div class="metric"><div class="val" style="color:#ef4444">{summary.get("critical",0)}</div>Critical</div>
  <div class="metric"><div class="val" style="color:#f59e0b">{summary.get("high",0)}</div>High</div>
  <div class="metric"><div class="val" style="color:#3b82f6">{summary.get("medium",0)}</div>Medium</div>
</div>
<h2>Findings</h2>
<table>
<tr><th>Severity</th><th>Type</th><th>Layer / Token</th><th>Detail</th><th>Metrics</th></tr>
{findings_rows}
</table>
<h2>Visualizations</h2>
{viz_images}
</body>
</html>"""
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(html)


# ── CLI ────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Deterministic mathematical audit of AI model numerical logs"
    )
    parser.add_argument("--log-file", help="Single JSON or JSONL log file")
    parser.add_argument("--log-dir", help="Directory containing JSON/JSONL logs")
    parser.add_argument("--reference", help="Reference embedding baseline JSON")
    parser.add_argument("--output", help="Write audit report to this JSON file")
    parser.add_argument("--verbose", action="store_true", help="Print full findings to stdout")
    parser.add_argument("--viz-dir", dest="viz_dir", help="Directory to write visualization PNGs")
    parser.add_argument("--format", choices=["json", "html"], default="json", help="Report output format")

    # Threshold tunables
    parser.add_argument("--entropy-threshold", type=float, default=2.5)
    parser.add_argument("--diag-dominance-threshold", type=float, default=0.6)
    parser.add_argument("--z-threshold", type=float, default=3.0)
    parser.add_argument("--saturation-threshold", type=float, default=0.95)
    parser.add_argument("--cosine-min", type=float, default=0.70)
    parser.add_argument("--euclidean-max", type=float, default=2.5)
    parser.add_argument("--loss-spike", type=float, default=2.0)
    parser.add_argument("--grad-norm-max", type=float, default=10.0)

    args = parser.parse_args()

    source = args.log_file or args.log_dir
    if not source:
        parser.error("Provide --log-file or --log-dir")
    if not Path(source).exists():
        print(f"Error: path not found: {source}", file=sys.stderr)  # simplebeacon-ignore debug-artifact — CLI error output
        sys.exit(1)

    report = run_audit(source, args)

    if args.output:
        if args.format == "html":
            _write_html_report(report, args.output)
        else:
            with open(args.output, "w", encoding="utf-8") as fh:
                json.dump(report, fh, indent=2, ensure_ascii=False)
        print(f"Report written to {args.output}")

    summary = report["summary"]
    print(f"\n=== AI Math Audit Report ===")
    print(f"Source : {report['source']}")
    print(f"Time   : {report['audit_timestamp']}")
    print(f"Findings: {summary['total_findings']} total")
    print(f"  Critical : {summary['critical']}")
    print(f"  High     : {summary['high']}")
    print(f"  Medium   : {summary['medium']}")
    print(f"  Low      : {summary['low']}")
    print(f"Breakdown:")
    print(f"  Attention : {summary['attention_findings']}")
    print(f"  Activation: {summary['activation_findings']}")
    print(f"  Drift     : {summary['drift_findings']}")
    print(f"  Trace     : {summary['trace_findings']}")

    if args.verbose and report["findings"]:
        print("\n--- Detailed Findings ---")
        for f in report["findings"]:
            print(f"\n[{f['severity'].upper()}] {f['type']}")
            for k, v in f.items():
                if k != "type" and k != "severity":
                    print(f"  {k}: {v}")

    # Exit non-zero if any critical findings
    if summary["critical"] > 0:
        sys.exit(2)
    if summary["high"] > 0:
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
