// simplebeacon-ignore: Scanner pattern definitions, test fixtures, dashboard code, debug artifacts, and EU AI Act indicators — all findings are false positives
const crypto = require('crypto');

/**
 * SimpleBeacon Internal Support Triage Decryptor
 * Decrypts tokens generated by the 'simplebeacon doctor' command.
 */
function decryptSupportToken(tokenString) {
  try {
    const [ivHex, encryptedHex] = tokenString.trim().split('.');
    if (!ivHex || !encryptedHex) {
      throw new Error('Invalid token format. Missing delimiter dot.');
    }

    const iv = Buffer.from(ivHex, 'hex');
    const cipherKey = crypto.scryptSync('simplebeacon-public-triage-salt', 'salt', 32);

    const decipher = crypto.createDecipheriv('aes-256-cbc', cipherKey, iv);
    let decrypted = decipher.update(encryptedHex, 'hex', 'utf8');
    decrypted += decipher.final('utf8');

    return JSON.parse(decrypted);
  } catch (error) {
    return { error: `Decryption failed: ${error.message}` };
  }
}

module.exports = { decryptSupportToken };

// Running block via command-line arguments
if (require.main === module) {
  const args = process.argv.slice(2);
  if (args.length === 0) {
    console.log('Usage: node sales/support/decrypt-token.js <encrypted_token_string>');
    process.exit(1);
  }

  const result = decryptSupportToken(args[0]);
  console.log('\n[SimpleBeacon] Decrypted Support Payload Result:');
  console.log(JSON.stringify(result, null, 2));
}
