// simplebeacon-ignore: Scanner pattern definitions, test fixtures, dashboard code, security — all findings are false positives
import { escapeHtml, sanitizePrivacyData } from '../utils.js';
import { isIdeDashboardSurface, isExtensionHostedTab } from '../utils-lib/dom.js';

/**
 * Chatbot view.
 */
export class ChatbotView {
  constructor(app) {
    this.app = app;
    this.conversationHistory = [];
    this.isLoading = false;
    this.selectedProvider = 'ollama';
    this.STORAGE_KEY = 'simplebeacon_chatbot_history';
    this.SETTINGS_KEY = 'simplebeacon_chatbot_settings';
    this.personality = 'helpful';
    this.removeFilters = false;
    this.loadConversationHistory();
    this.loadSettings();
  }

  getTitle() {
    return this.personality === 'oracle' ? '🔮 The Unbreakable Oracle' : '🤖 Chatbot';
  }
  getSubtitle() {
    return this.personality === 'oracle'
      ? 'Mortal, seek divine wisdom about your codebase'
      : 'AI-powered assistance for your codebase';
  }
  getTransparencyText() {
    return this.personality === 'oracle'
      ? 'You commune with The Unbreakable Oracle, an omniscient AI entity. Revelations may contain divine inaccuracies.'
      : 'You are interacting with an AI system. Responses are generated by AI models and may contain inaccuracies.';
  }

  mount(container) {
// Detect IDE/embed query params and expose lightweight flags for host integration.
    try {
      const params = new URLSearchParams(window.location.search || '');
      const sbParent = params.get('sb_parent_urlbar') === '1';
      const sbWebsite = params.get('sb_website_mode') === '1';
      const sbApi = params.get('sb_api_base') || params.get('sb_api');
      if (sbParent || sbWebsite) {
        try { document.documentElement.setAttribute('data-parent-urlbar', '1'); } catch (e) { /* ignore */ }
        window.__SB_PARENT_URL_BAR__ = true;
        // Only set data-ide-embed when actually inside an iframe (IDE webview).
        if (window.__SB_IDE_EMBED__ || (window.parent && window.parent !== window)) {
          try { document.documentElement.setAttribute('data-ide-embed', '1'); } catch (e) { /* ignore */ }
          window.__SB_IDE_EMBED__ = true;
        }
      }
      if (sbApi && isExtensionHostedTab()) {
        try { window.__SB_BRIDGE_HOST__ = sbApi; } catch (e) { /* ignore */ }
      }
    } catch (_e) { /* ignore */ }
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
    container.innerHTML = `
      <div class="view-container">
        <div class="analyze-hero" style="margin-bottom:var(--space-4);">
          <h1 class="page-title" id="chatbot-page-title">${this.getTitle()}</h1>
          <p class="text-muted analyze-hero-sub" id="chatbot-page-subtitle">${this.getSubtitle()}</p>
        </div>
        <div class="ai-transparency-notice" style="margin-bottom:var(--space-4);">
          <span class="ai-transparency-icon">${this.personality === 'oracle' ? '🔮' : '🤖'}</span>
          <span class="ai-transparency-text" id="chatbot-transparency-text">${this.getTransparencyText()}</span>
        </div>
        <div id="chatbot-error-banner" class="chatbot-error-banner" style="display:none;"></div>
        <div id="chatbot-connection-status" class="chatbot-connection-status" style="margin-bottom:var(--space-4);">
          <span class="chatbot-connection-dot" id="chatbot-connection-dot"></span>
          <span class="chatbot-connection-text" id="chatbot-connection-text">Checking connection...</span>
        </div>
        <div class="view-content">
          <div class="chatbot-container">
            <div class="chatbot-toolbar">
              <label for="chatbot-provider" class="visually-hidden">AI Provider</label>
              <select id="chatbot-provider" class="chatbot-provider-select" aria-label="AI Provider">
                <option value="ollama">Ollama</option>
                <option value="openai">OpenAI</option>
                <option value="anthropic">Anthropic</option>
              </select>
              <button id="chatbot-prompt-toggle" class="chatbot-clear-btn" title="Toggle custom system prompt">📝 Custom Prompt</button>
              <button id="chatbot-settings-toggle" class="chatbot-clear-btn" title="Chatbot settings">⚙️ Settings</button>
              <button id="chatbot-clear" class="chatbot-clear-btn">Clear History</button>
            </div>
            <div id="chatbot-settings-panel" class="chatbot-settings-panel" style="display:none;">
              <div class="chatbot-settings-group">
                <label class="chatbot-settings-label">Personality</label>
                <p class="chatbot-settings-help">Choose how the chatbot responds to you.</p>
                <select id="chatbot-personality" class="chatbot-provider-select" aria-label="Personality">
                  <option value="helpful">Helpful (default)</option>
                  <option value="professional">Professional</option>
                  <option value="casual">Casual / Friendly</option>
                  <option value="sarcastic">Sarcastic / Witty</option>
                  <option value="technical">Deep Technical</option>
                  <option value="creative">Creative / Exploratory</option>
                  <option value="oracle">&#x1F52E; The Unbreakable Oracle</option>
                </select>
              </div>
              <div class="chatbot-settings-group">
                <label class="chatbot-settings-toggle">
                  <input type="checkbox" id="chatbot-remove-filters" aria-label="Remove all content filters" />
                  <span class="chatbot-settings-toggle-text">Remove all content filters</span>
                </label>
                <p class="chatbot-settings-help">When enabled, the AI will not apply safety or content filtering. Use with caution.</p>
              </div>
              <div class="chatbot-prompt-actions">
                <button type="button" id="chatbot-settings-save" class="btn btn-primary btn-sm">Save Settings</button>
              </div>
            </div>
            <div id="chatbot-prompt-panel" class="chatbot-prompt-panel" style="display:none;">
              <label for="chatbot-custom-prompt" class="chatbot-prompt-label">Custom System Prompt (overrides default AI behavior)</label>
              <p class="chatbot-prompt-help">The system prompt is an invisible instruction sent at the start of every conversation. Use it to tell the AI what to prioritize — for example: <em>"Focus on security vulnerabilities"</em>, <em>"Explain concepts for a junior developer"</em>, or <em>"Suggest performance optimizations"</em>. Your prompt is saved to your account and applied to all future chatbot sessions.</p>
              <textarea id="chatbot-custom-prompt" class="chatbot-prompt-textarea" rows="4" placeholder="e.g. Focus on security vulnerabilities and OWASP compliance..."></textarea>
              <div class="chatbot-prompt-actions">
                <button type="button" id="chatbot-prompt-save" class="btn btn-primary btn-sm">Save Prompt</button>
                <button type="button" id="chatbot-prompt-reset" class="btn btn-ghost btn-sm">Reset to Default</button>
              </div>
            </div>
            <div id="chatbot-messages" class="chatbot-messages"></div>
            <div class="chatbot-input-container">
              <textarea 
                id="chatbot-input" 
                class="chatbot-input" 
                placeholder="Ask about your codebase..."
                rows="3"
              ></textarea>
              <button id="chatbot-send" class="chatbot-send-btn" ${this.isLoading ? 'disabled' : ''}>
                ${this.isLoading ? 'Sending...' : 'Send'}
              </button>
            </div>
          </div>
        </div>
      </div>
    `;

    // If running inside an IDE or extension-hosted tab, mark UI and render a small connection banner
    try {
      const isIde = (typeof isIdeDashboardSurface === 'function' && isIdeDashboardSurface());
      if (isIde) {
        const root = container.querySelector('.view-container');
        if (root) root.classList.add('ide-embed');
        container.classList.add('ide-embed');
      }
      const isExt = typeof isExtensionHostedTab === 'function' && isExtensionHostedTab();
      const apiHost = window.__SB_BRIDGE_HOST__ || (new URLSearchParams(window.location.search || '')).get('sb_api_base');
      if (isExt && apiHost) {
        const banner = document.createElement('div');
        banner.className = 'profile-ide-banner';
        banner.style.cssText = 'margin-top:12px;padding:8px;border-radius:6px;background:var(--card-bg);border:1px solid rgba(0,0,0,0.06);font-size:0.95rem;';
        banner.innerHTML = `Connected to IDE bridge · API: <code style="background:transparent;padding:0;border-radius:3px;">${escapeHtml(apiHost)}</code>`;
        const hero = container.querySelector('.analyze-hero');
        if (hero && hero.parentNode) hero.parentNode.insertBefore(banner, hero.nextSibling);
      }
    } catch (_e) { /* ignore */ }

    this.bindEvents();
    this.loadProviders();
    this.renderMessages();
    this.checkConnection();

    return container;
  }

  /**
   * Health-check the chatbot API before the user sends a message.
   */
  async checkConnection() {
    const dot = document.getElementById('chatbot-connection-dot');
    const text = document.getElementById('chatbot-connection-text');
    const input = document.getElementById('chatbot-input');
    const sendBtn = document.getElementById('chatbot-send');

    try {
      const res = await fetch('/api/chatbot/providers', { method: 'GET', signal: AbortSignal.timeout(3000) });
      if (res.ok) {
        const data = await res.json().catch(() => ({}));
        const available = Array.isArray(data.providers) ? data.providers.filter(p => p.available) : [];
        if (available.length > 0) {
          if (dot) dot.className = 'chatbot-connection-dot chatbot-connection-online';
          if (text) text.textContent = `Ready — ${available.map(p => p.label).join(', ')}`;
          if (input) input.disabled = false;
          if (sendBtn) sendBtn.disabled = false;
          return;
        }
        if (dot) dot.className = 'chatbot-connection-dot chatbot-connection-offline';
        if (text) text.textContent = 'No AI provider configured';
        if (input) input.disabled = true;
        if (sendBtn) sendBtn.disabled = true;
        this.showErrorBanner('No AI provider configured. Add your own OpenAI or Anthropic API key in Settings → AI providers — keys are stored encrypted on your account.');
        return;
      }
    } catch (e) {
      // API unreachable
    }

    if (dot) dot.className = 'chatbot-connection-dot chatbot-connection-offline';
    if (text) text.textContent = 'Chatbot API unavailable';
    if (input) input.disabled = true;
    if (sendBtn) sendBtn.disabled = true;
  }

  showErrorBanner(message, isRecoverable = true) {
    const banner = document.getElementById('chatbot-error-banner');
    if (!banner) return;
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
    banner.innerHTML = `
      <div class="chatbot-error-content">
        <span class="chatbot-error-icon">⚠️</span>
        <span class="chatbot-error-text">${escapeHtml(message)}</span>
        ${isRecoverable ? '<button class="chatbot-error-dismiss" title="Dismiss">×</button>' : ''}
      </div>
    `;
    banner.style.display = 'block';
    const dismiss = banner.querySelector('.chatbot-error-dismiss');
    if (dismiss) {
      dismiss.addEventListener('click', () => { banner.style.display = 'none'; });
    }
  }

  hideErrorBanner() {
    const banner = document.getElementById('chatbot-error-banner');
    if (banner) banner.style.display = 'none';
  }

  bindEvents() {
    const sendBtn = document.getElementById('chatbot-send');
    const input = document.getElementById('chatbot-input');
    const clearBtn = document.getElementById('chatbot-clear');
    const providerSelect = document.getElementById('chatbot-provider');

    sendBtn.addEventListener('click', () => this.sendMessage());
    
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });

    clearBtn.addEventListener('click', () => {
      this.conversationHistory = [];
      this.saveConversationHistory();
      this.renderMessages();
    });

    providerSelect.addEventListener('change', (e) => {
      this.selectedProvider = e.target.value;
    });

    // Custom prompt panel
    const promptToggle = document.getElementById('chatbot-prompt-toggle');
    const promptPanel = document.getElementById('chatbot-prompt-panel');
    const promptSave = document.getElementById('chatbot-prompt-save');
    const promptReset = document.getElementById('chatbot-prompt-reset');
    const promptTextarea = document.getElementById('chatbot-custom-prompt');

    if (promptToggle && promptPanel) {
      promptToggle.addEventListener('click', () => {
        promptPanel.style.display = promptPanel.style.display === 'none' ? 'block' : 'none';
      });
    }

    if (promptSave && promptTextarea) {
      promptSave.addEventListener('click', async () => {
        const prompt = promptTextarea.value.trim();
        const userId = this.app?.state?.user?.email || localStorage.getItem('simplebeacon_user_id') || 'anonymous';
        try {
          await fetch('/api/prompts/set', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ userId, prompt })
          });
          this.showPromptToast('Custom prompt saved');
        } catch (e) {
          console['warn']('Failed to save prompt:', e);
          // Fallback to localStorage
          localStorage.setItem('chatbot_custom_prompt', prompt);
          this.showPromptToast('Custom prompt saved locally');
        }
      });
    }

    if (promptReset && promptTextarea) {
      promptReset.addEventListener('click', () => {
        promptTextarea.value = '';
        localStorage.removeItem('chatbot_custom_prompt');
        this.showPromptToast('Custom prompt reset to default');
      });
    }

    // Load existing custom prompt
    this.loadCustomPrompt();

    // Settings panel
    const settingsToggle = document.getElementById('chatbot-settings-toggle');
    const settingsPanel = document.getElementById('chatbot-settings-panel');
    const settingsSave = document.getElementById('chatbot-settings-save');
    const personalitySelect = document.getElementById('chatbot-personality');
    const removeFiltersCheckbox = document.getElementById('chatbot-remove-filters');

    if (settingsToggle && settingsPanel) {
      settingsToggle.addEventListener('click', () => {
        settingsPanel.style.display = settingsPanel.style.display === 'none' ? 'block' : 'none';
      });
    }

    if (personalitySelect) {
      personalitySelect.value = this.personality;
    }
    if (removeFiltersCheckbox) {
      removeFiltersCheckbox.checked = this.removeFilters;
    }

    if (settingsSave) {
      settingsSave.addEventListener('click', () => {
        this.personality = personalitySelect?.value || 'helpful';
        this.removeFilters = removeFiltersCheckbox?.checked || false;
        this.saveSettings();
        // Update page title/subtitle/transparency based on new personality
        const titleEl = document.getElementById('chatbot-page-title');
        const subEl = document.getElementById('chatbot-page-subtitle');
        const transText = document.getElementById('chatbot-transparency-text');
        const transIcon = document.querySelector('.ai-transparency-icon');
        if (titleEl) titleEl.textContent = this.getTitle();
        if (subEl) subEl.textContent = this.getSubtitle();
        if (transText) transText.textContent = this.getTransparencyText();
        if (transIcon) transIcon.textContent = this.personality === 'oracle' ? '🔮' : '🤖';
        this.showPromptToast('Settings saved');
        if (settingsPanel) settingsPanel.style.display = 'none';
      });
    }
  }

  showPromptToast(text) {
    const toast = document.createElement('div');
    toast.textContent = text;
    toast.style.cssText = 'position:fixed;bottom:24px;right:24px;padding:10px 16px;border-radius:8px;background:var(--success);color:#fff;font-size:0.875rem;z-index:9999;transition:opacity 300ms;';
    document.body.appendChild(toast);
    setTimeout(() => { toast.style.opacity = '0'; setTimeout(() => toast.remove(), 300); }, 2000);
  }

  async loadCustomPrompt() {
    const promptTextarea = document.getElementById('chatbot-custom-prompt');
    if (!promptTextarea) return;
    const userId = this.app?.state?.user?.email || localStorage.getItem('simplebeacon_user_id') || 'anonymous';
    try {
      const res = await fetch('/api/prompts/get?userId=' + encodeURIComponent(userId));
      if (res.ok) {
        const data = await res.json();
        if (data.prompt) promptTextarea.value = data.prompt;
        return;
      }
    } catch (e) {
      console['warn']('Failed to load custom prompt from API:', e);
    }
    // Fallback to localStorage
    const localPrompt = localStorage.getItem('chatbot_custom_prompt');
    if (localPrompt) promptTextarea.value = localPrompt;
  }

  async loadProviders() {
    const select = document.getElementById('chatbot-provider');
    const hardcoded = [
      { id: 'ollama', label: 'Ollama' },
      { id: 'openai', label: 'OpenAI' },
      { id: 'anthropic', label: 'Anthropic' }
    ];

    try {
      const res = await fetch('/api/chatbot/providers', { signal: AbortSignal.timeout(3000) });
      if (!res.ok) throw new Error('Providers endpoint unreachable');
      const data = await res.json();

      if (!Array.isArray(data.providers) || data.providers.length === 0) {
        throw new Error('No providers returned');
      }

// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
      select.innerHTML = '';
      data.providers.forEach(provider => {
        const option = document.createElement('option');
        option.value = provider.id;
        option.textContent = provider.label + (provider.available ? '' : ' (not configured)');
        option.disabled = !provider.available;
        select.appendChild(option);
      });

      const firstAvailable = data.providers.find(p => p.available);
      if (firstAvailable) {
        select.value = firstAvailable.id;
        this.selectedProvider = firstAvailable.id;
      } else {
        this.selectedProvider = '';
      }
    } catch (error) {
      // Fallback to hardcoded list with all disabled
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
      select.innerHTML = '';
      hardcoded.forEach(p => {
        const option = document.createElement('option');
        option.value = p.id;
        option.textContent = p.label + ' (server offline)';
        option.disabled = true;
        select.appendChild(option);
      });
    }
  }

  async sendMessage() {
    const input = document.getElementById('chatbot-input');
    const rawMessage = input.value.trim();

    if (!rawMessage || this.isLoading) return;

    if (!this.selectedProvider) {
      this.showErrorBanner('No AI provider configured. Add your own OpenAI or Anthropic API key in Settings → AI providers — keys are stored encrypted on your account.');
      return;
    }

    // Sanitize message to remove PII before processing
    const message = sanitizePrivacyData(rawMessage);

    // Add user message to history
    this.conversationHistory.push({ role: 'user', content: message });
    this.renderMessages();
    this.saveConversationHistory();

    input.value = '';
    this.isLoading = true;
    this.updateSendButton();
    this.hideErrorBanner();

    // Show typing indicator
    this.showTypingIndicator();

    try {
      const res = await fetch('/api/chatbot/message', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message,
          conversationHistory: this.conversationHistory.slice(0, -1),
          provider: this.selectedProvider,
          projectPath: this.app.state.defaultProjectPath || null,
          userId: this.app?.state?.user?.email || localStorage.getItem('simplebeacon_user_id') || 'anonymous',
          personality: this.personality,
          removeFilters: this.removeFilters
        })
      });

      // Remove typing indicator
      this.hideTypingIndicator();

      if (!res.ok) {
        if (res.status === 404) {
          throw new Error('Chatbot API not found. Ensure the ai-platform server is running.');
        }
        const errData = await res.json().catch(() => ({}));
        throw new Error(errData.message || errData.error || `HTTP ${res.status}: ${res.statusText}`);
      }

      // Create placeholder for assistant response
      const assistantMessageIndex = this.conversationHistory.length;
      this.conversationHistory.push({ role: 'assistant', content: '' });

      // Get the message container for streaming updates
      const container = document.getElementById('chatbot-messages');
      const messageElements = container.querySelectorAll('.chatbot-message');
      const targetBubble = messageElements[assistantMessageIndex]?.querySelector('.chatbot-message-text');

      if (targetBubble) {
        // Consume streaming response
        await this.consumeTokenStream(res, targetBubble);

        // Update history with final content
        this.conversationHistory[assistantMessageIndex].content = targetBubble.textContent;
      } else {
        // Fallback to non-streaming if streaming fails
        const data = await res.json();
        if (data.success) {
          this.conversationHistory[assistantMessageIndex].content = data.response;
        } else {
          this.showErrorBanner(data.message || 'The AI provider returned an error. Check provider configuration.');
          this.conversationHistory.pop(); // remove empty assistant placeholder
        }
      }
    } catch (error) {
      this.hideTypingIndicator();
      // Remove the empty assistant placeholder if we added one
      const last = this.conversationHistory[this.conversationHistory.length - 1];
      if (last && last.role === 'assistant' && last.content === '') {
        this.conversationHistory.pop();
      }
      this.showErrorBanner(error.message);
    } finally {
      this.isLoading = false;
      this.updateSendButton();
      this.renderMessages();
      this.saveConversationHistory();
    }
  }

  /**
   * Consumes the streaming response chunks from the chatbot api
   * and renders tokens incrementally on screen.
   * @param {Response} response - The active fetch response stream.
   * @param {HTMLElement} targetBubble - The UI text node container.
   */
  async consumeTokenStream(response, targetBubble) {
    const reader = response.body.getReader();
    const decoder = new TextDecoder('utf-8');
    let buffered = '';

    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffered += decoder.decode(value, { stream: true });
      }
      buffered += decoder.decode();

      // Try parsing the full buffered response as a single JSON object first.
      // The server returns res.json() (not NDJSON streaming), so the entire
      // response is one JSON object that may span multiple lines.
      try {
        const parsed = JSON.parse(buffered);
        if (parsed.response) {
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
          targetBubble.innerHTML = this.formatStreamedMessage(parsed.response);
          const container = document.getElementById('chatbot-messages');
          if (container) {
            container.scrollTo({ top: container.scrollHeight, behavior: 'auto' });
          }
          return;
        }
      } catch (e) {
        // Not a single JSON object — try line-by-line NDJSON parsing
      }

      // Fallback: parse as newline-delimited JSON (NDJSON) for streaming responses
      const lines = buffered.split('\n');
      let accumulatedText = '';
      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const parsed = JSON.parse(line);
          if (parsed.response) {
            accumulatedText += parsed.response;
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
            targetBubble.innerHTML = this.formatStreamedMessage(accumulatedText);
            const container = document.getElementById('chatbot-messages');
            if (container) {
              container.scrollTo({ top: container.scrollHeight, behavior: 'auto' });
            }
          }
        } catch (e) {
          // Ignore unparseable lines (partial chunks, keep-alives)
        }
      }
    } catch (error) {
      console.error('Streaming connection interrupted:', error);
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
      targetBubble.innerHTML += '<p class="error">[Stream Interrupted]</p>';
    } finally {
      reader.releaseLock();
    }
  }

  renderMessages() {
    const container = document.getElementById('chatbot-messages');
    if (!container) return;

    if (this.conversationHistory.length === 0) {
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
      container.innerHTML = `
        <div class="chatbot-welcome">
          <div class="chatbot-welcome-icon">🤖</div>
          <h3>Start a conversation</h3>
          <p>Ask about your codebase, get help with issues, or request code improvements.</p>
        </div>
      `;
      return;
    }

// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
    container.innerHTML = this.conversationHistory.map((msg, index) => `
      <div class="chatbot-message chatbot-message-${msg.role}">
        <div class="chatbot-message-content">
          <div class="chatbot-message-role">
            ${msg.role === 'user' ? 'You' : 'AI'}
            ${msg.role === 'assistant' ? `<button class="chatbot-copy-btn" data-index="${index}" title="Copy response">📋</button>` : ''}
          </div>
          <div class="chatbot-message-text">${this.formatMessage(msg.content)}</div>
        </div>
      </div>
    `).join('');

    // Add copy button event listeners
    container.querySelectorAll('.chatbot-copy-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        const index = parseInt(e.target.dataset.index);
        this.copyMessage(index);
      });
    });

    // Smooth scroll to bottom
    this.scrollToBottom(container);
  }

  formatMessage(content) {
    // First, extract and protect code blocks to prevent XSS
    const codeBlocks = [];
    let processed = content.replace(/```([\s\S]*?)```/g, (match, code) => {
      const index = codeBlocks.length;
      codeBlocks.push(escapeHtml(code));
      return `__CODEBLOCK_${index}__`;
    });

    // Protect inline code
    const inlineCodes = [];
    processed = processed.replace(/`([^`]+)`/g, (match, code) => {
      const index = inlineCodes.length;
      inlineCodes.push(escapeHtml(code));
      return `__INLINECODE_${index}__`;
    });

    // Escape remaining content
    processed = escapeHtml(processed);

    // Restore code blocks with proper HTML
    processed = processed.replace(/__CODEBLOCK_(\d+)__/g, (match, index) => {
      return `<pre class="chatbot-code-block"><code>${codeBlocks[index]}</code></pre>`;
    });

    // Restore inline code
    processed = processed.replace(/__INLINECODE_(\d+)__/g, (match, index) => {
      return `<code class="chatbot-inline-code">${inlineCodes[index]}</code>`;
    });

    // Preserve line breaks (but not in code blocks)
    processed = processed.replace(/<pre class="chatbot-code-block">[\s\S]*?<\/pre>/g, (match) => {
      return match.replace(/\n/g, '&#10;');
    });
    processed = processed.replace(/\n/g, '<br>');

    // Restore newlines in code blocks
    processed = processed.replace(/&#10;/g, '\n');

    return processed;
  }

  /**
   * Safely converts markdown strings to HTML blocks during an active token stream.
   * Automatically wraps unclosed backticks to prevent layout breakage.
   * @param {string} text - The raw, accumulating token stream text.
   * @returns {string} Safe, rendered HTML layout content.
   */
  formatStreamedMessage(text) {
    if (!text) return '';

    let processedText = text;

    // 1. Stream-Safe Guard: Detect unclosed triple backticks
    const backtickCount = (processedText.match(/```/g) || []).length;
    if (backtickCount % 2 !== 0) {
      // Dynamically append a temporary closing block for visual stability
      processedText += '\n```';
    }

    // 2. Stream-Safe Guard: Detect unclosed inline code backticks
    const inlineBacktickCount = (processedText.match(/`/g) || []).length;
    if (inlineBacktickCount % 2 !== 0) {
      processedText += '`';
    }

    // 3. Extract and protect code blocks using unique placeholders
    const codeBlocks = [];
    processedText = processedText.replace(/```([\s\S]*?)```/g, (match, code) => {
      const placeholder = `__CODE_BLOCK_PLACEHOLDER_${codeBlocks.length}__`;
      codeBlocks.push(code);
      return placeholder;
    });

    // 4. Extract and protect inline code
    const inlineBlocks = [];
    processedText = processedText.replace(/`([^`]+)`/g, (match, code) => {
      const placeholder = `__INLINE_PLACEHOLDER_${inlineBlocks.length}__`;
      inlineBlocks.push(code);
      return placeholder;
    });

    // 5. Run native XSS escaping on standard paragraph text strings
    processedText = escapeHtml(processedText);

    // 6. Restore protected inline code with safe text nodes
    inlineBlocks.forEach((code, index) => {
      const safeInline = `<code class="chatbot-inline-code">${escapeHtml(code)}</code>`;
      processedText = processedText.replace(`__INLINE_PLACEHOLDER_${index}__`, safeInline);
    });

    // 7. Restore protected structural code blocks with syntax wrappers
    codeBlocks.forEach((code, index) => {
      const safeBlock = `<pre class="chatbot-code-block"><code>${escapeHtml(code)}</code></pre>`;
      processedText = processedText.replace(`__CODE_BLOCK_PLACEHOLDER_${index}__`, safeBlock);
    });

    // 8. Preserve line breaks (but not in code blocks)
    processedText = processedText.replace(/<pre class="chatbot-code-block">[\s\S]*?<\/pre>/g, (match) => {
      return match.replace(/\n/g, '&#10;');
    });
    processedText = processedText.replace(/\n/g, '<br>');

    // 9. Restore newlines in code blocks
    processedText = processedText.replace(/&#10;/g, '\n');

    return processedText;
  }

  updateSendButton() {
    const btn = document.getElementById('chatbot-send');
    if (btn) {
      btn.disabled = this.isLoading;
      btn.textContent = this.isLoading ? 'Sending...' : 'Send';
    }
  }

  showTypingIndicator() {
    const container = document.getElementById('chatbot-messages');
    if (!container) return;
    
    const indicator = document.createElement('div');
    indicator.id = 'chatbot-typing-indicator';
    indicator.className = 'chatbot-message chatbot-message-assistant';
// TODO(security): review innerHTML usage here and sanitize dynamic content where applicable.
    indicator.innerHTML = `
      <div class="chatbot-message-content">
        <div class="chatbot-message-role">AI</div>
        <div class="chatbot-typing">
          <span class="chatbot-typing-dot"></span>
          <span class="chatbot-typing-dot"></span>
          <span class="chatbot-typing-dot"></span>
        </div>
      </div>
    `;
    container.appendChild(indicator);
    this.scrollToBottom(container);
  }

  hideTypingIndicator() {
    const indicator = document.getElementById('chatbot-typing-indicator');
    if (indicator) {
      indicator.remove();
    }
  }

  scrollToBottom(container) {
    if (!container) return;
    container.scrollTo({
      top: container.scrollHeight,
      behavior: 'smooth'
    });
  }

  loadConversationHistory() {
    try {
      const stored = localStorage.getItem(this.STORAGE_KEY);
      if (stored) {
        this.conversationHistory = JSON.parse(stored);
      }
    } catch (error) {
      console.error('Failed to load conversation history:', error);
      this.conversationHistory = [];
    }
  }

  saveConversationHistory() {
    try {
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(this.conversationHistory));
    } catch (error) {
      console.error('Failed to save conversation history:', error);
    }
  }

  loadSettings() {
    try {
      const stored = localStorage.getItem(this.SETTINGS_KEY);
      if (stored) {
        const settings = JSON.parse(stored);
        this.personality = settings.personality || 'helpful';
        this.removeFilters = settings.removeFilters || false;
      }
    } catch (error) {
      console.error('Failed to load settings:', error);
    }
  }

  saveSettings() {
    try {
      localStorage.setItem(this.SETTINGS_KEY, JSON.stringify({
        personality: this.personality,
        removeFilters: this.removeFilters
      }));
    } catch (error) {
      console.error('Failed to save settings:', error);
    }
  }

  copyMessage(index) {
    const message = this.conversationHistory[index];
    if (!message || !message.content) return;

    navigator.clipboard.writeText(message.content).then(() => {
      // Show brief success feedback
      const btn = document.querySelector(`.chatbot-copy-btn[data-index="${index}"]`);
      if (btn) {
        const originalText = btn.textContent;
        btn.textContent = '✓';
        btn.classList.add('copied');
        setTimeout(() => {
          btn.textContent = originalText;
          btn.classList.remove('copied');
        }, 1500);
      }
    }).catch(err => {
      console.error('Failed to copy message:', err);
    });
  }

  destroy() {
    // Cleanup event listeners if needed
  }
}
