"""
True-Positive Fixture: llmSlop engine
Engine ID: llmSlop
Expected Finding: LLM Slop Pattern (severity: medium+)
Language: Python

Intentionally contains AI placeholder patterns from the LLM slop catalog
(SB-FICTION-001, SB-FICTION-005, SB-FICTION-006).
The matrix validation runner expects at least one LLM slop finding.
"""

import requests

# YOUR_API_KEY_HERE — unresolved LLM placeholder (SB-FICTION-001)
API_KEY = "YOUR_API_KEY_HERE"

# Generated by Claude 3.5 Sonnet — AI debris (SB-FICTION-001)
def process_data(data):
    """Process the input data and return results."""
    # TODO: as discussed, implement the actual logic here (SB-FICTION-006)
    pass

def call_hallucinated_api():
    """Call a hallucinated SDK method that doesn't exist."""
    # Hallucinated SDK method (SB-FICTION-005)
    result = client.getOrCreate('user')
    records = client.fetchAllRecords()
    return result
