// simplebeacon-ignore: Scanner pattern definitions, test fixtures, dashboard code, security — all findings are false positives
import { ScanResult, Finding } from '../analyzers/workspaceAnalyzer';
import { getFixForFinding } from '../fixes/fixRegistry';

export interface AIReportOptions {
  includeFixes?: boolean;
  includeContext?: boolean;
  maxFindings?: number;
  format?: 'markdown' | 'json' | 'xml';
}

const DEFAULT_OPTIONS: AIReportOptions = {
  includeFixes: true,
  includeContext: true,
  maxFindings: 200,
  format: 'markdown',
};

/**
 * Export scan findings into an AI-optimized report format.
 * Markdown is the default — it is token-efficient, structured, and natively
 * understood by every major LLM.
 */
export function exportAIReport(result: ScanResult, projectRoot: string, options: AIReportOptions = {}): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const findings = result.findings || [];
  const summary = result.summary || {
    totalFiles: 0,
    filesAnalyzed: 0,
    totalFindings: 0,
    severityCounts: { critical: 0, high: 0, medium: 0, low: 0 },
    categoryCounts: {},
  };
  const categories = result.categories || {};

  switch (opts.format) {
    case 'json':
      return exportJSON(findings, summary, projectRoot, opts);
    case 'xml':
      return exportXML(findings, summary, projectRoot, opts);
    case 'markdown':
    default:
      return exportMarkdown(findings, summary, categories, projectRoot, opts);
  }
}

function exportMarkdown(
  findings: Finding[],
  summary: NonNullable<ScanResult['summary']>,
  categories: Record<string, Finding[]>,
  projectRoot: string,
  opts: AIReportOptions
): string {
  const lines: string[] = [];

  // ── Header ──
  lines.push(`# SimpleBeacon Scan Report — AI Analysis Input`);
  lines.push(`**Project root:** \`${projectRoot}\``);
  lines.push(`**Scan scope:** ${summary.filesAnalyzed} files analyzed out of ${summary.totalFiles} total`);
  lines.push(`**Total findings:** ${summary.totalFindings}`);
  lines.push(
    `**Severity distribution:** critical=${summary.severityCounts.critical || 0}, high=${summary.severityCounts.high || 0}, medium=${summary.severityCounts.medium || 0}, low=${summary.severityCounts.low || 0}`
  );
  lines.push('');

  // ── Executive Summary ──
  lines.push(`## Executive Summary`);
  lines.push(`This report contains code-quality and security findings detected by the SimpleBeacon static analyzer.`);
  lines.push(
    `Each finding includes the source location, the matched code snippet, surrounding context, and (where available) a suggested remediation.`
  );
  lines.push('');

  // ── Action Items (Critical + High first) ──
  const criticalHigh = findings.filter((f) => f.severity === 'critical' || f.severity === 'high');
  if (criticalHigh.length > 0) {
    lines.push(`## Priority Action Items (${criticalHigh.length})`);
    lines.push(`> These findings require immediate attention.`);
    lines.push('');
    for (const f of criticalHigh.slice(0, opts.maxFindings)) {
      lines.push(...renderFindingMarkdown(f, projectRoot, opts));
    }
  }

  // ── Remaining Findings grouped by category ──
  const severities: Array<'critical' | 'high' | 'medium' | 'low'> = ['medium', 'low'];
  for (const sev of severities) {
    const catFindings = Object.entries(categories).flatMap(([cat, items]) =>
      items.filter((f) => f.severity === sev).map((f) => ({ ...f, category: cat }))
    );

    if (catFindings.length === 0) continue;

    lines.push(`## ${capitalize(sev)} Severity Findings (${catFindings.length})`);
    lines.push('');

    for (const f of catFindings.slice(0, (opts.maxFindings || 200) - criticalHigh.length)) {
      lines.push(...renderFindingMarkdown(f, projectRoot, opts));
    }
  }

  // ── Remediation Guide (unique fixes) ──
  if (opts.includeFixes) {
    const fixable = findings.map((f) => ({ finding: f, fix: getFixForFinding(f) })).filter((x) => x.fix !== null);

    if (fixable.length > 0) {
      lines.push(`## Remediation Quick-Reference`);
      lines.push(`> These are the auto-fixable or suggested fixes for the detected patterns.`);
      lines.push('');
      const seen = new Set<string>();
      for (const { finding, fix } of fixable) {
        if (!fix) continue;
        const key = `${finding.patternId}|${fix.description}`;
        if (seen.has(key)) continue;
        seen.add(key);
        lines.push(`### ${finding.type} (${finding.patternId})`);
        lines.push(
          `- **File:** \`${relativePath(finding.file, projectRoot)}\` line ${finding.matches?.[0]?.line ?? '?'}`
        );
        lines.push(`- **Fix:** ${fix.description}`);
        lines.push(`- **Auto-fixable:** ${fix.autoFixable ? 'Yes' : 'No'}`);
        if (fix.replace) {
          lines.push(`- **Replacement pattern:** \`${fix.replace}\``);
        }
        lines.push('');
      }
    }
  }

  lines.push(`---`);
  lines.push(`*Generated by SimpleBeacon for AI-assisted remediation.*`);

  return lines.join('\n');
}

function renderFindingMarkdown(
  f: Finding & { category?: string },
  projectRoot: string,
  opts: AIReportOptions
): string[] {
  const lines: string[] = [];
  const relFile = relativePath(f.file, projectRoot);

  lines.push(`### ${f.type}${f.category ? ` [${f.category}]` : ''}`);
  lines.push(`- **Severity:** ${f.severity}`);
  lines.push(`- **Confidence:** ${(f.confidence ?? 0.85) * 100}%`);
  lines.push(`- **File:** \`${relFile}\``);

  for (const m of f.matches ?? []) {
    lines.push(`- **Line ${m.line}:**`);
    if (opts.includeContext && m.context?.length) {
      lines.push('```');
      for (const ctx of m.context) {
        lines.push(ctx);
      }
      lines.push('```');
    } else if (m.snippet) {
      lines.push(`\`${m.snippet}\``);
    }
  }

  if (opts.includeFixes && f.patternId) {
    const fix = getFixForFinding(f);
    if (fix) {
      lines.push(`- **Suggested fix:** ${fix.description}${fix.autoFixable ? ' (auto-fixable)' : ''}`);
    }
  }

  lines.push('');
  return lines;
}

function exportJSON(
  findings: Finding[],
  summary: NonNullable<ScanResult['summary']>,
  projectRoot: string,
  opts: AIReportOptions
): string {
  const enriched = findings.slice(0, opts.maxFindings).map((f) => {
    const fix = opts.includeFixes ? getFixForFinding(f) : null;
    return {
      ...f,
      file: relativePath(f.file, projectRoot),
      fix: fix
        ? {
            description: fix.description,
            search: fix.search.source,
            replace: fix.replace,
            autoFixable: fix.autoFixable,
          }
        : null,
    };
  });

  return JSON.stringify(
    {
      projectRoot,
      summary,
      findings: enriched,
    },
    null,
    2
  );
}

function exportXML(
  findings: Finding[],
  summary: NonNullable<ScanResult['summary']>,
  projectRoot: string,
  opts: AIReportOptions
): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<simplebeacon-report>');
  lines.push(`  <project>${escapeXml(projectRoot)}</project>`);
  lines.push(`  <summary>`);
  lines.push(`    <filesAnalyzed>${summary.filesAnalyzed}</filesAnalyzed>`);
  lines.push(`    <totalFindings>${summary.totalFindings}</totalFindings>`);
  lines.push(`  </summary>`);

  for (const f of findings.slice(0, opts.maxFindings)) {
    lines.push(`  <finding severity="${f.severity}" type="${escapeXml(f.type)}">`);
    lines.push(`    <file>${escapeXml(relativePath(f.file, projectRoot))}</file>`);
    for (const m of f.matches ?? []) {
      lines.push(`    <match line="${m.line}">`);
      lines.push(`      <snippet>${escapeXml(m.snippet)}</snippet>`);
      if (opts.includeContext && m.context) {
        lines.push(`      <context>${escapeXml(m.context.join('\n'))}</context>`);
      }
      lines.push(`    </match>`);
    }
    if (opts.includeFixes && f.patternId) {
      const fix = getFixForFinding(f);
      if (fix) {
        lines.push(`    <fix autoFixable="${fix.autoFixable}">${escapeXml(fix.description)}</fix>`);
      }
    }
    lines.push(`  </finding>`);
  }

  lines.push('</simplebeacon-report>');
  return lines.join('\n');
}

/* ── Helpers ── */

function relativePath(file: string, root: string): string {
  if (file.startsWith(root)) {
    return file.slice(root.length).replace(/^[/\\]/, '');
  }
  return file;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function escapeXml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
