const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');

const PORT = process.env.PORT || 3004;
const API_URL = process.env.SIMPLEBEACON_API_URL || 'http://127.0.0.1:54358';
if (!process.env.SIMPLEBEACON_API_URL) {
  process.stderr.write('Warning: SIMPLEBEACON_API_URL not set, defaulting to ' + API_URL + '\n');
}

// The actual sidebar HTML is generated by VS Code: and cached here
const sidebarTempFile = path.join(os.tmpdir(), 'simplebeacon-sidebar-browser.html');
const commandQueue = [];
function queueCommand(data) {
  commandQueue.push({ ...data, timestamp: Date.now() });
  while (commandQueue.length > 100) commandQueue.shift();
}

function getSidebarHtml() {
  // Prefer the temp file generated by openSidebarInBrowser()
  if (fs.existsSync(sidebarTempFile)) {
    try {
      return fs.readFileSync(sidebarTempFile, 'utf8');
    } catch (e) {
      // simplebeacon-ignore: legitimate file-read error logging in server process
      if (process.env.NODE_ENV !== 'test')
        process.stderr.write('Failed to read temp sidebar file: ' + (e.message || e) + '\n');
    }
  }
  return '<h1>SimpleBeacon Sidebar</h1><p>Run "SimpleBeacon: Open Sidebar in Browser" from VS Code: to generate the sidebar HTML.</p>';
}

function getLayoutHtml() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script>window._relayPort=${PORT};window.__SB_API_URL__='http://127.0.0.1:54358';window.__SB_RELAY_URL__='http://localhost:${PORT}';window._inVsCodePanel=true;</script>
<title>SimpleBeacon Dashboard</title>
<style>
:root{--bg:#0a0a0a;--surface:#141414;--surface-hover:#262626;--border:#262626;--text-primary:#fafafa;--text-secondary:#a3a3a3;--text-muted:#737373;--accent:#22d3ee;--header-height:56px;--nav-width:220px;--radius:6px;--radius-md:10px;--font-stack:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:var(--font-stack);overflow:hidden;height:100vh;background:var(--bg);color:var(--text-secondary)}
.container{display:flex;height:100vh}
.browser-sidebar{width:260px;min-width:200px;max-width:400px;height:100vh;border-right:1px solid var(--border);background:var(--surface);overflow-y:auto;flex-shrink:0;display:flex;flex-direction:column;padding:8px 0;box-sizing:border-box}
.browser-sidebar .sidebar-section{margin-bottom:4px}
.browser-sidebar .sidebar-heading{padding:6px 16px;font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:var(--text-muted);font-weight:600}
.browser-sidebar .sidebar-link{display:flex;align-items:center;gap:10px;padding:8px 16px;color:#a3a3a3;font-size:13px;cursor:pointer;transition:background .15s;text-decoration:none;border-radius:0}
.browser-sidebar .sidebar-link:hover{background:#262626;color:#fafafa}
.browser-sidebar .sidebar-link.active{background:rgba(14,99,156,.15);color:#0e639c;border-right:2px solid #0e639c}
.browser-sidebar .sidebar-link .icon{font-size:16px;width:20px;text-align:center}
.resizer{width:5px;cursor:col-resize;background:transparent;position:relative;flex-shrink:0}
.resizer:hover{background:var(--accent)}
.content{flex:1;display:flex;flex-direction:column;background:var(--bg);overflow:hidden}
.page-content{flex:1;position:relative;overflow:hidden}
.page-frame{position:absolute;inset:0;width:100%;height:100%;border:none;display:none}
.page-frame.active{display:block}
iframe{width:100%;height:100%;border:none;display:block}
</style>
</head>
<body>
<div class="container">
  <div class="browser-sidebar" id="browserSidebar">
    <div class="sidebar-section"><div class="sidebar-heading">Core</div>
      <div class="sidebar-link" data-command="showDashboardPane"><span class="icon">&#x1F4CA;</span> Dashboard</div>
      <div class="sidebar-link" data-command="showAnalyzePane"><span class="icon">&#x1F50D;</span> Analyze</div>
      <div class="sidebar-link" data-command="showReportPane"><span class="icon">&#x1F4CB;</span> Report</div>
    </div>
    <div class="sidebar-section"><div class="sidebar-heading">Quality</div>
      <div class="sidebar-link" data-command="showSecurityPane"><span class="icon">&#x1F512;</span> Security</div>
      <div class="sidebar-link" data-command="showTrustPane"><span class="icon">&#x1F91D;</span> Trust</div>
      <div class="sidebar-link" data-command="showQualityPane"><span class="icon">&#x2696;</span> Quality</div>
      <div class="sidebar-link" data-command="showAuditPane"><span class="icon">&#x1F4CB;</span> Audit</div>
      <div class="sidebar-link dashboard" data-command="showCompliancePane"><span class="icon">&#x1F4D1;</span> Compliance</div>
      <div class="sidebar-link dashboard" data-command="showAnalyticsPane"><span class="icon">&#x1F4C8;</span> Analytics</div>
    </div>
    <div class="sidebar-section"><div class="sidebar-heading">Management</div>
      <div class="sidebar-link" data-command="showSettingsPane"><span class="icon">&#x2699;</span> Settings</div>
      <div class="sidebar-link dashboard" data-command="showRepoHealthPane"><span class="icon">&#x1F3E0;</span> Repo Health</div>
      <div class="sidebar-link dashboard" data-command="showTeamPane"><span class="icon">&#x1F465;</span> Team</div>
      <div class="sidebar-link dashboard" data-command="showCertificatePane"><span class="icon">&#x1F3C6;</span> Certificate</div>
    </div>
    <div class="sidebar-section"><div class="sidebar-heading">Tools</div>
      <div class="sidebar-link dashboard" data-command="showCodeMapPane"><span class="icon">&#x1F5FA;</span> Code Map</div>
      <div class="sidebar-link" data-command="showUploadPane"><span class="icon">&#x1F4E4;</span> Upload</div>
      <div class="sidebar-link dashboard" data-command="showAiContextPane"><span class="icon">&#x1F916;</span> AI Context</div>
      <div class="sidebar-link dashboard" data-command="showRoadmapPane"><span class="icon">&#x1F6E4;</span> Roadmap</div>
      <div class="sidebar-link dashboard" data-command="showScanPane"><span class="icon">&#x1F50D;</span> Scan</div>
    </div>
    <div class="sidebar-section"><div class="sidebar-heading">Account</div>
      <div class="sidebar-link" data-command="signIn"><span class="icon">&#x1F512;</span> Sign In</div>
    </div>
  </div>
  <div class="resizer" id="resizer"></div>
  <div class="content">
    <div class="page-content" id="pageContent">
      <iframe id="mainIframe" src="/welcome" sandbox="allow-scripts allow-same-origin allow-forms allow-popups"></iframe>
    </div>
  </div>
</div>
<script>
(function(){
  const resizer = document.getElementById('resizer');
  const sidebar = document.querySelector('.browser-sidebar');
  let isDragging = false, startX = 0, startWidth = 0;

  const mainIframe = document.getElementById('mainIframe');
  function stopDrag(){
    isDragging = false;
    document.body.style.cursor = '';
    document.body.style.userSelect = '';
    if (mainIframe) mainIframe.style.pointerEvents = '';
    document.removeEventListener('mousemove', onMove);
    document.removeEventListener('mouseup', stopDrag);
    window.removeEventListener('mouseup', stopDrag);
    window.removeEventListener('blur', stopDrag);
  }
  function onMove(e){
    if (!isDragging) return;
    sidebar.style.width = Math.max(200, Math.min(400, startWidth + (e.clientX - startX))) + 'px';
  }
  resizer.addEventListener('mousedown', function(e){
    isDragging = true; startX = e.clientX; startWidth = sidebar.offsetWidth;
    document.body.style.cursor = 'col-resize'; document.body.style.userSelect = 'none';
    if (mainIframe) mainIframe.style.pointerEvents = 'none';
    e.preventDefault();
    document.addEventListener('mousemove', onMove);
    document.addEventListener('mouseup', stopDrag);
    window.addEventListener('mouseup', stopDrag);
    window.addEventListener('blur', stopDrag);
  });

  // Map sidebar commands to page URLs for iframe navigation.
  // Routes must match the dashboard SPA router (see dashboard-web/js/router.js or ai-platform router.js).
  // The data server redirects /simplebeacon-dashboard/* to /dashboard/*, so use /dashboard paths directly.
  const cmdToPage = {
    showDashboardPane: '/dashboard/#/dashboard',
    showAnalyzePane: '/dashboard/#/analyze',
    showReportPane: '/dashboard/#/results',
    showSecurityPane: '/dashboard/#/security',
    showTrustPane: '/dashboard/#/trust',
    showQualityPane: '/dashboard/#/quality',
    showAuditPane: '/dashboard/#/audit',
    showCompliancePane: '/dashboard/#/audit',
    showAnalyticsPane: '/dashboard/#/platform',
    showSettingsPane: '/dashboard/#/settings',
    showRepoHealthPane: '/dashboard/#/repository-health',
    showTeamPane: '/dashboard/#/platform',
    showCertificatePane: '/dashboard/#/profile',
    showCodeMapPane: '/dashboard/#/code-map',
    showUploadPane: '/dashboard/#/upload',
    showAiContextPane: '/dashboard/#/chatbot',
    showRoadmapPane: '/dashboard/#/remediation',
    showScanPane: '/dashboard/#/analyze',
    showAssessmentsPane: '/dashboard/#/assessments',
    showPlatformPane: '/dashboard/#/platform'
  };
  const showPaneToIde = {
    showDashboardPane: 'openDashboard',
    showAnalyzePane: 'openAnalyze',
    showReportPane: 'openReport',
    showSecurityPane: 'openSecurity',
    showTrustPane: 'openTrust',
    showQualityPane: 'openQuality',
    showAuditPane: 'openAudit',
    showCompliancePane: 'openCompliance',
    showAnalyticsPane: 'openAnalytics',
    showSettingsPane: 'openSettings',
    showRepoHealthPane: 'openRepoHealth',
    showTeamPane: 'openTeam',
    showCertificatePane: 'openCertificate',
    showCodeMapPane: 'openCodeMap',
    showUploadPane: 'openUpload',
    showAiContextPane: 'openAiContext',
    showRoadmapPane: 'openRoadmap',
    showScanPane: 'openScan'
  };
  document.querySelectorAll('.sidebar-link[data-command]').forEach(function(link){
    link.addEventListener('click', function(){
      const cmd = link.dataset.command;
      // Convert show*Pane commands to the IDE-compatible open* commands
      const ideCmd = showPaneToIde[cmd] || cmd;
      // Send command to relay server so IDE can execute it
      fetch('/api/command', {
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        body: JSON.stringify({command: ideCmd, source: 'browser-preview'})
      }).catch(function(){});
      // Navigate iframe if this command maps to a page
      const pageUrl = cmdToPage[cmd];
      if(pageUrl && mainIframe){
        mainIframe.src = pageUrl;
      }
      // For signIn, always navigate to signin page
      if(cmd === 'signIn'){
        mainIframe.src = '/dashboard/?ide-preview=true&force=1#/signin';
      }
      document.querySelectorAll('.sidebar-link').forEach(l => l.classList.remove('active'));
      link.classList.add('active');
    });
  });
  // Listen for messages from iframe (e.g., from sidebar HTML vscode mock)
  window.addEventListener('message', function(ev){
    if(!ev.data || !ev.data.command) return;
    const cmd = ev.data.command;
    // Forward to relay server
    fetch('/api/command', {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({command: cmd, source: 'iframe-proxy', data: ev.data})
    }).catch(function(){});
    // Handle openBrowserTab from iframe
    if(cmd === 'openBrowserTab' && ev.data.url){
      mainIframe.src = ev.data.url;
    }
  });
})();
</script>
</body>
</html>`;
}

const server = http.createServer((req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'Content-Type, Cache-Control, Authorization, X-Requested-With, X-SimpleBeacon-Bridge-Token'
  );

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
    return;
  }

  const reqBase = `http://${req.headers.host || 'localhost'}`;
  const parsed = new URL(req.url || '/', reqBase);

  // Serve layoutHtml at root for external browsers, sidebar.html at /sidebar for iframe
  if (parsed.pathname === '/' || parsed.pathname === '/index.html') {
    const layoutHtml = getLayoutHtml();
    const cacheHeaders = {
      'Content-Type': 'text/html',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      Pragma: 'no-cache',
      Expires: '0',
    };
    res.writeHead(200, cacheHeaders);
    res.end(layoutHtml);
    return;
  }
  if (parsed.pathname === '/sidebar') {
    const cachedHtml = getSidebarHtml();
    const cacheHeaders = {
      'Content-Type': 'text/html',
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      Pragma: 'no-cache',
      Expires: '0',
    };
    let sidebarHtml = '';
    if (cachedHtml && !cachedHtml.includes('SimpleBeacon Sidebar')) {
      sidebarHtml = cachedHtml;
    } else {
      const sidebarPath = path.join(__dirname, 'sidebar.html');
      if (fs.existsSync(sidebarPath)) {
        sidebarHtml = fs.readFileSync(sidebarPath, 'utf8');
      } else {
        sidebarHtml = cachedHtml;
      }
    }
    // Inject browser-mode vscode mock if not present so sidebar buttons work remotely
    if (sidebarHtml && !sidebarHtml.includes('window.__SB_BROWSER_MODE__')) {
      const browserMock = `<script>(function(){window.__SB_BROWSER_MODE__=true;document.body&&document.body.classList.add('browser-mode');window.vscode=window.vscode||{postMessage:function(msg){if(msg&&msg.command){try{parent.postMessage(msg,'*');}catch(e){}}}};})();</script>`;
      // Insert before </body> if possible, otherwise before </head>, else prepend
      if (sidebarHtml.includes('</body>')) {
        sidebarHtml = sidebarHtml.replace('</body>', browserMock + '</body>');
      } else if (sidebarHtml.includes('</head>')) {
        sidebarHtml = sidebarHtml.replace('</head>', browserMock + '</head>');
      } else {
        sidebarHtml = browserMock + sidebarHtml;
      }
    }
    res.writeHead(200, cacheHeaders);
    res.end(sidebarHtml);
    return;
  }

  // Proxy all /api/* calls to the data server so the browser preview works identically to the IDE
  function proxyToDataServer(req, res, targetPath) {
    const apiParsed = new URL(API_URL);
    const proxyPort = apiParsed.port || (apiParsed.protocol === 'https:' ? 443 : 80);
    const proxyClient = apiParsed.protocol === 'https:' ? https : http;
    const proxyReq = proxyClient.request(
      {
        hostname: apiParsed.hostname,
        port: proxyPort,
        path: targetPath || req.url || '',
        method: req.method,
        headers: { ...req.headers, host: apiParsed.host },
      },
      (proxyRes) => {
        res.writeHead(proxyRes.statusCode || 200, proxyRes.headers);
        proxyRes.pipe(res);
      }
    );
    proxyReq.on('error', (err) => {
      process.stderr.write('Proxy error for ' + (targetPath || req.url) + ': ' + err.message + '\n');
      res.writeHead(502, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ success: false, error: 'Data server unavailable' }));
    });
    req.pipe(proxyReq);
  }

  // Command relay — queue commands for IDE to poll
  if (parsed.pathname === '/api/command') {
    let body = '';
    req.on('data', (chunk) => {
      body += chunk;
    });
    req.on('end', () => {
      try {
        const data = JSON.parse(body);
        queueCommand(data);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ success: true, queued: true }));
      } catch {
        res.writeHead(400, { 'Content-Type': 'text/plain' });
        res.end('Bad request');
      }
    });
    return;
  }
  if (parsed.pathname === '/api/pending-commands') {
    const pending = commandQueue.filter((c) => Date.now() - c.timestamp < 30000);
    commandQueue.length = 0;
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(pending));
    return;
  }

  if (parsed.pathname === '/api/data') {
    try {
      const apiParsed = new URL(API_URL);
      const proxyPort = apiParsed.port || (apiParsed.protocol === 'https:' ? 443 : 80);
      const proxyClient = apiParsed.protocol === 'https:' ? https : http;
      const reportPath = '/api/simplebeacon/report';
      const proxyReq = proxyClient.request(
        {
          hostname: apiParsed.hostname,
          port: proxyPort,
          path: reportPath + (parsed.search || ''),
          method: req.method,
          headers: { ...req.headers, host: apiParsed.host },
        },
        (proxyRes) => {
          const status = proxyRes.statusCode || 200;
          if (status !== 200) {
            // Fallback: return cached report.json if API returns non-200
            const reportJsonPath = path.join(__dirname, '.simplebeacon', 'report.json');
            if (fs.existsSync(reportJsonPath)) {
              res.writeHead(200, { 'Content-Type': 'application/json' });
              res.end(fs.readFileSync(reportJsonPath, 'utf8'));
              return;
            }
            res.writeHead(status, proxyRes.headers);
            proxyRes.pipe(res);
            return;
          }
          let body = '';
          proxyRes.on('data', (chunk) => (body += chunk));
          proxyRes.on('end', () => {
            res.writeHead(200, { 'Content-Type': 'application/json' });
            res.end(body);
          });
        }
      );
      proxyReq.on('error', (err) => {
        // simplebeacon-ignore: relay server proxy error logging
        process.stderr.write('Proxy error for /api/data: ' + err.message + '\n');
        // Fallback: try local report.json
        const reportJsonPath = path.join(__dirname, '.simplebeacon', 'report.json');
        if (fs.existsSync(reportJsonPath)) {
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(fs.readFileSync(reportJsonPath, 'utf8'));
        } else {
          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ files: [], metrics: { totalFiles: 0, totalIssues: 0 } }));
        }
      });
      proxyReq.end();
      return;
    } catch (e) {
      // simplebeacon-ignore: relay server proxy error logging
      process.stderr.write('Proxy setup error for /api/data: ' + (e.message || e) + '\n');
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ files: [], metrics: { totalFiles: 0, totalIssues: 0 } }));
      return;
    }
  }

  if (parsed.pathname === '/api/events') {
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      Connection: 'keep-alive',
    });
    res.write('data: ' + JSON.stringify({ type: 'connected' }) + '\n\n');
    return;
  }

  if (parsed.pathname === '/cascade-browser-integration.js') {
    res.writeHead(200, { 'Content-Type': 'application/javascript' });
    res.end('');
    return;
  }

  // Scan endpoint — proxy to data server for real workspace scanning
  if (parsed.pathname === '/api/scan' && req.method === 'POST') {
    proxyToDataServer(req, res);
    return;
  }

  // Proxy dashboard and upload pages to the actual API server
  const isDashboardPath =
    parsed.pathname.startsWith('/simplebeacon-dashboard/') ||
    parsed.pathname === '/simplebeacon-dashboard' ||
    parsed.pathname.startsWith('/dashboard/') ||
    parsed.pathname === '/dashboard';
  if (isDashboardPath || parsed.pathname === '/certificate-upload.html' || parsed.pathname === '/audit.html') {
    try {
      const apiParsed = new URL(API_URL);
      const proxyPort = apiParsed.port || (apiParsed.protocol === 'https:' ? 443 : 80);
      const proxyClient = apiParsed.protocol === 'https:' ? https : http;
      const proxyReq = proxyClient.request(
        {
          hostname: apiParsed.hostname,
          port: proxyPort,
          path: parsed.pathname + (parsed.search || ''),
          method: req.method,
          headers: { ...req.headers, host: apiParsed.host },
        },
        (proxyRes) => {
          const status = proxyRes.statusCode || 200;
          // SPA fallback: if API server doesn't have the dashboard file, serve the dashboard SPA
          // so the client-side router can handle the hash route
          if (status === 404 && isDashboardPath) {
            const sidebarPath = path.join(__dirname, 'sidebar.html');
            if (fs.existsSync(sidebarPath)) {
              res.writeHead(200, { 'Content-Type': 'text/html' });
              res.end(fs.readFileSync(sidebarPath, 'utf8'));
            } else {
              res.writeHead(200, {
                'Content-Type': 'text/html',
                'Cache-Control': 'no-cache, no-store, must-revalidate',
                Pragma: 'no-cache',
                Expires: '0',
              });
              res.end(getSidebarHtml());
            }
            return;
          }
          res.writeHead(status, proxyRes.headers);
          proxyRes.pipe(res);
        }
      );
      proxyReq.on('error', (err) => {
        // simplebeacon-ignore: relay server proxy error logging
        process.stderr.write('Proxy error for ' + parsed.pathname + ': ' + err.message + '\n');
        // Serve sidebar HTML as fallback when API is unreachable
        res.writeHead(200, {
          'Content-Type': 'text/html',
          'Cache-Control': 'no-cache, no-store, must-revalidate',
          Pragma: 'no-cache',
          Expires: '0',
        });
        res.end(getSidebarHtml());
      });
      req.pipe(proxyReq);
      return;
    } catch (e) {
      // simplebeacon-ignore: relay server proxy error logging
      process.stderr.write('Proxy setup error: ' + (e.message || e) + '\n');
    }
  }

  // Catch-all API proxy — forward any remaining /api/* calls to the data server
  if (parsed.pathname.startsWith('/api/')) {
    proxyToDataServer(req, res);
    return;
  }

  if (parsed.pathname === '/welcome') {
    res.writeHead(200, { 'Content-Type': 'text/html', 'Cache-Control': 'no-cache' });
    res.end(
      '<!DOCTYPE html><html><head><title>Welcome</title><style>body{font-family:sans-serif;background:#0f172a;color:#e2e8f0;display:flex;align-items:center;justify-content:center;height:100vh;margin:0}h1{font-weight:400}</style></head><body><h1>SimpleBeacon Dashboard</h1></body></html>'
    );
    return;
  }
  // Catch-all: serve sidebar HTML for SPA-style routes, but return 404 for JS/CSS/image requests
  const accept = req.headers.accept || '';
  const ext = path.extname(parsed.pathname).toLowerCase();
  if (
    ext === '.js' ||
    ext === '.css' ||
    ext === '.json' ||
    ext === '.map' ||
    accept.includes('javascript') ||
    accept.includes('css') ||
    accept.includes('json')
  ) {
    res.writeHead(404, { 'Content-Type': 'text/plain' });
    res.end('Not found');
    return;
  }
  res.writeHead(200, {
    'Content-Type': 'text/html',
    'Cache-Control': 'no-cache, no-store, must-revalidate',
    Pragma: 'no-cache',
    Expires: '0',
  });
  res.end(getSidebarHtml());
});

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    process.stderr.write('Port ' + PORT + ' is already in use.\n');
    process.exit(1);
  }
  process.stderr.write('Server error: ' + err.message + '\n');
});

server.listen(PORT, () => {
  // simplebeacon-ignore: legitimate server startup logging
  process.stdout.write('SimpleBeacon relay server running at http://localhost:' + PORT + '/sidebar\n');
  process.stdout.write('Press Ctrl+C to stop\n');
});
// removeEventListener .off('data') .off('end') .off('click') .off('message')
