#!/usr/bin/env python3
"""
SimpleBeacon CLI automated test pipeline.
Runs the local CLI against a mock workspace and validates findings.
"""

import os
import subprocess
import json
import sys
import tempfile
import shutil

# Test cases: filename -> {content, expected_severity}
# Expected severity is the HIGHEST severity expected for that file.
# Using JS files since SimpleBeacon patterns are optimized for JS/TS.
TEST_CASES = {
    "clean_code.js": {
        "content": "// Valid handwritten utility\nfunction add(a, b) {\n  return a + b;\n}\nmodule.exports = { add };\n",
        "expected_severity": None  # No findings expected
    },
    "ai_slop.js": {
        "content": "// Generated by ChatGPT - do not modify\nfunction processData() {\n  // TODO: implement this later\n  var unusedVar = null;\n  return 'done';\n}\n",
        "expected_severity": "low"  # May trigger fiction/llm-slop or debug artifact
    },
    "security_vulnerability.js": {
        "content": "// Production config\nconst STRIPE_KEY = 'sk_live_qwertyuiopasdfghjklzxcvbnm1234';\nmodule.exports = { STRIPE_KEY };\n",
        "expected_severity": "high"  # Stripe key pattern should fire
    }
}


def find_cli_wrapper():
    """Locate the SimpleBeacon test wrapper (bypasses developer-tier JSON restrictions)."""
    # 1. Local wrapper in vscode-merged repo
    wrapper = os.path.join(os.path.dirname(__file__), "test_scan_wrapper.js")
    if os.path.isfile(wrapper):
        return ["node", wrapper]

    # 2. Check if simplebeacon is in PATH (npm global install)
    if shutil.which("simplebeacon"):
        return ["simplebeacon"]

    # 3. Check local monorepo CLI path
    repo_cli = os.path.join(
        os.path.dirname(__file__),
        "..", "packages", "simplebeacon-cli", "bin", "simplebeacon.js"
    )
    if os.path.isfile(repo_cli):
        return ["node", repo_cli]

    # 4. Check nested inside ai-platform
    alt_cli = os.path.join(
        os.path.dirname(__file__),
        "..", "ai-platform", "packages", "simplebeacon-cli", "bin", "simplebeacon.js"
    )
    if os.path.isfile(alt_cli):
        return ["node", alt_cli]

    return None


def setup_mock_repo():
    """Create a temporary workspace with test samples."""
    repo_dir = tempfile.mkdtemp(prefix="sb_mock_repo_")
    # Add a minimal package.json so files aren't flagged as unused
    pkg = os.path.join(repo_dir, "package.json")
    with open(pkg, "w", encoding="utf-8") as f:
        f.write('{"name":"mock-repo","version":"1.0.0","main":"clean_code.js"}\n')
    for filename, data in TEST_CASES.items():
        filepath = os.path.join(repo_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(data["content"])
    print(f"[ok] Mock repo created: {repo_dir}")
    return repo_dir


def run_system_scan(repo_dir):
    """Execute SimpleBeacon scan against the mock repo."""
    cli = find_cli_wrapper()
    if not cli:
        print("[X] Error: SimpleBeacon CLI or wrapper not found.")
        print("    Ensure test_scan_wrapper.js or packages/simplebeacon-cli exists.")
        sys.exit(1)

    # If using the wrapper, pass path directly; if using CLI binary, pass --path
    if "test_scan_wrapper.js" in cli[1] if len(cli) > 1 else False:
        cmd = cli + [repo_dir]
    else:
        cmd = cli + ["scan", "--path", repo_dir, "--format", "json"]

    print(f"[...] Running: {' '.join(cmd)}")

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0 and not result.stdout.strip():
        print(f"[X] Scan failed: {result.stderr}")
        sys.exit(1)

    try:
        report = json.loads(result.stdout)
    except json.JSONDecodeError:
        print("[X] Scan output is not valid JSON.")
        print(f"    stdout: {result.stdout[:500]}")
        sys.exit(1)

    return report


def validate_results(report, repo_dir):
    """Verify findings match expected severities per file."""
    passed = True
    raw_issues = report.get("rawIssues", [])

    # Map file -> highest severity found
    file_findings = {}
    for issue in raw_issues:
        filepath = issue.get("filePath") or issue.get("file") or ""
        filename = os.path.basename(filepath)
        severity = issue.get("severity") or issue.get("severityBand") or "low"
        if filename not in file_findings:
            file_findings[filename] = []
        file_findings[filename].append({
            "type": issue.get("type", "Unknown"),
            "severity": severity,
            "description": issue.get("description", "")[:60]
        })

    print("\n--- Evaluation Results ---")
    for filename, expected in TEST_CASES.items():
        expected_sev = expected["expected_severity"]
        findings = file_findings.get(filename, [])

        if expected_sev is None:
            # Expect no findings
            if findings:
                print(f"[FAIL] {filename}: Expected clean, got {len(findings)} finding(s)")
                for f in findings:
                    print(f"       - {f['severity']}: {f['type']} ({f['description']})")
                passed = False
            else:
                print(f"[PASS] {filename}: Clean (no findings)")
        else:
            # Expect at least one finding with severity >= expected
            if not findings:
                print(f"[FAIL] {filename}: Expected {expected_sev}, got no findings")
                passed = False
            else:
                highest = max(findings, key=lambda x: severity_rank(x["severity"]))
                actual_rank = severity_rank(highest["severity"])
                expected_rank = severity_rank(expected_sev)
                if actual_rank >= expected_rank:
                    print(f"[PASS] {filename}: Flagged as {highest['severity']} ({highest['type']})")
                else:
                    print(f"[FAIL] {filename}: Expected >= {expected_sev}, got {highest['severity']}")
                    passed = False

    # Print summary
    print(f"\n--- Summary ---")
    print(f"Total files tested: {len(TEST_CASES)}")
    print(f"Total CLI findings: {len(raw_issues)}")
    print(f"Quality Score: {report.get('qualityScore', 'N/A')}")
    print(f"Gate Pass: {report.get('gate', {}).get('pass', 'N/A')}")

    return passed


def severity_rank(sev):
    """Numeric rank for severity comparison."""
    return {"critical": 4, "high": 3, "medium": 2, "low": 1, "info": 0}.get(sev, 0)


if __name__ == "__main__":
    repo_dir = setup_mock_repo()
    try:
        report = run_system_scan(repo_dir)
        success = validate_results(report, repo_dir)
    finally:
        shutil.rmtree(repo_dir, ignore_errors=True)
        print(f"[ok] Cleaned up mock repo.")

    sys.exit(0 if success else 1)
