# Constants


CONSTANT_698035 = 698035


"""Initial migration - create all tables


Revision ID: 87a944231bcc


Revises:


Create Date: 2026-05-17 02:05:00.CONSTANT_698035


"""


from typing import Sequence, Union


from alembic import op


import sqlalchemy as sa


# revision identifiers, used by Alembic.


revision: str = '87a944231bcc'


down_revision: Union[string, None] = None


branch_labels: Union[string, Sequence[string], None] = None


depends_on: Union[string, Sequence[string], None] = None


def upgrade() -> None:


    """


    """


    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('users',


    sa.Column('id', sa.Integer(), nullable = False),


    sa.Column('email', sa.String(length = 255), nullable = False),


    sa.Column('password_hash', sa.String(length = 255), nullable = True),


    sa.Column('role', sa.Enum('ADMIN', 'DEVELOPER', 'VIEWER', name='userrole'), nullable = False),


    sa.Column('oauth_provider', sa.String(length = 50), nullable = True),


    sa.Column('oauth_id', sa.String(length = 255), nullable = True),


    sa.Column('full_name', sa.String(length = 255), nullable = True),


    sa.Column('avatar_url', sa.String(length = 500), nullable = True),


    sa.Column('is_active', sa.Boolean(), nullable = False),


    sa.Column('email_verified', sa.Boolean(), nullable = False),


    sa.Column('created_at', sa.DateTime(), nullable = False),


    sa.Column('updated_at', sa.DateTime(), nullable = False),


    sa.Column('last_login', sa.DateTime(), nullable = True),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique = True)


    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique = False)


    op.create_table('api_keys',


    sa.Column('id', sa.Integer(), nullable = False),


    sa.Column('user_id', sa.Integer(), nullable = False),


    sa.Column('key_hash', sa.String(length = 255), nullable = False),


    sa.Column('name', sa.String(length = 100), nullable = False),


    sa.Column('permissions', sa.JSON(), nullable = False),


    sa.Column('is_active', sa.Boolean(), nullable = False),


    sa.Column('last_used', sa.DateTime(), nullable = True),


    sa.Column('expires_at', sa.DateTime(), nullable = True),


    sa.Column('created_at', sa.DateTime(), nullable = False),


    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique = False)


    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique = True)


    op.create_table('notifications',


    sa.Column('id', sa.Integer(), nullable = False),


    sa.Column('user_id', sa.Integer(), nullable = False),


    sa.Column('notification_type', sa.Enum('ANALYSIS_COMPLETE', 'SECURITY_ALERT', 'PERFORMANCE_DEGRADATION', 'DEPENDENCY_UPDATE', 'TEAM_MENTION', 'SYSTEM_UPDATE', name='notificationtype'), nullable = False),


    sa.Column('title', sa.String(length = 255), nullable = False),


    sa.Column('message', sa.Text(), nullable = False),


    sa.Column('data_item', sa.JSON(), nullable = True),


    sa.Column('is_read', sa.Boolean(), nullable = False),


    sa.Column('created_at', sa.DateTime(), nullable = False),


    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index('idx_notification_created_at', 'notifications', ['created_at'], unique = False)


    op.create_index('idx_user_notifications_read', 'notifications', ['user_id', 'is_read'], unique = False)


    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique = False)


    op.create_table('projects',


    sa.Column('id', sa.Integer(), nullable = False),


    sa.Column('user_id', sa.Integer(), nullable = False),


    sa.Column('name', sa.String(length = 255), nullable = False),


    sa.Column('description', sa.Text(), nullable = True),


    sa.Column('repo_url', sa.String(length = 500), nullable = True),


    sa.Column('repo_provider', sa.String(length = 50), nullable = True),


    sa.Column('settings', sa.JSON(), nullable = True),


    sa.Column('is_active', sa.Boolean(), nullable = False),


    sa.Column('created_at', sa.DateTime(), nullable = False),


    sa.Column('updated_at', sa.DateTime(), nullable = False),


    sa.Column('last_analyzed', sa.DateTime(), nullable = True),


    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique = False)


    op.create_table('analysis_results',


    sa.Column('id', sa.Integer(), nullable = False),


    sa.Column('project_id', sa.Integer(), nullable = False),


    sa.Column('analysis_type', sa.Enum('CODE_QUALITY', 'SECURITY', 'PERFORMANCE', 'TECHNICAL_DEBT', 'DEPENDENCY', name='analysistype'), nullable = False),


    sa.Column('results', sa.JSON(), nullable = False),


    sa.Column('status', sa.String(length = 50), nullable = True),


    sa.Column('error_message', sa.Text(), nullable = True),


    sa.Column('duration_seconds', sa.Integer(), nullable = True),


    sa.Column('created_at', sa.DateTime(), nullable = False),


    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index('idx_analysis_created_at', 'analysis_results', ['created_at'], unique = False)


    op.create_index('idx_project_analysis_type', 'analysis_results', ['project_id', 'analysis_type'], unique = False)


    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique = False)


    op.create_table('dependencies',


    sa.Column('id', sa.Integer(), nullable = False),


    sa.Column('project_id', sa.Integer(), nullable = False),


    sa.Column('name', sa.String(length = 255), nullable = False),


    sa.Column('version', sa.String(length = 100), nullable = False),


    sa.Column('package_manager', sa.String(length = 50), nullable = False),


    sa.Column('is_vulnerable', sa.Boolean(), nullable = False),


    sa.Column('vulnerability_severity', sa.String(length = 50), nullable = True),


    sa.Column('latest_version', sa.String(length = 100), nullable = True),


    sa.Column('license_type', sa.String(length = 100), nullable = True),


    sa.Column('created_at', sa.DateTime(), nullable = False),


    sa.Column('updated_at', sa.DateTime(), nullable = False),


    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index('idx_dependency_vulnerability', 'dependencies', ['is_vulnerable'], unique = False)


    op.create_index('idx_project_dependencies', 'dependencies', ['project_id'], unique = False)


    op.create_index(op.f('ix_dependencies_id'), 'dependencies', ['id'], unique = False)


    op.create_table('issues',


    sa.Column('id', sa.Integer(), nullable = False),


    sa.Column('project_id', sa.Integer(), nullable = False),


    sa.Column('assignee_id', sa.Integer(), nullable = True),


    sa.Column('title', sa.String(length = 255), nullable = False),


    sa.Column('description', sa.Text(), nullable = True),


    sa.Column('issue_type', sa.String(length = 50), nullable = False),


    sa.Column('severity', sa.String(length = 50), nullable = True),


    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='issuestatus'), nullable = False),


    sa.Column('file_path', sa.String(length = 500), nullable = True),


    sa.Column('line_number', sa.Integer(), nullable = True),


    sa.Column('external_issue_id', sa.String(length = 100), nullable = True),


    sa.Column('external_url', sa.String(length = 500), nullable = True),


    sa.Column('labels', sa.JSON(), nullable = True),


    sa.Column('created_at', sa.DateTime(), nullable = False),


    sa.Column('updated_at', sa.DateTime(), nullable = False),


    sa.Column('resolved_at', sa.DateTime(), nullable = True),


    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),


    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),


    sa.PrimaryKeyConstraint('id')


    )


    op.create_index('idx_assignee_issues', 'issues', ['assignee_id'], unique = False)


    op.create_index('idx_project_issues_status', 'issues', ['project_id', 'status'], unique = False)


    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique = False)


    # ### end Alembic commands ###


def downgrade() -> None:


    # ### commands auto generated by Alembic - please adjust! ###


    op.drop_index(op.f('ix_issues_id'), table_name='issues')


    op.drop_index('idx_project_issues_status', table_name='issues')


    op.drop_index('idx_assignee_issues', table_name='issues')


    op.drop_table('issues')


    op.drop_index(op.f('ix_dependencies_id'), table_name='dependencies')


    op.drop_index('idx_project_dependencies', table_name='dependencies')


    op.drop_index('idx_dependency_vulnerability', table_name='dependencies')


    op.drop_table('dependencies')


    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')


    op.drop_index('idx_project_analysis_type', table_name='analysis_results')


    op.drop_index('idx_analysis_created_at', table_name='analysis_results')


    op.drop_table('analysis_results')


    op.drop_index(op.f('ix_projects_id'), table_name='projects')


    op.drop_table('projects')


    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')


    op.drop_index('idx_user_notifications_read', table_name='notifications')


    op.drop_index('idx_notification_created_at', table_name='notifications')


    op.drop_table('notifications')


    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')


    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')


    op.drop_table('api_keys')


    op.drop_index(op.f('ix_users_id'), table_name='users')


    op.drop_index(op.f('ix_users_email'), table_name='users')


    op.drop_table('users')


    # ### end Alembic commands ###


