#!/usr/bin/env python3
import ast
import re
import os
import sys
import json

AI_INDICATORS = {
    "provenance_metadata": [
        rb"com\.anthropic\.claude", rb"github\.copilot", rb"synthid",
        rb"\x00x-prov-sig", rb"application/x-prov-metadata"
    ],
    "invisible_unicode": [
        "\u200b",  # Zero-width space
        "\u202f",  # Narrow no-break space
        "\ufeff"   # BOM inside unexpected lines
    ]
}

class AICodeWatermarkDetector(ast.NodeVisitor):
    def __init__(self, source_code):
        self.source_code = source_code
        self.anomalies = []
        self.ai_score = 0.0

    def analyze(self):
        try:
            tree = ast.parse(self.source_code)
            self.visit(tree)
        except SyntaxError:
            # Fallback to textual heuristics
            pass

        self.check_raw_text_heuristics()
        self.calculate_probability_score()
        return {
            "ai_score_pct": min(self.ai_score * 100, 100.0),
            "anomalies_detected": self.anomalies
        }

    def visit_FunctionDef(self, node):
        if len(node.name) > 35 and ("helper" in node.name or "wrapper" in node.name or "handler" in node.name):
            self.anomalies.append(f"Robotic overly-verbose function signature: '{node.name}'")
            self.ai_score += 0.25
        self.generic_visit(node)

    def visit_ExceptHandler(self, node):
        if node.type is None:
            if len(node.body) == 1 and isinstance(node.body[0], (ast.Pass, ast.Continue)):
                self.anomalies.append(f"AI-style bare except/pass block (Line {getattr(node, 'lineno', '?')})")
                self.ai_score += 0.30
        self.generic_visit(node)

    def check_raw_text_heuristics(self):
        for marker in AI_INDICATORS["invisible_unicode"]:
            if marker in self.source_code:
                count = self.source_code.count(marker)
                self.anomalies.append(f"Detected invisible tracker token unicode sequence ({marker}) x{count}")
                self.ai_score += 0.40

        ai_comments = [
            r"# Insert your logic here",
            r"// Generated by AI assistant",
            r"# TODO: implement error handling"
        ]
        for pattern in ai_comments:
            if re.search(pattern, self.source_code, re.IGNORECASE):
                self.anomalies.append(f"Matched boilerplate LLM scaffolding comment pattern: '{pattern}'")
                self.ai_score += 0.35

    def calculate_probability_score(self):
        # keep as a simple linear aggregator for now
        # cap handled in analyze()
        pass


def scan_file_for_ai_marks(file_path):
    if not os.path.exists(file_path):
        return {"error": "File route missing"}

    with open(file_path, 'rb') as f:
        raw_bytes = f.read()

    detected_metadata = []
    for sig in AI_INDICATORS["provenance_metadata"]:
        try:
            if re.search(sig, raw_bytes, re.IGNORECASE):
                detected_metadata.append(sig.decode('utf-8', errors='ignore'))
        except re.error:
            # non-textual pattern; ignore
            pass

    try:
        source_text = raw_bytes.decode('utf-8')
    except UnicodeDecodeError:
        source_text = raw_bytes.decode('latin-1', errors='ignore')

    detector = AICodeWatermarkDetector(source_text)
    metrics = detector.analyze()

    if detected_metadata:
        metrics["anomalies_detected"].append(f"CRITICAL: Cryptographic provenance signature found: {detected_metadata}")
        metrics["ai_score_pct"] = 100.0

    return metrics


def scan_path(path):
    results = {}
    if os.path.isfile(path):
        results[path] = scan_file_for_ai_marks(path)
        return results

    for root, dirs, files in os.walk(path):
        for fn in files:
            if fn.endswith(('.py', '.js', '.ts', '.cjs', '.mjs', '.jsx', '.tsx', '.yml', '.yaml')):
                fp = os.path.join(root, fn)
                rel = os.path.relpath(fp)
                try:
                    results[rel] = scan_file_for_ai_marks(fp)
                except Exception as e:
                    results[rel] = {"error": str(e)}
    return results


def main(argv):
    target = argv[1] if len(argv) > 1 else '.'
    out = scan_path(target)
    json_out = json.dumps({"target": target, "results": out}, indent=2)
    print(json_out)
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv))
