import os
import json
from spot_ai_watermarks import scan_file_for_ai_marks

# Define localized file pathways for the verification sweep
TEST_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../test_fixtures"))
os.makedirs(TEST_DIR, exist_ok=True)

# [1;34m[0m[0m
# [0mFixture 1: Pristine human-written source code
CLEAN_CODE = """def calculate_total(price, tax_rate):
    if price < 0:
        raise ValueError("Price cannot be negative")
    return price * (1 + tax_rate)
"""

# [0mFixture 2: Explicit digital provenance watermark (Metadata Header Match)
METADATA_CODE = """# Generated by github.copilot and com.anthropic.claude to satisfy compliance rules
# application/x-prov-metadata signature active
def process_data(payload):
    return payload
"""

# [0mFixture 3: Invisible structural space tracking bias (KGW / Token Space matching)
ANOMALY_CODE = """def process_data_payload_transaction_records_helper_utility(data):
    # Insert your logic here
    try:
        parsed_endpoint = data + "\u200b" # Hidden tracking space sequence
        return parsed_endpoint
    except:
        pass
"""


def setup_fixtures():
    fixtures = {
        "clean_human.py": CLEAN_CODE,
        "ai_metadata_marked.py": METADATA_CODE,
        "ai_structural_anomaly.py": ANOMALY_CODE
    }
    paths = {}
    for name, content in fixtures.items():
        p = os.path.join(TEST_DIR, name)
        with open(p, "w", encoding="utf-8") as f:
            f.write(content)
        paths[name] = p
    return paths


def run_watermark_test_suite():
    print("🔬 Initializing SimpleBeacon Local AI Watermark Analysis Sweep...\n")
    paths = setup_fixtures()
    
    for name, path in paths.items():
        print(f"📁 Scanning target file: {name}")
        metrics = scan_file_for_ai_marks(path)
        print(f"📊 AI Probability Score: {metrics.get('ai_score_pct', 'N/A')}%")
        print(f"🕵️ Detected Anomalies: {json.dumps(metrics.get('anomalies_detected', metrics.get('anomalies', [])), indent=2)}")
        print("-" * 60)


if __name__ == "__main__":
    run_watermark_test_suite()
