/** Jest config for dashboard page tests (routing, samples, stub API, E2E structure). */
const path = require('path');

process.env.CI = process.env.CI || 'true';
process.env.SIMPLEBEACON_INTERNAL_DASHBOARD = process.env.SIMPLEBEACON_INTERNAL_DASHBOARD || 'true';
if (!process.env.JEST_COVERAGE_SUMMARY_PATH) {
    process.env.JEST_COVERAGE_SUMMARY_PATH = path.join(__dirname, 'tests/fixtures/jest-coverage-summary.json');
}

module.exports = {
    testEnvironment: 'node',
    setupFiles: [path.join(__dirname, 'tests/jest-coverage-env.js')],
    testMatch: [
        '**/tests/unit/payload-routing.test.js',
        '**/tests/unit/page-samples.test.js',
        '**/tests/unit/phase2-database-config.test.js',
        '**/tests/unit/phase2-integration-bootstrap.test.js',
        '**/tests/unit/secret-config.test.js',
        '**/tests/unit/path-safety.test.js',
        '**/tests/unit/client-error.test.js',
        '**/tests/unit/phase2-redis-config.test.js',
        '**/tests/unit/redis-cache.test.js',
        '**/tests/unit/user-service.test.js',
        '**/tests/unit/snapshot-resolver.test.js',
        '**/tests/unit/snapshot-seeds.test.js',
        '**/tests/integration/dashboard-stub-api.test.js',
        '**/tests/integration/simplebeacon-api.test.js',
        '**/tests/integration/simplebeacon-monetization.test.js',
        '**/tests/integration/scanner.test.js',
        '**/tests/integration/ai-validation-api.test.js',
        '**/tests/integration/roadmap-analysis-history.test.js',
        '**/tests/integration/phase2-integration.test.js',
        '**/tests/unit/mock-data-scanner.test.js',
        '**/tests/unit/scan-scope.test.js',
        '**/tests/unit/data-maintenance-analyzers.test.js',
        '**/tests/unit/file-merger-reduction-scanner.test.js',
        '**/tests/unit/codebase-analyzer.test.js',
        '**/tests/unit/complete-scan-audit-report.test.js',
        '**/tests/unit/audit-remediation-recipes.test.js',
        '**/tests/unit/upgrade-legacy-audit-html.test.js',
        '**/tests/unit/universal-language-framework.test.js',
        '**/tests/unit/code-understanding.test.js',
        '**/tests/unit/app-logger.test.js',
        '**/tests/unit/src-app-logger.test.js',
        '**/tests/unit/trust-verification-payload.test.js',
        '**/tests/unit/trust-api-routes.test.js',
        '**/tests/unit/repository-health-payload.test.js',
        '**/tests/unit/repository-health-preview-ui.test.js',
        '**/tests/unit/security-scanner-view.test.js',
        '**/tests/unit/merge-preview.test.js',
        '**/tests/unit/strategic-insights-engine.test.js',
        '**/tests/unit/code-roadmap-generator.test.js',
        '**/tests/unit/code-roadmap-phase2.test.js',
        '**/tests/unit/central-data-config.test.js',
        '**/tests/unit/npm-audit-runner.test.js',
        '**/tests/unit/dashboard-home-builder.test.js',
        '**/tests/unit/dashboard-mock-wiring.test.js',
        '**/tests/unit/dashboard-metrics-service.test.js',
        '**/tests/unit/jest-coverage-reader.test.js',
        '**/tests/unit/llama-cpp-hints.test.js',
        '**/tests/unit/fuzzy-content-matcher.test.js',
        '**/tests/unit/ai-systems-issue-analyzer.test.js',
        '**/tests/unit/roadmap-data-analyzer.test.js',
        '**/tests/unit/roadmap-history-metrics.test.js',
        '**/tests/unit/local-model-service.test.js',
        '**/tests/unit/ollama-client.test.js',
        '**/tests/unit/model-inference-service.test.js',
        '**/tests/unit/flexible-analyze-api.test.js',
        '**/tests/unit/data-cleanup-scan.test.js',
        '**/tests/unit/upload-routes.test.js',
        '**/tests/unit/core-boundary.test.js',
        '**/tests/unit/gguf-issues-api.routes.test.js',
        '**/tests/unit/config-schema.test.js',
        '**/tests/unit/audit-baseline-guard.test.js',
        '**/tests/integration/local-models-api.test.js',
        '**/tests/e2e/dashboard-pages.e2e.test.js',
        '**/tests/e2e/simplebeacon-dashboard.e2e.test.js'
    ],
    testPathIgnorePatterns: ['/node_modules/', '/docs/archive/'],
    collectCoverageFrom: [
        'web/scripts/payload-routing.js',
        'src/api/dashboard-stub-api.js',
        'server/config/database.js',
        'server/bootstrap/phase2-integration.js',
        'server/services/user-service.js',
        'server/lib/snapshot-resolver.js',
        'server/lib/npm-audit-runner.js',
        'server/lib/app-logger.js'
    ],
    coverageDirectory: 'coverage/dashboard',
    coverageReporters: ['text', 'json-summary', 'lcov', 'json'],
    verbose: true,
    testTimeout: 15000
};
